My Application: ComGraphics/Source/Application.cpp File Reference
Application.cpp File Reference
#include "Application.h"
#include <stdio.h>
#include <stdlib.h>
#include "SceneOpening.h"
#include "SceneStart.h"
#include "SceneEnd.h"
#include "CutSceneOne.h"
#include "SceneLevelOneA.h"
#include "SceneLevelOneB.h"
#include "SceneLevelTwo.h"
#include "OpeningCutScene.h"
#include "OpeningCutScene2.h"
#include "SceneEndCutScene.h"
#include "Credits.h"
Functions
static void error_callback (int error, const char *description)
static void key_callback (GLFWwindow *window, int key, int scancode, int action, int mods)
void resize_callback (GLFWwindow *window, int w, int h)
void scroll_callback (GLFWwindow *m_window, double xoffset, double yoffset)
Variables
const unsigned char FPS = 60
const unsigned int frameTime = 1000 / FPS
GLFWwindow * m_window
Function Documentation
static void error_callback (int error, const char * description) static
Definition at line 29 of file Application.cpp.
Referenced by Application::Init().
static void key_callback (GLFWwindow * window, int key, int scancode, int action, int mods) static
Definition at line 36 of file Application.cpp.
void resize_callback (GLFWwindow * window, int w, int h)
Definition at line 69 of file Application.cpp.
Referenced by Application::Init().
void scroll_callback (GLFWwindow * m_window, double xoffset, double yoffset)
Definition at line 74 of file Application.cpp.
References Application::mouse_scroll.
Referenced by Application::Init(), and Application::Run().
Variable Documentation
const unsigned char FPS = 60
Definition at line 23 of file Application.cpp.
const unsigned int frameTime = 1000 / FPS
Definition at line 24 of file Application.cpp.
Referenced by Application::Run().
GLFWwindow* m_window
Definition at line 25 of file Application.cpp.
Referenced by Camera3::CameraRotation(), Application::Exit(), Application::Init(), Camera3::Init(), and Application::Run().