My Application: SceneStart Class Reference
SceneStart Class Reference
#include <SceneStart.h>
Public Member Functions
SceneStart ()
~SceneStart ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_MAINDOORLEFT,
GEO_MAINDOORRIGHT, GEO_RUBBLE, GEO_PORTRAIT, GEO_PLANETFLOOR,
GEO_FACILITYFLOOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FACILITYWALLS,
GEO_FACILITYCEILINGS, GEO_LHAND, GEO_RHAND, GEO_TOOLUIONE,
GEO_TOOLUITWO, GEO_TOOLUITHREE, GEO_TOOLUIFOUR, GEO_HANDICON,
GEO_PICKAXE, GEO_PICKAXEICON, GEO_BAT, GEO_BATICON,
GEO_SWORD, GEO_SWORDICON, GEO_GHOST1, GEO_DEADBODY,
GEO_BLOOD1, GEO_HEALTHBAR, GEO_STAMINABAR, GEO_HEALTHICON,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSceneStart ()
void RenderSkyBox ()
void RenderFloor ()
void RenderDownWall (int xPosLarge, int xPosSmall, int zPos)
void RenderUpWall (int xPosLarge, int xPosSmall, int zPos)
void RenderRightWall (int zPosLarge, int zPosSmall, int xPos)
void RenderLeftWall (int zPosLarge, int zPosSmall, int xPos)
void RenderGhost ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void checkPlayerPos (double dt, int checkRate, int lessenSpeed)
void checkPlayerPosMisc ()
void Collision (float smallx, float largex, float smallz, float largez)
bool proximitycheck (float smallx, float largex, float smallz, float largez)
void ToolsUI ()
void MouseScrollToolSlot ()
void RenderMouseScrollToolSlot ()
void ToolSelectionMouseScroll ()
void RenderToolIcon ()
void MouseClickFunction (double dt)
void ChangeFirstCutScene ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
misc Misc
SwitchLightPuzzle Switches
float FPS
bool displayInteract
float mobTimeCount
Detailed Description
Definition at line 15 of file SceneStart.h.
Member Enumeration Documentation
enum SceneStart::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_MAINDOORLEFT
GEO_MAINDOORRIGHT
GEO_RUBBLE
GEO_PORTRAIT
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_LHAND
GEO_RHAND
GEO_TOOLUIONE
GEO_TOOLUITWO
GEO_TOOLUITHREE
GEO_TOOLUIFOUR
GEO_HANDICON
GEO_PICKAXE
GEO_PICKAXEICON
GEO_BAT
GEO_BATICON
GEO_SWORD
GEO_SWORDICON
GEO_GHOST1
GEO_DEADBODY
GEO_BLOOD1
GEO_HEALTHBAR
GEO_STAMINABAR
GEO_HEALTHICON
NUM_GEOMETRY
Definition at line 17 of file SceneStart.h.
enum SceneStart::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 79 of file SceneStart.h.
Constructor & Destructor Documentation
SceneStart::SceneStart ()
Definition at line 15 of file SceneStart.cpp.
SceneStart::~SceneStart ()
Definition at line 19 of file SceneStart.cpp.
Member Function Documentation
void SceneStart::ChangeFirstCutScene () private
Definition at line 410 of file SceneStart.cpp.
References displayInteract, Application::FirstCutScene(), Application::IsKeyPressed(), and proximitycheck().
Referenced by Update().
void SceneStart::checkPlayerPos (double dt, int checkRate, int lessenSpeed) private
void SceneStart::checkPlayerPosMisc () private
Definition at line 225 of file SceneStart.cpp.
References camera, misc::camX, misc::camY, misc::camZ, Misc, Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneStart::Collision (float smallx, float largex, float smallz, float largez) private
Definition at line 209 of file SceneStart.cpp.
References camera, Math::DegreeToRadian(), Camera::position, Camera3::rotationX, Camera3::rotationY, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneStart::Exit () virtual
Implements Scene.
Definition at line 673 of file SceneStart.cpp.
References m_programID, and m_vertexArrayID.
void SceneStart::Init () virtual
Implements Scene.
Definition at line 23 of file SceneStart.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BAT, GEO_BATICON, GEO_BOTTOM, GEO_DEADBODY, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FRONT, GEO_HANDICON, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_LEFT, GEO_LHAND, GEO_LIGHTBALL, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PLANETFLOOR, GEO_PORTRAIT, GEO_RHAND, GEO_RIGHT, GEO_RUBBLE, GEO_STAMINABAR, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void SceneStart::MouseClickFunction (double dt) private
Definition at line 367 of file SceneStart.cpp.
References GlobalVariables::b_LockSwing, GlobalVariables::b_LockSwingDebounce, Explorer::instance(), Application::IsKeyPressed(), GlobalVariables::RotateX, Explorer::stamina, and Scene::Variables.
Referenced by Update().
void SceneStart::MouseScrollToolSlot () private
Definition at line 237 of file SceneStart.cpp.
References Explorer::i_SlotIndex, Explorer::instance(), and Application::mouse_scroll.
Referenced by Update().
bool SceneStart::proximitycheck (float smallx, float largex, float smallz, float largez) private
Definition at line 399 of file SceneStart.cpp.
References camera, Camera::position, Vector3::x, and Vector3::z.
Referenced by ChangeFirstCutScene().
void SceneStart::Render () virtual
Implements Scene.
Definition at line 608 of file SceneStart.cpp.
References camera, displayInteract, FPS, GEO_AXES, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_STAMINABAR, GEO_TEXT, Explorer::instance(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, Explorer::PlayerLife, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderMesh(), RenderModelOnScreen(), RenderMouseScrollToolSlot(), RenderSceneStart(), RenderTextOnScreen(), RenderToolIcon(), Light::spotDirection, Camera::target, ToolSelectionMouseScroll(), MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneStart::RenderDownWall (int xPosLarge, int xPosSmall, int zPos) private
void SceneStart::RenderFloor () private
Definition at line 69 of file SceneStartRenders.cpp.
References GEO_DEADBODY, GEO_PLANETFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderSceneStart().
void SceneStart::RenderGhost () private
void SceneStart::RenderLeftWall (int zPosLarge, int zPosSmall, int xPos) private
void SceneStart::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 467 of file SceneStart.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderFloor(), RenderModelOnScreen(), RenderSceneStart(), and RenderSkyBox().
void SceneStart::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 587 of file SceneStart.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render(), RenderMouseScrollToolSlot(), RenderToolIcon(), and ToolSelectionMouseScroll().
void SceneStart::RenderMouseScrollToolSlot () private
Definition at line 260 of file SceneStart.cpp.
References GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, Explorer::instance(), meshList, and RenderModelOnScreen().
Referenced by Render().
void SceneStart::RenderRightWall (int zPosLarge, int zPosSmall, int xPos) private
void SceneStart::RenderSceneStart () private
Definition at line 95 of file SceneStartRenders.cpp.
References GEO_FACILITYOUT, GEO_FACILITYOUTWALL, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderFloor(), RenderMesh(), RenderSkyBox(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneStart::RenderSkyBox () private
Definition at line 8 of file SceneStartRenders.cpp.
References GlobalVariables::f_Worldspin, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and Scene::Variables.
Referenced by RenderSceneStart().
void SceneStart::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 511 of file SceneStart.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneStart::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 541 of file SceneStart.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SceneStart::RenderToolIcon () private
Definition at line 311 of file SceneStart.cpp.
References ToolUI::BaseballBat, GEO_BATICON, GEO_HANDICON, GEO_PICKAXEICON, GEO_SWORDICON, ToolUI::Hand, Explorer::instance(), meshList, ToolUI::Pickaxe, RenderModelOnScreen(), and ToolUI::Sword.
Referenced by Render().
void SceneStart::RenderUpWall (int xPosLarge, int xPosSmall, int zPos) private
void SceneStart::Reset () virtual
Definition at line 205 of file SceneStart.cpp.
void SceneStart::ToolSelectionMouseScroll () private
Definition at line 278 of file SceneStart.cpp.
References ToolUI::BaseballBat, GEO_BAT, GEO_LHAND, GEO_PICKAXE, GEO_RHAND, GEO_SWORD, ToolUI::Hand, Explorer::instance(), meshList, modelStack, ToolUI::Pickaxe, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), GlobalVariables::RotateX, ToolUI::Sword, and Scene::Variables.
Referenced by Render().
void SceneStart::ToolsUI () private
Definition at line 232 of file SceneStart.cpp.
Referenced by Update().
void SceneStart::Update (double dt) virtual
Implements Scene.
Definition at line 430 of file SceneStart.cpp.
References camera, ChangeFirstCutScene(), Explorer::checkDead(), checkPlayerPosMisc(), Collision(), GlobalVariables::f_Worldspin, FPS, Explorer::instance(), Application::IsKeyPressed(), light, MouseClickFunction(), MouseScrollToolSlot(), Light::position, Camera::position, rotate, Position::Set(), Vector3::Set(), Light::spotDirection, Switches, SwitchLightPuzzle::SwitchPuzzleOne(), Camera::target, ToolsUI(), Camera3::Update(), Scene::Variables, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Animation SceneStart::anima private
Definition at line 170 of file SceneStart.h.
Camera3 SceneStart::camera
Definition at line 119 of file SceneStart.h.
Referenced by checkPlayerPosMisc(), Collision(), Init(), proximitycheck(), Render(), and Update().
bool SceneStart::displayInteract private
Definition at line 186 of file SceneStart.h.
Referenced by ChangeFirstCutScene(), and Render().
Vector3 SceneStart::end private
Definition at line 180 of file SceneStart.h.
float SceneStart::FPS private
Definition at line 185 of file SceneStart.h.
Referenced by Render(), and Update().
Light SceneStart::light[1] private
Definition at line 174 of file SceneStart.h.
Referenced by Init(), Render(), and Update().
unsigned SceneStart::m_parameters[U_TOTAL] private
Definition at line 168 of file SceneStart.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SceneStart::m_programID private
Definition at line 167 of file SceneStart.h.
Referenced by Exit(), and Init().
unsigned SceneStart::m_vertexArrayID private
Definition at line 164 of file SceneStart.h.
Referenced by Exit(), and Init().
Mesh* SceneStart::meshList[NUM_GEOMETRY] private
Definition at line 165 of file SceneStart.h.
Referenced by Init(), Render(), RenderFloor(), RenderMouseScrollToolSlot(), RenderSceneStart(), RenderSkyBox(), RenderToolIcon(), and ToolSelectionMouseScroll().
misc SceneStart::Misc private
Definition at line 182 of file SceneStart.h.
Referenced by checkPlayerPosMisc().
float SceneStart::mobTimeCount private
Definition at line 187 of file SceneStart.h.
MS SceneStart::modelStack private
Definition at line 172 of file SceneStart.h.
Referenced by Render(), RenderFloor(), RenderMesh(), RenderModelOnScreen(), RenderSceneStart(), RenderSkyBox(), RenderText(), RenderTextOnScreen(), and ToolSelectionMouseScroll().
MS SceneStart::projectionStack private
Definition at line 172 of file SceneStart.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
Vector3 SceneStart::start private
Definition at line 179 of file SceneStart.h.
SwitchLightPuzzle SceneStart::Switches private
Definition at line 183 of file SceneStart.h.
Referenced by Update().
MS SceneStart::viewStack private
Definition at line 172 of file SceneStart.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneStart.h
ComGraphics/Source/SceneStart.cpp
ComGraphics/Source/SceneStartRenders.cpp