My Application: SceneLevelOneB Class Reference
SceneLevelOneB Class Reference
#include <SceneLevelOneB.h>
Public Member Functions
SceneLevelOneB ()
~SceneLevelOneB ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void ResetSameScene ()
virtual void ResetAll ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_RUBBLE,
GEO_PORTRAIT, GEO_PLANETFLOOR, GEO_FACILITYFLOOR, GEO_FACILITYOUT,
GEO_FACILITYOUTWALL, GEO_FACILITYWALLS, GEO_FACILITYCEILINGS, GEO_LHAND,
GEO_RHAND, GEO_TOOLUIONE, GEO_TOOLUITWO, GEO_TOOLUITHREE,
GEO_TOOLUIFOUR, GEO_HANDICON, GEO_PICKAXE, GEO_PICKAXEICON,
GEO_BAT, GEO_BATICON, GEO_SWORD, GEO_SWORDICON,
GEO_GHOST1, GEO_BOSS1, GEO_CRYSTAL1, GEO_CRYSTAL2,
GEO_SPAWNPOINT, GEO_SUITCASE, GEO_SLIDEDOORTOP, GEO_SLIDEDOORBTM,
GEO_HEALTHBAR, GEO_STAMINABAR, GEO_LIGHTGREEN, GEO_LIGHTRED,
GEO_PUZZLELEVER, GEO_DEADCOLOR, GEO_DEADBLACKSCREEN, GEO_ELEVATOR,
GEO_HEALTHICON, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderScene ()
void RenderFloorCeiling ()
void RenderDownWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber)
void RenderUpWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber)
void RenderRightWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber)
void RenderLeftWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber)
void RenderGhost (float xpos, float zpos)
void RenderBoss (float xpos, float zpos)
void RenderDoor ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void checkPlayerPosMisc ()
void Collision (float smallx, float largex, float smallz, float largez)
bool proximitycheck (float smallx, float largex, float smallz, float largez)
void checkDoor1 ()
void checkDoor2 ()
void checkDoor3 ()
void checkDoor4 ()
void EnvironmentAnimation (double dt)
void ElevatorCheck ()
void attackCheck ()
void MobsSpawn ()
void AnimationCheck (double dt)
void PuzzleOneSwitchCheck (double dt)
void SwitchCollisionChecker ()
void RenderPuzzle ()
void LogicAnimationSwitches (double dt)
void ToolsUI ()
void MouseScrollToolSlot ()
void RenderMouseScrollToolSlot ()
void ToolSelectionMouseScroll ()
void RenderToolIcon ()
void MouseClickFunction (double dt)
void RenderPickUpPickTools ()
void RenderPlayerDiesInteraction ()
void UpdatePlayerDiesInteraction (double dt)
void ContinueGameOrNot ()
void PickUpSuitcaseInteraction ()
void RenderPickUpSuitcaseText ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
GlobalVariables Variables
float FPS
bool displayInteract1
bool displayInteract2
bool displayInteract3
bool activateDoor1
bool activateDoor2
bool activateDoor3_1
bool activateDoor3_2
bool activateDoor4
bool elevatorCheck
float CollXLarge [43]
float CollXSmall [43]
float CollZLarge [43]
float CollZSmall [43]
MobGhost PuzzleGhost1
MobGhost PuzzleGhost2
MobGhost ElevatorGhost1
MobGhost ElevatorGhost2
MobGhost ElevatorGhost3
MobBossOne BossOne
bool CrosshairHit = false
Detailed Description
Definition at line 14 of file SceneLevelOneB.h.
Member Enumeration Documentation
enum SceneLevelOneB::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_RUBBLE
GEO_PORTRAIT
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_LHAND
GEO_RHAND
GEO_TOOLUIONE
GEO_TOOLUITWO
GEO_TOOLUITHREE
GEO_TOOLUIFOUR
GEO_HANDICON
GEO_PICKAXE
GEO_PICKAXEICON
GEO_BAT
GEO_BATICON
GEO_SWORD
GEO_SWORDICON
GEO_GHOST1
GEO_BOSS1
GEO_CRYSTAL1
GEO_CRYSTAL2
GEO_SPAWNPOINT
GEO_SUITCASE
GEO_SLIDEDOORTOP
GEO_SLIDEDOORBTM
GEO_HEALTHBAR
GEO_STAMINABAR
GEO_LIGHTGREEN
GEO_LIGHTRED
GEO_PUZZLELEVER
GEO_DEADCOLOR
GEO_DEADBLACKSCREEN
GEO_ELEVATOR
GEO_HEALTHICON
NUM_GEOMETRY
Definition at line 16 of file SceneLevelOneB.h.
enum SceneLevelOneB::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 88 of file SceneLevelOneB.h.
Constructor & Destructor Documentation
SceneLevelOneB::SceneLevelOneB ()
Definition at line 16 of file SceneLevelOneB.cpp.
SceneLevelOneB::~SceneLevelOneB ()
Definition at line 20 of file SceneLevelOneB.cpp.
Member Function Documentation
void SceneLevelOneB::AnimationCheck (double dt) private
Definition at line 478 of file SceneLevelOneBRenders.cpp.
References activateDoor1, activateDoor2, activateDoor3_1, activateDoor3_2, activateDoor4, anima, BossOne, Animation::CloseSlideDoor_Boss(), Animation::OpenSlideDoor1(), Animation::OpenSlideDoor2(), Animation::OpenSlideDoor3(), Animation::OpenSlideDoor4(), Animation::OpenSlideDoor_Boss(), and HostileMob::Spawn.
Referenced by Update().
void SceneLevelOneB::attackCheck () private
Definition at line 435 of file SceneLevelOneBRenders.cpp.
References BossOne, camera, CrosshairHit, misc::hitting(), Explorer::instance(), Application::IsKeyPressed(), Scene::Misc, HostileMob::MobPosX, HostileMob::MobPosZ, Camera::position, PuzzleGhost1, PuzzleGhost2, MobGhost::TakeDamage(), MobBossOne::TakeDamage(), Camera3::view, Vector3::x, and Vector3::z.
Referenced by MouseClickFunction().
void SceneLevelOneB::checkDoor1 () private
Definition at line 254 of file SceneLevelOneBRenders.cpp.
References activateDoor1, anima, Collision(), displayInteract1, Application::IsKeyPressed(), proximitycheck(), and Animation::toSlideDoorBtm.
Referenced by Update().
void SceneLevelOneB::checkDoor2 () private
Definition at line 282 of file SceneLevelOneBRenders.cpp.
References activateDoor2, anima, SwitchLightPuzzle::b_PuzzleOne, Collision(), Scene::Switches, and Animation::toSlideDoorBtm2.
Referenced by Update().
void SceneLevelOneB::checkDoor3 () private
Definition at line 297 of file SceneLevelOneBRenders.cpp.
References activateDoor3_1, activateDoor3_2, anima, BossOne, Collision(), displayInteract2, HostileMob::health, Application::IsKeyPressed(), proximitycheck(), HostileMob::Spawn, Animation::toSlideDoorBtm_Boss, and Animation::toSlideDoorTop_Boss.
Referenced by Update().
void SceneLevelOneB::checkDoor4 () private
Definition at line 344 of file SceneLevelOneBRenders.cpp.
References activateDoor4, anima, Collision(), displayInteract3, Application::IsKeyPressed(), proximitycheck(), and Animation::toSlideDoorBtm4.
Referenced by Update().
void SceneLevelOneB::checkPlayerPosMisc () private
Definition at line 510 of file SceneLevelOneBRenders.cpp.
References camera, misc::camX, misc::camY, misc::camZ, Scene::Misc, Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneLevelOneB::Collision (float smallx, float largex, float smallz, float largez) private
Definition at line 292 of file SceneLevelOneB.cpp.
References camera, Math::DegreeToRadian(), Camera::position, Camera3::rotationX, Camera3::rotationY, Camera::target, Vector3::x, and Vector3::z.
Referenced by checkDoor1(), checkDoor2(), checkDoor3(), checkDoor4(), RenderDoor(), SwitchCollisionChecker(), and Update().
void SceneLevelOneB::ContinueGameOrNot () private
Definition at line 675 of file SceneLevelOneB.cpp.
References camera, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Application::IsKeyPressed(), Application::OpenGame(), Explorer::PlayerLife, Camera::position, Explorer::SavePoint, Variables, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneLevelOneB::ElevatorCheck () private
Definition at line 38 of file SceneLevelOneBRenders.cpp.
References elevatorCheck, Application::IsKeyPressed(), Scene::Misc, Application::SceneLevel2(), and misc::WithinArea().
Referenced by Update().
void SceneLevelOneB::EnvironmentAnimation (double dt) private
Definition at line 430 of file SceneLevelOneBRenders.cpp.
References GlobalVariables::f_SuitcaseRotateY, and Variables.
Referenced by Update().
void SceneLevelOneB::Exit () virtual
Implements Scene.
Definition at line 1058 of file SceneLevelOneB.cpp.
References m_programID, and m_vertexArrayID.
void SceneLevelOneB::Init () virtual
Implements Scene.
Definition at line 24 of file SceneLevelOneB.cpp.
References BossOne, camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BAT, GEO_BATICON, GEO_BOSS1, GEO_BOTTOM, GEO_CRYSTAL1, GEO_CRYSTAL2, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_ELEVATOR, GEO_FACILITYCEILINGS, GEO_FACILITYFLOOR, GEO_FACILITYWALLS, GEO_FRONT, GEO_GHOST1, GEO_HANDICON, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_LEFT, GEO_LHAND, GEO_LIGHTBALL, GEO_LIGHTGREEN, GEO_LIGHTRED, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PORTRAIT, GEO_PUZZLELEVER, GEO_RHAND, GEO_RIGHT, GEO_RUBBLE, GEO_SLIDEDOORBTM, GEO_SLIDEDOORTOP, GEO_SPAWNPOINT, GEO_STAMINABAR, GEO_SUITCASE, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, PuzzleGhost1, PuzzleGhost2, Position::Set(), Color::Set(), Vector3::Set(), MobBossOne::setSpawnBossOne(), MobGhost::setSpawnGhost(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void SceneLevelOneB::LogicAnimationSwitches (double dt) private
Definition at line 602 of file SceneLevelOneB.cpp.
References GlobalVariables::b_SwitchAnimate, GlobalVariables::f_SwitchRotateOne, GlobalVariables::f_SwitchRotateThree, GlobalVariables::f_SwitchRotateTwo, and Variables.
Referenced by Update().
void SceneLevelOneB::MobsSpawn () private
Definition at line 457 of file SceneLevelOneBRenders.cpp.
References BossOne, HostileMob::health, proximitycheck(), PuzzleGhost1, PuzzleGhost2, and HostileMob::Spawn.
Referenced by Update().
void SceneLevelOneB::MouseClickFunction (double dt) private
Definition at line 465 of file SceneLevelOneB.cpp.
References attackCheck(), GlobalVariables::b_LockSwing, GlobalVariables::b_LockSwingDebounce, CrosshairHit, Explorer::instance(), Application::IsKeyPressed(), GlobalVariables::RotateX, Explorer::stamina, and Variables.
Referenced by Update().
void SceneLevelOneB::MouseScrollToolSlot () private
Definition at line 442 of file SceneLevelOneB.cpp.
References Explorer::i_SlotIndex, Explorer::instance(), and Application::mouse_scroll.
Referenced by Update().
void SceneLevelOneB::PickUpSuitcaseInteraction () private
Definition at line 712 of file SceneLevelOneB.cpp.
References Explorer::b_pickUpSuitCase, camera, ToolUI::Hand, Explorer::i_SuitcaseCount, Explorer::instance(), Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
bool SceneLevelOneB::proximitycheck (float smallx, float largex, float smallz, float largez) private
Definition at line 306 of file SceneLevelOneB.cpp.
References camera, Camera::position, Vector3::x, and Vector3::z.
Referenced by checkDoor1(), checkDoor3(), checkDoor4(), and MobsSpawn().
void SceneLevelOneB::PuzzleOneSwitchCheck (double dt) private
Definition at line 507 of file SceneLevelOneB.cpp.
References SwitchLightPuzzle::b_PuzzleOne, GlobalVariables::b_SwitchAnimate, GlobalVariables::f_SwitchDebounce, Application::IsKeyPressed(), Scene::Misc, Scene::Switches, Variables, and misc::WithinArea().
Referenced by Update().
void SceneLevelOneB::Render () virtual
Implements Scene.
Definition at line 963 of file SceneLevelOneB.cpp.
References BossOne, camera, CrosshairHit, displayInteract1, displayInteract2, displayInteract3, elevatorCheck, FPS, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_STAMINABAR, GEO_TEXT, Explorer::instance(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, HostileMob::MobPosX, HostileMob::MobPosZ, modelStack, Explorer::PlayerLife, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), PuzzleGhost1, PuzzleGhost2, RenderBoss(), RenderDoor(), RenderGhost(), RenderModelOnScreen(), RenderMouseScrollToolSlot(), RenderPickUpPickTools(), RenderPickUpSuitcaseText(), RenderPlayerDiesInteraction(), RenderScene(), RenderTextOnScreen(), RenderToolIcon(), HostileMob::Spawn, Light::spotDirection, Camera::target, ToolSelectionMouseScroll(), MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneLevelOneB::RenderBoss (float xpos, float zpos) private
Definition at line 393 of file SceneLevelOneBRenders.cpp.
References MobBossOne::AttackAnimation, BossOne, camera, MobBossOne::CrystalAnim, GEO_BOSS1, GEO_CRYSTAL1, GEO_CRYSTAL2, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneLevelOneB::RenderDoor () private
Definition at line 166 of file SceneLevelOneBRenders.cpp.
References anima, Collision(), Animation::DoorSlideBtm, Animation::DoorSlideBtm_2, Animation::DoorSlideBtm_3, Animation::DoorSlideBtm_4, Animation::DoorSlideBtm_Boss, Animation::DoorSlideTop, Animation::DoorSlideTop_2, Animation::DoorSlideTop_3, Animation::DoorSlideTop_4, Animation::DoorSlideTop_Boss, GEO_SLIDEDOORBTM, GEO_SLIDEDOORTOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneLevelOneB::RenderDownWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber) private
Definition at line 236 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneB::RenderFloorCeiling () private
Definition at line 7 of file SceneLevelOneBRenders.cpp.
References GEO_FACILITYCEILINGS, GEO_FACILITYFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneB::RenderGhost (float xpos, float zpos) private
Definition at line 374 of file SceneLevelOneBRenders.cpp.
References camera, GEO_GHOST1, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, MS::Translate(), Camera3::view, Vector3::x, and Vector3::z.
Referenced by Render().
void SceneLevelOneB::RenderLeftWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber) private
Definition at line 409 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneB::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 822 of file SceneLevelOneB.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderBoss(), RenderDoor(), RenderDownWall(), RenderFloorCeiling(), RenderGhost(), RenderLeftWall(), RenderModelOnScreen(), RenderPickUpPickTools(), RenderPuzzle(), RenderRightWall(), RenderScene(), and RenderUpWall().
void SceneLevelOneB::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 942 of file SceneLevelOneB.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderToolIcon(), and ToolSelectionMouseScroll().
void SceneLevelOneB::RenderMouseScrollToolSlot () private
Definition at line 332 of file SceneLevelOneB.cpp.
References GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, Explorer::instance(), meshList, and RenderModelOnScreen().
Referenced by Render().
void SceneLevelOneB::RenderPickUpPickTools () private
Definition at line 632 of file SceneLevelOneBRenders.cpp.
References MobBossOne::BossDies, BossOne, GlobalVariables::f_rotatingTool, GEO_BAT, GEO_SWORD, Explorer::instance(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and Variables.
Referenced by Render().
void SceneLevelOneB::RenderPickUpSuitcaseText () private
Definition at line 657 of file SceneLevelOneBRenders.cpp.
References camera, GEO_TEXT, ToolUI::Hand, Explorer::instance(), meshList, Camera::position, RenderTextOnScreen(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneLevelOneB::RenderPlayerDiesInteraction () private
Definition at line 598 of file SceneLevelOneBRenders.cpp.
References GlobalVariables::f_redScreenTimer, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_TEXT, Explorer::instance(), meshList, RenderModelOnScreen(), RenderTextOnScreen(), and Variables.
Referenced by Render().
void SceneLevelOneB::RenderPuzzle () private
Definition at line 518 of file SceneLevelOneBRenders.cpp.
References SwitchLightPuzzle::b_PuzzleOne, GlobalVariables::f_SwitchRotateOne, GlobalVariables::f_SwitchRotateThree, GlobalVariables::f_SwitchRotateTwo, GEO_LIGHTGREEN, GEO_LIGHTRED, GEO_PUZZLELEVER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Scene::Switches, MS::Translate(), and Variables.
Referenced by RenderScene().
void SceneLevelOneB::RenderRightWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber) private
Definition at line 352 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneB::RenderScene () private
Definition at line 55 of file SceneLevelOneBRenders.cpp.
References GlobalVariables::f_SuitcaseRotateY, GEO_ELEVATOR, GEO_SPAWNPOINT, GEO_SUITCASE, Explorer::instance(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderDownWall(), RenderFloorCeiling(), RenderLeftWall(), RenderMesh(), RenderPuzzle(), RenderRightWall(), RenderUpWall(), MS::Rotate(), MS::Scale(), MS::Translate(), and Variables.
Referenced by Render().
void SceneLevelOneB::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 866 of file SceneLevelOneB.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneLevelOneB::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 896 of file SceneLevelOneB.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderPickUpSuitcaseText(), and RenderPlayerDiesInteraction().
void SceneLevelOneB::RenderToolIcon () private
Definition at line 383 of file SceneLevelOneB.cpp.
References ToolUI::BaseballBat, GEO_BATICON, GEO_HANDICON, GEO_PICKAXEICON, GEO_SWORDICON, ToolUI::Hand, Explorer::instance(), meshList, ToolUI::Pickaxe, RenderModelOnScreen(), and ToolUI::Sword.
Referenced by Render().
void SceneLevelOneB::RenderUpWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber) private
Definition at line 295 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneB::ResetAll () virtual
Definition at line 276 of file SceneLevelOneB.cpp.
References Explorer::checkSavePoint, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Explorer::PlayerLife, Explorer::SavePoint, and Variables.
void SceneLevelOneB::ResetSameScene () virtual
Definition at line 233 of file SceneLevelOneB.cpp.
References activateDoor1, activateDoor2, activateDoor3_1, activateDoor3_2, activateDoor4, anima, BossOne, Explorer::checkSavePoint, Animation::ClosingDoorBtm5, Animation::ClosingDoorBtm_Boss, Animation::ClosingDoorTop5, Animation::ClosingDoorTop_Boss, Animation::DoorSlideBtm_5, Animation::DoorSlideBtm_Boss, Animation::DoorSlideTop_5, Animation::DoorSlideTop_Boss, GlobalVariables::f_redScreenTimer, HostileMob::health, Explorer::hp, Explorer::instance(), Explorer::isDead, PuzzleGhost1, PuzzleGhost2, Explorer::SavePoint, MobBossOne::setSpawnBossOne(), MobGhost::setSpawnGhost(), HostileMob::Spawn, Animation::toSlideDoorBtm_Boss, Animation::toSlideDoorTop_Boss, and Variables.
void SceneLevelOneB::SwitchCollisionChecker () private
Definition at line 502 of file SceneLevelOneB.cpp.
References Collision().
Referenced by Update().
void SceneLevelOneB::ToolSelectionMouseScroll () private
Definition at line 350 of file SceneLevelOneB.cpp.
References ToolUI::BaseballBat, GEO_BAT, GEO_LHAND, GEO_PICKAXE, GEO_RHAND, GEO_SWORD, ToolUI::Hand, Explorer::instance(), meshList, modelStack, ToolUI::Pickaxe, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), GlobalVariables::RotateX, ToolUI::Sword, and Variables.
Referenced by Render().
void SceneLevelOneB::ToolsUI () private
Definition at line 317 of file SceneLevelOneB.cpp.
References Explorer::b_PickUpTool, ToolUI::BaseballBat, camera, Explorer::InsertToolSlot(), Explorer::instance(), Camera::position, ToolUI::Sword, Vector3::x, and Vector3::z.
Referenced by Update().
void SceneLevelOneB::Update (double dt) virtual
Implements Scene.
Definition at line 724 of file SceneLevelOneB.cpp.
References activateDoor1, anima, AnimationCheck(), BossOne, camera, Explorer::checkDead(), checkDoor1(), checkDoor2(), checkDoor3(), checkDoor4(), HostileMob::checkPlayerPos(), checkPlayerPosMisc(), Collision(), CollXLarge, CollXSmall, CollZLarge, CollZSmall, ContinueGameOrNot(), ElevatorCheck(), EnvironmentAnimation(), GlobalVariables::f_rotatingTool, FPS, Explorer::instance(), Application::IsKeyPressed(), light, LogicAnimationSwitches(), HostileMob::MobCollision(), HostileMob::MobPosX, HostileMob::MobPosZ, MobsSpawn(), MouseClickFunction(), MouseScrollToolSlot(), MobGhost::move(), MobBossOne::move(), Application::OpenGame(), Animation::OpenSlideDoor1(), PickUpSuitcaseInteraction(), Light::position, Camera::position, PuzzleGhost1, PuzzleGhost2, PuzzleOneSwitchCheck(), Position::Set(), Vector3::Set(), HostileMob::Spawn, Light::spotDirection, SwitchCollisionChecker(), Scene::Switches, SwitchLightPuzzle::SwitchPuzzleOne(), Camera::target, ToolsUI(), Camera3::Update(), UpdatePlayerDiesInteraction(), Variables, Vector3::x, Vector3::y, and Vector3::z.
void SceneLevelOneB::UpdatePlayerDiesInteraction (double dt) private
Definition at line 665 of file SceneLevelOneB.cpp.
References GlobalVariables::f_redScreenTimer, Explorer::instance(), light, m_parameters, Light::power, U_LIGHT0_POWER, and Variables.
Referenced by Update().
Field Documentation
bool SceneLevelOneB::activateDoor1 private
Definition at line 215 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), checkDoor1(), ResetSameScene(), and Update().
bool SceneLevelOneB::activateDoor2 private
Definition at line 216 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), checkDoor2(), and ResetSameScene().
bool SceneLevelOneB::activateDoor3_1 private
Definition at line 217 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), checkDoor3(), and ResetSameScene().
bool SceneLevelOneB::activateDoor3_2 private
Definition at line 218 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), checkDoor3(), and ResetSameScene().
bool SceneLevelOneB::activateDoor4 private
Definition at line 219 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), checkDoor4(), and ResetSameScene().
Animation SceneLevelOneB::anima private
Definition at line 201 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), checkDoor1(), checkDoor2(), checkDoor3(), checkDoor4(), RenderDoor(), ResetSameScene(), and Update().
MobBossOne SceneLevelOneB::BossOne private
Definition at line 232 of file SceneLevelOneB.h.
Referenced by AnimationCheck(), attackCheck(), checkDoor3(), Init(), MobsSpawn(), Render(), RenderBoss(), RenderPickUpPickTools(), ResetSameScene(), and Update().
Camera3 SceneLevelOneB::camera
Definition at line 129 of file SceneLevelOneB.h.
Referenced by attackCheck(), checkPlayerPosMisc(), Collision(), ContinueGameOrNot(), Init(), PickUpSuitcaseInteraction(), proximitycheck(), Render(), RenderBoss(), RenderGhost(), RenderPickUpSuitcaseText(), ToolsUI(), and Update().
float SceneLevelOneB::CollXLarge[43] private
Definition at line 222 of file SceneLevelOneB.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelOneB::CollXSmall[43] private
Definition at line 223 of file SceneLevelOneB.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelOneB::CollZLarge[43] private
Definition at line 224 of file SceneLevelOneB.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelOneB::CollZSmall[43] private
Definition at line 225 of file SceneLevelOneB.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
bool SceneLevelOneB::CrosshairHit = false private
Definition at line 233 of file SceneLevelOneB.h.
Referenced by attackCheck(), MouseClickFunction(), and Render().
bool SceneLevelOneB::displayInteract1 private
Definition at line 212 of file SceneLevelOneB.h.
Referenced by checkDoor1(), and Render().
bool SceneLevelOneB::displayInteract2 private
Definition at line 213 of file SceneLevelOneB.h.
Referenced by checkDoor3(), and Render().
bool SceneLevelOneB::displayInteract3 private
Definition at line 214 of file SceneLevelOneB.h.
Referenced by checkDoor4(), and Render().
bool SceneLevelOneB::elevatorCheck private
Definition at line 220 of file SceneLevelOneB.h.
Referenced by ElevatorCheck(), and Render().
MobGhost SceneLevelOneB::ElevatorGhost1 private
Definition at line 229 of file SceneLevelOneB.h.
MobGhost SceneLevelOneB::ElevatorGhost2 private
Definition at line 230 of file SceneLevelOneB.h.
MobGhost SceneLevelOneB::ElevatorGhost3 private
Definition at line 231 of file SceneLevelOneB.h.
Vector3 SceneLevelOneB::end private
Definition at line 208 of file SceneLevelOneB.h.
float SceneLevelOneB::FPS private
Definition at line 211 of file SceneLevelOneB.h.
Referenced by Render(), and Update().
Light SceneLevelOneB::light[1] private
Definition at line 205 of file SceneLevelOneB.h.
Referenced by Init(), Render(), Update(), and UpdatePlayerDiesInteraction().
unsigned SceneLevelOneB::m_parameters[U_TOTAL] private
Definition at line 199 of file SceneLevelOneB.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and UpdatePlayerDiesInteraction().
unsigned SceneLevelOneB::m_programID private
Definition at line 198 of file SceneLevelOneB.h.
Referenced by Exit(), and Init().
unsigned SceneLevelOneB::m_vertexArrayID private
Definition at line 195 of file SceneLevelOneB.h.
Referenced by Exit(), and Init().
Mesh* SceneLevelOneB::meshList[NUM_GEOMETRY] private
Definition at line 196 of file SceneLevelOneB.h.
Referenced by Init(), Render(), RenderBoss(), RenderDoor(), RenderDownWall(), RenderFloorCeiling(), RenderGhost(), RenderLeftWall(), RenderMouseScrollToolSlot(), RenderPickUpPickTools(), RenderPickUpSuitcaseText(), RenderPlayerDiesInteraction(), RenderPuzzle(), RenderRightWall(), RenderScene(), RenderToolIcon(), RenderUpWall(), and ToolSelectionMouseScroll().
MS SceneLevelOneB::modelStack private
Definition at line 203 of file SceneLevelOneB.h.
Referenced by Render(), RenderBoss(), RenderDoor(), RenderDownWall(), RenderFloorCeiling(), RenderGhost(), RenderLeftWall(), RenderMesh(), RenderModelOnScreen(), RenderPickUpPickTools(), RenderPuzzle(), RenderRightWall(), RenderScene(), RenderText(), RenderTextOnScreen(), RenderUpWall(), and ToolSelectionMouseScroll().
MS SceneLevelOneB::projectionStack private
Definition at line 203 of file SceneLevelOneB.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
MobGhost SceneLevelOneB::PuzzleGhost1 private
Definition at line 227 of file SceneLevelOneB.h.
Referenced by attackCheck(), Init(), MobsSpawn(), Render(), ResetSameScene(), and Update().
MobGhost SceneLevelOneB::PuzzleGhost2 private
Definition at line 228 of file SceneLevelOneB.h.
Referenced by attackCheck(), Init(), MobsSpawn(), Render(), ResetSameScene(), and Update().
Vector3 SceneLevelOneB::start private
Definition at line 207 of file SceneLevelOneB.h.
GlobalVariables SceneLevelOneB::Variables private
Definition at line 209 of file SceneLevelOneB.h.
Referenced by ContinueGameOrNot(), EnvironmentAnimation(), LogicAnimationSwitches(), MouseClickFunction(), PuzzleOneSwitchCheck(), RenderPickUpPickTools(), RenderPlayerDiesInteraction(), RenderPuzzle(), RenderScene(), ResetAll(), ResetSameScene(), ToolSelectionMouseScroll(), Update(), and UpdatePlayerDiesInteraction().
MS SceneLevelOneB::viewStack private
Definition at line 203 of file SceneLevelOneB.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneLevelOneB.h
ComGraphics/Source/MapRender.cpp
ComGraphics/Source/SceneLevelOneB.cpp
ComGraphics/Source/SceneLevelOneBRenders.cpp