My Application: Camera3 Class Reference
Camera3 Class Reference
#include <Camera3.h>
Public Member Functions
Camera3 ()
~Camera3 ()
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
virtual void HumanControl ()
virtual void Update (double dt)
virtual void Reset ()
void CameraRotation (double dt, float CAMERASPEED)
Public Member Functions inherited from Camera
Camera ()
~Camera ()
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
Vector3 view
Vector3 right
float rotationX
float rotationY
float MarginofError = 5.f
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Detailed Description
Definition at line 6 of file Camera3.h.
Constructor & Destructor Documentation
Camera3::Camera3 ()
Definition at line 9 of file Camera3.cpp.
Camera3::~Camera3 ()
Definition at line 13 of file Camera3.cpp.
Member Function Documentation
void Camera3::CameraRotation (double dt, float CAMERASPEED)
Definition at line 32 of file Camera3.cpp.
References Math::DegreeToRadian(), m_window, Camera::position, rotationX, rotationY, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void Camera3::HumanControl () virtual
Definition at line 67 of file Camera3.cpp.
References Math::DegreeToRadian(), Explorer::instance(), Explorer::isDead, Application::IsKeyPressed(), Camera::position, right, rotationY, Explorer::stamina, Camera::target, view, Vector3::x, and Vector3::z.
Referenced by Update().
void Camera3::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Reimplemented from Camera.
Definition at line 17 of file Camera3.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, m_window, Vector3::Normalize(), Vector3::Normalized(), Camera::position, right, rotationX, rotationY, Camera::target, view, and Vector3::y.
Referenced by CutSceneOne::Init(), SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneLevelTwo::Init(), SceneStart::Init(), SceneLevelOneA::Init(), SceneLevelOneB::Init(), and SceneEnd::Init().
void Camera3::Reset () virtual
Reimplemented from Camera.
Definition at line 108 of file Camera3.cpp.
Referenced by Update().
void Camera3::Update (double dt) virtual
Reimplemented from Camera.
Definition at line 112 of file Camera3.cpp.
References CameraRotation(), Explorer::checkDead(), Vector3::Cross(), defaultUp, Math::DegreeToRadian(), HumanControl(), Explorer::instance(), Vector3::Normalize(), Vector3::Normalized(), Camera::position, regenDelay, Reset(), right, rotationX, rotationY, Explorer::stamina, Camera::target, Camera::up, view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SceneOpening::Update(), SceneLevelTwo::Update(), SceneLevelOneA::Update(), SceneStart::Update(), SceneLevelOneB::Update(), and SceneEnd::Update().
Field Documentation
Vector3 Camera3::defaultPosition
Definition at line 13 of file Camera3.h.
Referenced by Init().
Vector3 Camera3::defaultTarget
Definition at line 14 of file Camera3.h.
Referenced by Init().
Vector3 Camera3::defaultUp
Definition at line 15 of file Camera3.h.
Referenced by Init(), and Update().
float Camera3::MarginofError = 5.f
Definition at line 29 of file Camera3.h.
Vector3 Camera3::right
Definition at line 17 of file Camera3.h.
Referenced by HumanControl(), Init(), and Update().
float Camera3::rotationX
Definition at line 26 of file Camera3.h.
Referenced by CameraRotation(), SceneLevelTwo::Collision(), SceneStart::Collision(), SceneLevelOneB::Collision(), SceneEnd::Collision(), SceneLevelOneA::Collision(), Init(), SceneLevelTwo::SpecialCollision(), and Update().
float Camera3::rotationY
Definition at line 27 of file Camera3.h.
Referenced by CameraRotation(), SceneLevelTwo::Collision(), SceneStart::Collision(), SceneLevelOneB::Collision(), SceneEnd::Collision(), SceneLevelOneA::Collision(), HumanControl(), Init(), SceneLevelTwo::SpecialCollision(), and Update().
Vector3 Camera3::view
Definition at line 16 of file Camera3.h.
Referenced by SceneLevelOneB::attackCheck(), SceneLevelOneA::AttackCheck(), SceneEnd::checkAttack(), HumanControl(), Init(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), and Update().
The documentation for this class was generated from the following files:
ComGraphics/Source/Camera3.h
ComGraphics/Source/Camera3.cpp