My Application: MobBossOne Class Reference
MobBossOne Class Reference
#include <MobBossOne.h>
Public Member Functions
MobBossOne ()
~MobBossOne ()
void setSpawnBossOne (float xpos, float zpos)
void move (double dt, int movespeed)
void attack (float damage)
void knockback ()
void TakeDamage (int damage)
void checkAttack (double dt)
bool proximitycheck (float smallx, float largex, float smallz, float largez)
Public Member Functions inherited from HostileMob
HostileMob ()
~HostileMob ()
void checkPlayerPos (double dt, int checkRate, int lessenSpeed, float xpos, float zpos)
void MobCollision (float smallx, float largex, float smallz, float largez)
Data Fields
bool AttackAnimation
float CrystalAnim
bool BossDies
Data Fields inherited from HostileMob
bool Spawn
int health
float AttackDamage
float MobPosX
float MobPosY
float MobPosZ
float TargetDetectX
float TargetDetectZ
float mobTimeCount
Private Attributes
bool kenaWhack
float animtimer
Detailed Description
Definition at line 7 of file MobBossOne.h.
Constructor & Destructor Documentation
MobBossOne::MobBossOne ()
Definition at line 3 of file MobBossOne.cpp.
References AttackAnimation, HostileMob::AttackDamage, BossDies, HostileMob::health, kenaWhack, HostileMob::MobPosX, HostileMob::MobPosY, HostileMob::MobPosZ, HostileMob::mobTimeCount, HostileMob::Spawn, HostileMob::TargetDetectX, and HostileMob::TargetDetectZ.
MobBossOne::~MobBossOne ()
Definition at line 26 of file MobBossOne.cpp.
Member Function Documentation
void MobBossOne::attack (float damage)
Definition at line 107 of file MobBossOne.cpp.
References HostileMob::AttackDamage, BossDies, HostileMob::health, Explorer::instance(), Explorer::MinusHP(), and HostileMob::Spawn.
Referenced by checkAttack().
void MobBossOne::checkAttack (double dt)
Definition at line 45 of file MobBossOne.cpp.
References animtimer, attack(), AttackAnimation, HostileMob::AttackDamage, HostileMob::MobPosX, HostileMob::MobPosZ, and proximitycheck().
Referenced by move().
void MobBossOne::knockback ()
Definition at line 31 of file MobBossOne.cpp.
References kenaWhack.
void MobBossOne::move (double dt, int movespeed = 10)
Definition at line 73 of file MobBossOne.cpp.
References checkAttack(), CrystalAnim, HostileMob::MobPosX, HostileMob::MobPosY, HostileMob::MobPosZ, Vector3::Normalize(), HostileMob::TargetDetectX, HostileMob::TargetDetectZ, Vector3::x, and Vector3::z.
Referenced by SceneEnd::moveMob(), and SceneLevelOneB::Update().
bool MobBossOne::proximitycheck (float smallx, float largex, float smallz, float largez)
Definition at line 35 of file MobBossOne.cpp.
References HostileMob::TargetDetectX, and HostileMob::TargetDetectZ.
Referenced by checkAttack().
void MobBossOne::setSpawnBossOne (float xpos, float zpos)
Definition at line 96 of file MobBossOne.cpp.
References HostileMob::MobPosX, and HostileMob::MobPosZ.
Referenced by SceneEnd::Init(), SceneLevelOneB::Init(), SceneEnd::ResetMobs(), and SceneLevelOneB::ResetSameScene().
void MobBossOne::TakeDamage (int damage)
Definition at line 101 of file MobBossOne.cpp.
References HostileMob::health.
Referenced by SceneLevelOneB::attackCheck(), and SceneEnd::checkAttack().
Field Documentation
float MobBossOne::animtimer private
Definition at line 28 of file MobBossOne.h.
Referenced by checkAttack().
bool MobBossOne::AttackAnimation
Definition at line 20 of file MobBossOne.h.
Referenced by checkAttack(), MobBossOne(), SceneLevelOneB::RenderBoss(), and SceneEnd::RenderBoss().
bool MobBossOne::BossDies
Definition at line 23 of file MobBossOne.h.
Referenced by attack(), MobBossOne(), and SceneLevelOneB::RenderPickUpPickTools().
float MobBossOne::CrystalAnim
Definition at line 21 of file MobBossOne.h.
Referenced by move(), SceneLevelOneB::RenderBoss(), and SceneEnd::RenderBoss().
bool MobBossOne::kenaWhack private
Definition at line 26 of file MobBossOne.h.
Referenced by knockback(), and MobBossOne().
The documentation for this class was generated from the following files:
ComGraphics/Source/MobBossOne.h
ComGraphics/Source/MobBossOne.cpp