My Application: Scene Class Reference
Scene Class Reference abstract
#include <Scene.h>
Public Member Functions
Scene ()
~Scene ()
virtual void Init ()=0
virtual void Update (double dt)=0
virtual void Render ()=0
virtual void Exit ()=0
Data Fields
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Detailed Description
Definition at line 9 of file Scene.h.
Constructor & Destructor Documentation
Scene::Scene () inline
Definition at line 12 of file Scene.h.
Scene::~Scene () inline
Definition at line 13 of file Scene.h.
Member Function Documentation
virtual void Scene::Exit () pure virtual
Implemented in SceneEnd, SceneLevelOneB, SceneLevelOneA, SceneStart, SceneLevelTwo, SceneEndCutScene, OpeningCutScene2, Credits, OpeningCutScene, SceneOpening, and CutSceneOne.
Referenced by Application::Run().
virtual void Scene::Init () pure virtual
Implemented in SceneEnd, SceneLevelOneB, SceneLevelOneA, SceneStart, SceneLevelTwo, SceneEndCutScene, OpeningCutScene2, Credits, OpeningCutScene, SceneOpening, and CutSceneOne.
Referenced by Application::End_Credits(), Application::EndingCutScene(), Application::EndingScene(), Application::FirstCutScene(), Application::OpenCutScene(), Application::OpenCutScene2(), Application::OpenGame(), Application::Run(), Application::SceneLevel1A(), Application::SceneLevel1B(), Application::SceneLevel2(), and Application::StartingScene().
virtual void Scene::Render () pure virtual
Implemented in SceneEnd, SceneLevelOneB, SceneLevelOneA, SceneStart, SceneLevelTwo, SceneEndCutScene, OpeningCutScene2, Credits, OpeningCutScene, SceneOpening, and CutSceneOne.
Referenced by Application::Run().
virtual void Scene::Update (double dt) pure virtual
Implemented in SceneEnd, SceneLevelOneB, SceneLevelOneA, SceneStart, SceneLevelTwo, SceneEndCutScene, OpeningCutScene2, Credits, OpeningCutScene, SceneOpening, and CutSceneOne.
Referenced by Application::Run().
Field Documentation
misc Scene::Misc
Definition at line 24 of file Scene.h.
Referenced by SceneLevelOneB::attackCheck(), SceneLevelOneA::AttackCheck(), SceneEnd::checkAttack(), SceneLevelOneB::checkPlayerPosMisc(), SceneLevelOneB::ElevatorCheck(), and SceneLevelOneB::PuzzleOneSwitchCheck().
SwitchLightPuzzle Scene::Switches
Definition at line 22 of file Scene.h.
Referenced by SceneLevelOneB::checkDoor2(), SceneLevelOneB::PuzzleOneSwitchCheck(), SceneLevelOneB::RenderPuzzle(), and SceneLevelOneB::Update().
ToolUI::ToolType Scene::Tool
Definition at line 21 of file Scene.h.
GlobalVariables Scene::Variables
Definition at line 20 of file Scene.h.
Referenced by SceneEnd::ContinueGameOrNot(), SceneStart::MouseClickFunction(), SceneEnd::MouseClickFunction(), SceneEnd::RenderPlayerDiesInteraction(), OpeningCutScene2::RenderSkyBox(), SceneStart::RenderSkyBox(), SceneEnd::Reset(), SceneStart::ToolSelectionMouseScroll(), SceneEnd::ToolSelectionMouseScroll(), OpeningCutScene2::Update(), SceneStart::Update(), and SceneEnd::UpdatePlayerDiesInteraction().
The documentation for this class was generated from the following file:
ComGraphics/Source/Scene.h