My Application: MobGhost Class Reference
MobGhost Class Reference
#include <MobGhost.h>
Public Member Functions
MobGhost ()
~MobGhost ()
void setSpawnGhost (float xpos, float zpos)
void move (double dt, int movespeed)
void knockback ()
void TakeDamage (int damage)
void checkAttack ()
bool proximitycheck (float smallx, float largex, float smallz, float largez)
void attack (float Damage)
Public Member Functions inherited from HostileMob
HostileMob ()
~HostileMob ()
void checkPlayerPos (double dt, int checkRate, int lessenSpeed, float xpos, float zpos)
void MobCollision (float smallx, float largex, float smallz, float largez)
Data Fields
bool canHit
float mobTimeCount2
Data Fields inherited from HostileMob
bool Spawn
int health
float AttackDamage
float MobPosX
float MobPosY
float MobPosZ
float TargetDetectX
float TargetDetectZ
float mobTimeCount
Private Attributes
bool kenaWhack
Detailed Description
Definition at line 6 of file MobGhost.h.
Constructor & Destructor Documentation
MobGhost::MobGhost ()
Definition at line 5 of file MobGhost.cpp.
References HostileMob::AttackDamage, canHit, HostileMob::health, kenaWhack, HostileMob::MobPosX, HostileMob::MobPosY, HostileMob::MobPosZ, HostileMob::mobTimeCount, mobTimeCount2, HostileMob::Spawn, HostileMob::TargetDetectX, and HostileMob::TargetDetectZ.
MobGhost::~MobGhost ()
Definition at line 28 of file MobGhost.cpp.
Member Function Documentation
void MobGhost::attack (float Damage)
Definition at line 49 of file MobGhost.cpp.
References HostileMob::AttackDamage, canHit, Explorer::instance(), and Explorer::MinusHP().
Referenced by checkAttack().
void MobGhost::checkAttack ()
Definition at line 57 of file MobGhost.cpp.
References attack(), HostileMob::AttackDamage, canHit, HostileMob::MobPosX, HostileMob::MobPosZ, and proximitycheck().
Referenced by move().
void MobGhost::knockback ()
Definition at line 43 of file MobGhost.cpp.
References kenaWhack.
void MobGhost::move (double dt, int movespeed)
Definition at line 64 of file MobGhost.cpp.
References canHit, checkAttack(), HostileMob::health, HostileMob::MobPosX, HostileMob::MobPosY, HostileMob::MobPosZ, mobTimeCount2, Vector3::Normalize(), HostileMob::Spawn, HostileMob::TargetDetectX, HostileMob::TargetDetectZ, Vector3::x, and Vector3::z.
Referenced by SceneEnd::moveMob(), SceneLevelOneA::Update(), and SceneLevelOneB::Update().
bool MobGhost::proximitycheck (float smallx, float largex, float smallz, float largez)
Definition at line 33 of file MobGhost.cpp.
References HostileMob::TargetDetectX, and HostileMob::TargetDetectZ.
Referenced by checkAttack().
void MobGhost::setSpawnGhost (float xpos, float zpos)
Definition at line 102 of file MobGhost.cpp.
References HostileMob::MobPosX, and HostileMob::MobPosZ.
Referenced by SceneLevelOneA::Init(), SceneLevelOneB::Init(), SceneEnd::Init(), SceneEnd::ResetMobs(), and SceneLevelOneB::ResetSameScene().
void MobGhost::TakeDamage (int damage)
Definition at line 108 of file MobGhost.cpp.
References HostileMob::health.
Referenced by SceneLevelOneB::attackCheck(), SceneLevelOneA::AttackCheck(), and SceneEnd::checkAttack().
Field Documentation
bool MobGhost::canHit
Definition at line 20 of file MobGhost.h.
Referenced by attack(), checkAttack(), MobGhost(), and move().
bool MobGhost::kenaWhack private
Definition at line 24 of file MobGhost.h.
Referenced by knockback(), and MobGhost().
float MobGhost::mobTimeCount2
Definition at line 22 of file MobGhost.h.
Referenced by MobGhost(), and move().
The documentation for this class was generated from the following files:
ComGraphics/Source/MobGhost.h
ComGraphics/Source/MobGhost.cpp