My Application: SceneLevelTwo Class Reference
SceneLevelTwo Class Reference
#include <SceneLevelTwo.h>
Public Member Functions
SceneLevelTwo ()
~SceneLevelTwo ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void ResetAll ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_RUBBLE,
GEO_PORTRAIT, GEO_PLANETFLOOR, GEO_FACILITYFLOOR, GEO_FACILITYOUT,
GEO_FACILITYOUTWALL, GEO_FACILITYWALLS, GEO_FACILITYCEILINGS, GEO_TRAPWALL,
GEO_HEALTHBAR, GEO_STAMINABAR, GEO_LHAND, GEO_RHAND,
GEO_TOOLUIONE, GEO_TOOLUITWO, GEO_TOOLUITHREE, GEO_TOOLUIFOUR,
GEO_HANDICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_BAT,
GEO_BATICON, GEO_SWORD, GEO_SWORDICON, GEO_GHOST1,
GEO_SPAWNPOINT, GEO_SLIDEDOORTOP, GEO_SLIDEDOORBTM, GEO_LIGHTGREEN,
GEO_LIGHTRED, GEO_LEVER, GEO_DEADCOLOR, GEO_DEADBLACKSCREEN,
GEO_HEALTHICON, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void SomeUpdates (double dt)
void RenderScene ()
void RenderFloorCeiling ()
void RenderSwitches ()
void RenderDownWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber)
void RenderUpWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber)
void RenderRightWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber)
void RenderLeftWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber)
void RenderGhost1 ()
void RenderTraps ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void checkPlayerPosMisc ()
void Collision (float smallx, float largex, float smallz, float largez)
void SpecialCollision (float smallx, float largex, float smallz, float largez)
bool proximitycheck (float smallx, float largex, float smallz, float largez)
void SwitchCheck (double dt)
void PuzzleTwoSwitchCheck (double dt)
void LogicAnimationSwitches (double dt)
void SwitchCollisionChecker ()
void RenderPuzzle ()
void ToolsUI ()
void MouseScrollToolSlot ()
void RenderMouseScrollToolSlot ()
void ToolSelectionMouseScroll ()
void RenderToolIcon ()
void MouseClickFunction (double dt)
void RenderPlayerDiesInteraction ()
void UpdatePlayerDiesInteraction (double dt)
void ContinueGameOrNot ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
GlobalVariables Variables
misc Misc
float FPS
bool displayInteract1
bool activateDoor1
float CollXLarge [60]
float CollXSmall [60]
float CollZLarge [60]
float CollZSmall [60]
bool Switch1Int
bool Switch2Int
float Switch1Rot
float Switch2Rot
bool Switch1Press
bool Switch2Press
float transSpikeDoor
bool closeDoors
float timerDoor
bool openDoor1
bool openDoor2
bool invisWALLDisappear
bool puzzling
float transSpikeWall2
bool hitWall
MobGhost Ghost
Detailed Description
Definition at line 13 of file SceneLevelTwo.h.
Member Enumeration Documentation
enum SceneLevelTwo::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_RUBBLE
GEO_PORTRAIT
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_TRAPWALL
GEO_HEALTHBAR
GEO_STAMINABAR
GEO_LHAND
GEO_RHAND
GEO_TOOLUIONE
GEO_TOOLUITWO
GEO_TOOLUITHREE
GEO_TOOLUIFOUR
GEO_HANDICON
GEO_PICKAXE
GEO_PICKAXEICON
GEO_BAT
GEO_BATICON
GEO_SWORD
GEO_SWORDICON
GEO_GHOST1
GEO_SPAWNPOINT
GEO_SLIDEDOORTOP
GEO_SLIDEDOORBTM
GEO_LIGHTGREEN
GEO_LIGHTRED
GEO_LEVER
GEO_DEADCOLOR
GEO_DEADBLACKSCREEN
GEO_HEALTHICON
NUM_GEOMETRY
Definition at line 15 of file SceneLevelTwo.h.
enum SceneLevelTwo::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 84 of file SceneLevelTwo.h.
Constructor & Destructor Documentation
SceneLevelTwo::SceneLevelTwo ()
Definition at line 16 of file SceneLevelTwo.cpp.
References closeDoors, hitWall, invisWALLDisappear, openDoor1, openDoor2, puzzling, Switch1Int, Switch1Press, Switch1Rot, Switch2Int, Switch2Press, Switch2Rot, timerDoor, transSpikeDoor, and transSpikeWall2.
SceneLevelTwo::~SceneLevelTwo ()
Definition at line 35 of file SceneLevelTwo.cpp.
Member Function Documentation
void SceneLevelTwo::checkPlayerPosMisc () private
Definition at line 557 of file SceneLevelTwo.cpp.
References camera, misc::camX, misc::camY, misc::camZ, Misc, Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneLevelTwo::Collision (float smallx, float largex, float smallz, float largez) private
Definition at line 310 of file SceneLevelTwo.cpp.
References camera, Math::DegreeToRadian(), Camera::position, Camera3::rotationX, Camera3::rotationY, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SomeUpdates(), SwitchCollisionChecker(), and Update().
void SceneLevelTwo::ContinueGameOrNot () private
Definition at line 529 of file SceneLevelTwo.cpp.
References camera, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Application::IsKeyPressed(), light, m_parameters, Application::OpenGame(), Explorer::PlayerLife, Camera::position, Light::power, Reset(), Explorer::SavePoint, U_LIGHT0_POWER, and Variables.
Referenced by Update().
void SceneLevelTwo::Exit () virtual
Implements Scene.
Definition at line 1231 of file SceneLevelTwo.cpp.
References m_programID, and m_vertexArrayID.
void SceneLevelTwo::Init () virtual
Implements Scene.
Definition at line 39 of file SceneLevelTwo.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BAT, GEO_BATICON, GEO_BOTTOM, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_FACILITYCEILINGS, GEO_FACILITYFLOOR, GEO_FACILITYWALLS, GEO_FRONT, GEO_HANDICON, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_LEFT, GEO_LEVER, GEO_LHAND, GEO_LIGHTBALL, GEO_LIGHTGREEN, GEO_LIGHTRED, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PORTRAIT, GEO_RHAND, GEO_RIGHT, GEO_RUBBLE, GEO_SLIDEDOORBTM, GEO_SLIDEDOORTOP, GEO_SPAWNPOINT, GEO_STAMINABAR, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, GEO_TOP, GEO_TRAPWALL, Camera3::Init(), Explorer::instance(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Explorer::SavePoint, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void SceneLevelTwo::LogicAnimationSwitches (double dt) private
Definition at line 849 of file SceneLevelTwo.cpp.
References GlobalVariables::b_SwitchAnimate, GlobalVariables::f_SwitchRotateFour, GlobalVariables::f_SwitchRotateOne, GlobalVariables::f_SwitchRotateThree, GlobalVariables::f_SwitchRotateTwo, and Variables.
Referenced by Update().
void SceneLevelTwo::MouseClickFunction (double dt) private
Definition at line 487 of file SceneLevelTwo.cpp.
References GlobalVariables::b_LockSwing, GlobalVariables::b_LockSwingDebounce, Explorer::instance(), Application::IsKeyPressed(), GlobalVariables::RotateX, Explorer::stamina, and Variables.
Referenced by Update().
void SceneLevelTwo::MouseScrollToolSlot () private
Definition at line 446 of file SceneLevelTwo.cpp.
References Explorer::i_SlotIndex, Explorer::instance(), and Application::mouse_scroll.
Referenced by Update().
bool SceneLevelTwo::proximitycheck (float smallx, float largex, float smallz, float largez) private
Definition at line 338 of file SceneLevelTwo.cpp.
References camera, Camera::position, Vector3::x, and Vector3::z.
Referenced by SomeUpdates().
void SceneLevelTwo::PuzzleTwoSwitchCheck (double dt) private
Definition at line 729 of file SceneLevelTwo.cpp.
References SwitchLightPuzzle::b_PuzzleOne, SwitchLightPuzzle::b_PuzzleTwo, GlobalVariables::b_SwitchAnimate, camera, GlobalVariables::f_SwitchDebounce, Application::IsKeyPressed(), Camera::position, Scene::Switches, Variables, Vector3::x, and Vector3::z.
Referenced by Update().
void SceneLevelTwo::Render () virtual
Implements Scene.
Definition at line 1154 of file SceneLevelTwo.cpp.
References camera, displayInteract1, FPS, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_STAMINABAR, GEO_TEXT, Explorer::instance(), invisWALLDisappear, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, Explorer::PlayerLife, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderModelOnScreen(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderPuzzle(), RenderScene(), RenderTextOnScreen(), RenderToolIcon(), RenderTraps(), Light::spotDirection, Switch1Int, Switch2Int, Camera::target, timerDoor, ToolSelectionMouseScroll(), MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneLevelTwo::RenderDownWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber) private
Definition at line 466 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelTwo::RenderFloorCeiling () private
Definition at line 9 of file SceneLevelTwoRenders.cpp.
References GEO_FACILITYCEILINGS, GEO_FACILITYFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelTwo::RenderGhost1 () private
Definition at line 361 of file SceneLevelTwoRenders.cpp.
References GEO_GHOST1, Ghost, meshList, HostileMob::MobPosX, HostileMob::MobPosY, HostileMob::MobPosZ, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), and MS::Translate().
void SceneLevelTwo::RenderLeftWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber) private
Definition at line 639 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelTwo::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 1013 of file SceneLevelTwo.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderDownWall(), RenderFloorCeiling(), RenderGhost1(), RenderLeftWall(), RenderModelOnScreen(), RenderPuzzle(), RenderRightWall(), RenderScene(), RenderSwitches(), RenderTraps(), and RenderUpWall().
void SceneLevelTwo::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 1133 of file SceneLevelTwo.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderToolIcon(), and ToolSelectionMouseScroll().
void SceneLevelTwo::RenderMouseScrollToolSlot () private
Definition at line 469 of file SceneLevelTwo.cpp.
References GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, Explorer::instance(), meshList, and RenderModelOnScreen().
Referenced by Render().
void SceneLevelTwo::RenderPlayerDiesInteraction () private
Definition at line 369 of file SceneLevelTwoRenders.cpp.
References GlobalVariables::f_redScreenTimer, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_TEXT, Explorer::instance(), meshList, RenderModelOnScreen(), RenderTextOnScreen(), and Variables.
Referenced by Render().
void SceneLevelTwo::RenderPuzzle () private
Definition at line 403 of file SceneLevelTwoRenders.cpp.
References SwitchLightPuzzle::b_PuzzleTwo, GlobalVariables::f_SwitchRotateFour, GlobalVariables::f_SwitchRotateOne, GlobalVariables::f_SwitchRotateThree, GlobalVariables::f_SwitchRotateTwo, GEO_LEVER, GEO_LIGHTGREEN, GEO_LIGHTRED, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Scene::Switches, MS::Translate(), and Variables.
Referenced by Render(), and Update().
void SceneLevelTwo::RenderRightWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber) private
Definition at line 582 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelTwo::RenderScene () private
Definition at line 27 of file SceneLevelTwoRenders.cpp.
References anima, camera, misc::camX, misc::camY, misc::camZ, Animation::DoorSlideBtm_5, Animation::DoorSlideTop_5, GEO_SLIDEDOORBTM, GEO_SLIDEDOORTOP, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Animation::QPDOOR1_BOT, Animation::QPDOOR1_TOP, Animation::QPDOOR2_BOT, Animation::QPDOOR2_TOP, Animation::QPDOOR3_BOT, Animation::QPDOOR3_TOP, Animation::QPDOOR4_BOT, Animation::QPDOOR4_TOP, Animation::QPDOOR5_BOT, Animation::QPDOOR5_TOP, RenderDownWall(), RenderFloorCeiling(), RenderLeftWall(), RenderMesh(), RenderRightWall(), RenderSwitches(), RenderUpWall(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneLevelTwo::RenderSwitches () private
Definition at line 299 of file SceneLevelTwoRenders.cpp.
References GEO_LEVER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), Switch1Rot, Switch2Rot, and MS::Translate().
Referenced by RenderScene().
void SceneLevelTwo::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 1057 of file SceneLevelTwo.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneLevelTwo::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 1087 of file SceneLevelTwo.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), and RenderPlayerDiesInteraction().
void SceneLevelTwo::RenderToolIcon () private
Definition at line 387 of file SceneLevelTwo.cpp.
References ToolUI::BaseballBat, GEO_BATICON, GEO_HANDICON, GEO_PICKAXEICON, GEO_SWORDICON, ToolUI::Hand, Explorer::instance(), meshList, ToolUI::Pickaxe, RenderModelOnScreen(), and ToolUI::Sword.
Referenced by Render().
void SceneLevelTwo::RenderTraps () private
Definition at line 195 of file SceneLevelTwoRenders.cpp.
References GEO_TRAPWALL, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), transSpikeDoor, and transSpikeWall2.
Referenced by Render().
void SceneLevelTwo::RenderUpWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber) private
Definition at line 525 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelTwo::Reset () virtual
Definition at line 233 of file SceneLevelTwo.cpp.
References activateDoor1, anima, Explorer::checkSavePoint, closeDoors, Animation::ClosingDoorBtm5, Animation::ClosingDoorTop5, Animation::DoorSlideBtm_5, Animation::DoorSlideTop_5, GlobalVariables::f_redScreenTimer, hitWall, Explorer::hp, Explorer::instance(), invisWALLDisappear, Explorer::isDead, openDoor1, openDoor2, puzzling, Animation::QP_BOTDOOR1, Animation::QP_BOTDOOR2, Animation::QP_BOTDOOR3, Animation::QP_BOTDOOR4, Animation::QP_BOTDOOR5, Animation::QP_TOPDOOR1, Animation::QP_TOPDOOR2, Animation::QP_TOPDOOR3, Animation::QP_TOPDOOR4, Animation::QP_TOPDOOR5, Animation::QPDOOR1_BOT, Animation::QPDOOR1_TOP, Animation::QPDOOR2_BOT, Animation::QPDOOR2_TOP, Animation::QPDOOR3_BOT, Animation::QPDOOR3_TOP, Animation::QPDOOR4_BOT, Animation::QPDOOR4_TOP, Animation::QPDOOR5_BOT, Animation::QPDOOR5_TOP, Explorer::SavePoint, Explorer::stamina, Switch1Int, Switch1Press, Switch1Rot, Switch2Int, Switch2Press, Switch2Rot, timerDoor, transSpikeDoor, transSpikeWall2, and Variables.
Referenced by ContinueGameOrNot().
void SceneLevelTwo::ResetAll () virtual
Definition at line 296 of file SceneLevelTwo.cpp.
References Explorer::checkSavePoint, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Explorer::PlayerLife, Explorer::SavePoint, and Variables.
Referenced by Update().
void SceneLevelTwo::SomeUpdates (double dt) private
Definition at line 564 of file SceneLevelTwo.cpp.
References anima, closeDoors, Animation::CloseSlideDoor5(), Collision(), Application::EndingScene(), hitWall, Explorer::instance(), invisWALLDisappear, Explorer::isDead, Application::IsKeyPressed(), Misc, openDoor1, openDoor2, Animation::OpenQPDOOR1(), Animation::OpenQPDOOR2(), Animation::OpenQPDOOR3(), Animation::OpenQPDOOR4(), Animation::OpenQPDOOR5(), proximitycheck(), puzzling, Animation::QP_BOTDOOR1, Animation::QP_BOTDOOR2, Animation::QP_BOTDOOR3, Animation::QP_BOTDOOR4, Animation::QP_BOTDOOR5, Animation::QP_TOPDOOR1, Animation::QP_TOPDOOR2, Animation::QP_TOPDOOR3, Animation::QP_TOPDOOR4, Animation::QP_TOPDOOR5, Animation::QPDOOR4_TOP, SpecialCollision(), Switch1Press, Switch2Press, Scene::Switches, SwitchLightPuzzle::SwitchPuzzleTwo(), timerDoor, transSpikeDoor, transSpikeWall2, and misc::WithinArea().
Referenced by Update().
void SceneLevelTwo::SpecialCollision (float smallx, float largex, float smallz, float largez) private
Definition at line 324 of file SceneLevelTwo.cpp.
References camera, Math::DegreeToRadian(), hitWall, Camera::position, Camera3::rotationX, Camera3::rotationY, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SomeUpdates().
void SceneLevelTwo::SwitchCheck (double dt) private
Definition at line 316 of file SceneLevelTwoRenders.cpp.
References Application::IsKeyPressed(), Switch1Int, Switch1Press, Switch1Rot, Switch2Int, Switch2Press, Switch2Rot, and misc::WithinArea().
Referenced by Update().
void SceneLevelTwo::SwitchCollisionChecker () private
Definition at line 724 of file SceneLevelTwo.cpp.
References Collision().
Referenced by Update().
void SceneLevelTwo::ToolSelectionMouseScroll () private
Definition at line 354 of file SceneLevelTwo.cpp.
References ToolUI::BaseballBat, GEO_BAT, GEO_LHAND, GEO_PICKAXE, GEO_RHAND, GEO_SWORD, ToolUI::Hand, Explorer::instance(), meshList, modelStack, ToolUI::Pickaxe, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), GlobalVariables::RotateX, ToolUI::Sword, and Variables.
Referenced by Render().
void SceneLevelTwo::ToolsUI () private
Definition at line 349 of file SceneLevelTwo.cpp.
Referenced by Update().
void SceneLevelTwo::Update (double dt) virtual
Implements Scene.
Definition at line 932 of file SceneLevelTwo.cpp.
References camera, Explorer::checkDead(), checkPlayerPosMisc(), Collision(), CollXLarge, CollXSmall, CollZLarge, CollZSmall, ContinueGameOrNot(), Explorer::f_FlickeringLight, FPS, Explorer::InsertToolSlot(), Explorer::instance(), Application::IsKeyPressed(), light, LogicAnimationSwitches(), m_parameters, MouseClickFunction(), MouseScrollToolSlot(), Application::OpenGame(), ToolUI::Pickaxe, Light::position, Camera::position, Light::power, PuzzleTwoSwitchCheck(), RenderPuzzle(), ResetAll(), Position::Set(), Vector3::Set(), SomeUpdates(), Light::spotDirection, SwitchCheck(), SwitchCollisionChecker(), Scene::Switches, SwitchLightPuzzle::SwitchPuzzleTwo(), Camera::target, ToolsUI(), U_LIGHT0_POWER, Camera3::Update(), UpdatePlayerDiesInteraction(), Vector3::x, Vector3::y, and Vector3::z.
void SceneLevelTwo::UpdatePlayerDiesInteraction (double dt) private
Definition at line 519 of file SceneLevelTwo.cpp.
References GlobalVariables::f_redScreenTimer, Explorer::instance(), light, m_parameters, Light::power, U_LIGHT0_POWER, and Variables.
Referenced by Update().
Field Documentation
bool SceneLevelTwo::activateDoor1 private
Definition at line 196 of file SceneLevelTwo.h.
Referenced by Reset().
Animation SceneLevelTwo::anima private
Definition at line 183 of file SceneLevelTwo.h.
Referenced by RenderScene(), Reset(), and SomeUpdates().
Camera3 SceneLevelTwo::camera
Definition at line 125 of file SceneLevelTwo.h.
Referenced by checkPlayerPosMisc(), Collision(), ContinueGameOrNot(), Init(), proximitycheck(), PuzzleTwoSwitchCheck(), Render(), RenderScene(), SpecialCollision(), and Update().
bool SceneLevelTwo::closeDoors private
Definition at line 210 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), and SomeUpdates().
float SceneLevelTwo::CollXLarge[60] private
Definition at line 198 of file SceneLevelTwo.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelTwo::CollXSmall[60] private
Definition at line 199 of file SceneLevelTwo.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelTwo::CollZLarge[60] private
Definition at line 200 of file SceneLevelTwo.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelTwo::CollZSmall[60] private
Definition at line 201 of file SceneLevelTwo.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
bool SceneLevelTwo::displayInteract1 private
Definition at line 195 of file SceneLevelTwo.h.
Referenced by Render().
Vector3 SceneLevelTwo::end private
Definition at line 190 of file SceneLevelTwo.h.
float SceneLevelTwo::FPS private
Definition at line 194 of file SceneLevelTwo.h.
Referenced by Render(), and Update().
MobGhost SceneLevelTwo::Ghost private
Definition at line 218 of file SceneLevelTwo.h.
Referenced by RenderGhost1().
bool SceneLevelTwo::hitWall private
Definition at line 217 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), SomeUpdates(), and SpecialCollision().
bool SceneLevelTwo::invisWALLDisappear private
Definition at line 214 of file SceneLevelTwo.h.
Referenced by Render(), Reset(), SceneLevelTwo(), and SomeUpdates().
Light SceneLevelTwo::light[1] private
Definition at line 187 of file SceneLevelTwo.h.
Referenced by ContinueGameOrNot(), Init(), Render(), Update(), and UpdatePlayerDiesInteraction().
unsigned SceneLevelTwo::m_parameters[U_TOTAL] private
Definition at line 181 of file SceneLevelTwo.h.
Referenced by ContinueGameOrNot(), Init(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), Update(), and UpdatePlayerDiesInteraction().
unsigned SceneLevelTwo::m_programID private
Definition at line 180 of file SceneLevelTwo.h.
Referenced by Exit(), and Init().
unsigned SceneLevelTwo::m_vertexArrayID private
Definition at line 177 of file SceneLevelTwo.h.
Referenced by Exit(), and Init().
Mesh* SceneLevelTwo::meshList[NUM_GEOMETRY] private
Definition at line 178 of file SceneLevelTwo.h.
Referenced by Init(), Render(), RenderDownWall(), RenderFloorCeiling(), RenderGhost1(), RenderLeftWall(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderPuzzle(), RenderRightWall(), RenderScene(), RenderSwitches(), RenderToolIcon(), RenderTraps(), RenderUpWall(), and ToolSelectionMouseScroll().
misc SceneLevelTwo::Misc private
Definition at line 192 of file SceneLevelTwo.h.
Referenced by checkPlayerPosMisc(), and SomeUpdates().
MS SceneLevelTwo::modelStack private
Definition at line 185 of file SceneLevelTwo.h.
Referenced by Render(), RenderDownWall(), RenderFloorCeiling(), RenderGhost1(), RenderLeftWall(), RenderMesh(), RenderModelOnScreen(), RenderPuzzle(), RenderRightWall(), RenderScene(), RenderSwitches(), RenderText(), RenderTextOnScreen(), RenderTraps(), RenderUpWall(), and ToolSelectionMouseScroll().
bool SceneLevelTwo::openDoor1 private
Definition at line 212 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), and SomeUpdates().
bool SceneLevelTwo::openDoor2 private
Definition at line 213 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), and SomeUpdates().
MS SceneLevelTwo::projectionStack private
Definition at line 185 of file SceneLevelTwo.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
bool SceneLevelTwo::puzzling private
Definition at line 215 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), and SomeUpdates().
Vector3 SceneLevelTwo::start private
Definition at line 189 of file SceneLevelTwo.h.
bool SceneLevelTwo::Switch1Int private
Definition at line 203 of file SceneLevelTwo.h.
Referenced by Render(), Reset(), SceneLevelTwo(), and SwitchCheck().
bool SceneLevelTwo::Switch1Press private
Definition at line 207 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), SomeUpdates(), and SwitchCheck().
float SceneLevelTwo::Switch1Rot private
Definition at line 205 of file SceneLevelTwo.h.
Referenced by RenderSwitches(), Reset(), SceneLevelTwo(), and SwitchCheck().
bool SceneLevelTwo::Switch2Int private
Definition at line 204 of file SceneLevelTwo.h.
Referenced by Render(), Reset(), SceneLevelTwo(), and SwitchCheck().
bool SceneLevelTwo::Switch2Press private
Definition at line 208 of file SceneLevelTwo.h.
Referenced by Reset(), SceneLevelTwo(), SomeUpdates(), and SwitchCheck().
float SceneLevelTwo::Switch2Rot private
Definition at line 206 of file SceneLevelTwo.h.
Referenced by RenderSwitches(), Reset(), SceneLevelTwo(), and SwitchCheck().
float SceneLevelTwo::timerDoor private
Definition at line 211 of file SceneLevelTwo.h.
Referenced by Render(), Reset(), SceneLevelTwo(), and SomeUpdates().
float SceneLevelTwo::transSpikeDoor private
Definition at line 209 of file SceneLevelTwo.h.
Referenced by RenderTraps(), Reset(), SceneLevelTwo(), and SomeUpdates().
float SceneLevelTwo::transSpikeWall2 private
Definition at line 216 of file SceneLevelTwo.h.
Referenced by RenderTraps(), Reset(), SceneLevelTwo(), and SomeUpdates().
GlobalVariables SceneLevelTwo::Variables private
Definition at line 191 of file SceneLevelTwo.h.
Referenced by ContinueGameOrNot(), LogicAnimationSwitches(), MouseClickFunction(), PuzzleTwoSwitchCheck(), RenderPlayerDiesInteraction(), RenderPuzzle(), Reset(), ResetAll(), ToolSelectionMouseScroll(), and UpdatePlayerDiesInteraction().
MS SceneLevelTwo::viewStack private
Definition at line 185 of file SceneLevelTwo.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneLevelTwo.h
ComGraphics/Source/MapRender.cpp
ComGraphics/Source/SceneLevelTwo.cpp
ComGraphics/Source/SceneLevelTwoRenders.cpp