My Application: CutSceneOne Class Reference
CutSceneOne Class Reference
#include <CutSceneOne.h>
Public Member Functions
CutSceneOne ()
~CutSceneOne ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE { GEO_MAINDOORLEFT, GEO_MAINDOORRIGHT, NUM_GEOMETRY }
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderCutSceneOne ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
GlobalVariables Variables
Detailed Description
Definition at line 13 of file CutSceneOne.h.
Member Enumeration Documentation
enum CutSceneOne::GEOMETRY_TYPE private
Enumerator
GEO_MAINDOORLEFT
GEO_MAINDOORRIGHT
NUM_GEOMETRY
Definition at line 15 of file CutSceneOne.h.
enum CutSceneOne::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 22 of file CutSceneOne.h.
Constructor & Destructor Documentation
CutSceneOne::CutSceneOne ()
Definition at line 16 of file CutSceneOne.cpp.
CutSceneOne::~CutSceneOne ()
Definition at line 20 of file CutSceneOne.cpp.
Member Function Documentation
void CutSceneOne::Exit () virtual
Implements Scene.
Definition at line 264 of file CutSceneOne.cpp.
References m_programID, and m_vertexArrayID.
void CutSceneOne::Init () virtual
Implements Scene.
Definition at line 24 of file CutSceneOne.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateOBJ(), GEO_MAINDOORLEFT, GEO_MAINDOORRIGHT, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void CutSceneOne::Render () virtual
Implements Scene.
Definition at line 226 of file CutSceneOne.cpp.
References camera, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, modelStack, Light::position, Camera::position, RenderCutSceneOne(), Light::spotDirection, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void CutSceneOne::RenderCutSceneOne () private
Definition at line 8 of file CutSceneOneRenders.cpp.
References anima, GEO_MAINDOORLEFT, GEO_MAINDOORRIGHT, meshList, modelStack, Animation::OpenDoorL, Animation::OpenDoorR, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void CutSceneOne::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 182 of file CutSceneOne.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderCutSceneOne().
void CutSceneOne::Reset () virtual
Definition at line 119 of file CutSceneOne.cpp.
void CutSceneOne::Update (double dt) virtual
Implements Scene.
Definition at line 125 of file CutSceneOne.cpp.
References anima, camera, Animation::cameramove2, Animation::cameramove3, Application::IsKeyPressed(), light, Animation::OpenDoorL, Animation::OpenMainDoor(), Light::position, Camera::position, Application::SceneLevel1A(), Position::Set(), Vector3::Set(), Light::spotDirection, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Animation CutSceneOne::anima private
Definition at line 75 of file CutSceneOne.h.
Referenced by RenderCutSceneOne(), and Update().
Camera3 CutSceneOne::camera
Definition at line 62 of file CutSceneOne.h.
Referenced by Init(), Render(), and Update().
Vector3 CutSceneOne::end private
Definition at line 82 of file CutSceneOne.h.
Light CutSceneOne::light[1] private
Definition at line 79 of file CutSceneOne.h.
Referenced by Init(), Render(), and Update().
unsigned CutSceneOne::m_parameters[U_TOTAL] private
Definition at line 73 of file CutSceneOne.h.
Referenced by Init(), Render(), and RenderMesh().
unsigned CutSceneOne::m_programID private
Definition at line 72 of file CutSceneOne.h.
Referenced by Exit(), and Init().
unsigned CutSceneOne::m_vertexArrayID private
Definition at line 69 of file CutSceneOne.h.
Referenced by Exit(), and Init().
Mesh* CutSceneOne::meshList[NUM_GEOMETRY] private
Definition at line 70 of file CutSceneOne.h.
Referenced by Init(), and RenderCutSceneOne().
MS CutSceneOne::modelStack private
Definition at line 77 of file CutSceneOne.h.
Referenced by Render(), RenderCutSceneOne(), and RenderMesh().
MS CutSceneOne::projectionStack private
Definition at line 77 of file CutSceneOne.h.
Referenced by Init(), and RenderMesh().
Vector3 CutSceneOne::start private
Definition at line 81 of file CutSceneOne.h.
GlobalVariables CutSceneOne::Variables private
Definition at line 83 of file CutSceneOne.h.
MS CutSceneOne::viewStack private
Definition at line 77 of file CutSceneOne.h.
Referenced by Render(), and RenderMesh().
The documentation for this class was generated from the following files:
ComGraphics/Source/CutSceneOne.h
ComGraphics/Source/CutSceneOne.cpp
ComGraphics/Source/CutSceneOneRenders.cpp