My Application: SceneEnd Class Reference
SceneEnd Class Reference
#include <SceneEnd.h>
Public Member Functions
SceneEnd ()
~SceneEnd ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_MAINDOORLEFT,
GEO_MAINDOORRIGHT, GEO_RUBBLE, GEO_PORTRAIT, GEO_PLANETFLOOR,
GEO_FACILITYFLOOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FACILITYWALLS,
GEO_FACILITYCEILINGS, GEO_ROCK, GEO_TOOLUIONE, GEO_TOOLUITWO,
GEO_TOOLUITHREE, GEO_TOOLUIFOUR, GEO_LHAND, GEO_RHAND,
GEO_HANDICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_BAT,
GEO_BATICON, GEO_SWORD, GEO_SWORDICON, GEO_GHOST1,
GEO_BOSS, GEO_CRYSTAL1, GEO_CRYSTAL2, GEO_DEADCOLOR,
GEO_DEADBLACKSCREEN, GEO_SPACESHIP, GEO_REPAIRPOD, GEO_REPAIRDONE,
GEO_HEALTHICON, GEO_HEALTHBAR, GEO_STAMINABAR, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderLevel1 ()
void RenderFloor ()
void RenderSkyBox ()
void RenderSceneEnd ()
void RenderDownWall (int xPos, int zPos)
void RenderGhost1 ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float Tx, float Ty, float Tz, bool LightYN)
void checkPlayerPos (double dt, int checkRate, int lessenSpeed)
void checkPlayerPosMisc ()
void Collision (float smallx, float largex, float smallz, float largez)
bool proximitycheck (float smallx, float largex, float smallz, float largez)
void PuzzleOneSwitchCheck (double dt)
bool b_ReadyToFly ()
void RenderShipAndPod ()
void RenderRepairText ()
void RenderMineText ()
void UpdateRepairs (double dt)
void MouseScrollToolSlot ()
void RenderMouseScrollToolSlot ()
void ToolSelectionMouseScroll ()
void RenderToolIcon ()
void MouseClickFunction (double dt)
void RenderPlayerDiesInteraction ()
void UpdatePlayerDiesInteraction (double dt)
void ContinueGameOrNot ()
void moveMob (double dt)
void RenderMobs (float xpos, float zpos)
void RenderBoss (float xpos, float zpos)
void ResetMobs ()
void MobCheck ()
void checkAttack ()
Private Attributes
bool b_RepairDone [3]
bool b_startRepair [3]
float f_RepairProcess
float f_rockY
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
float worldspin
Vector3 start
Vector3 end
float FPS
MobGhost MobOne
MobGhost MobTwo
MobGhost MobThree
MobBossOne BossOne
bool spawnWaveOne =false
int killCounter
int waveCounter
int MobMS
int BossMS
bool CrosshairHit
Detailed Description
Definition at line 15 of file SceneEnd.h.
Member Enumeration Documentation
enum SceneEnd::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_MAINDOORLEFT
GEO_MAINDOORRIGHT
GEO_RUBBLE
GEO_PORTRAIT
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_ROCK
GEO_TOOLUIONE
GEO_TOOLUITWO
GEO_TOOLUITHREE
GEO_TOOLUIFOUR
GEO_LHAND
GEO_RHAND
GEO_HANDICON
GEO_PICKAXE
GEO_PICKAXEICON
GEO_BAT
GEO_BATICON
GEO_SWORD
GEO_SWORDICON
GEO_GHOST1
GEO_BOSS
GEO_CRYSTAL1
GEO_CRYSTAL2
GEO_DEADCOLOR
GEO_DEADBLACKSCREEN
GEO_SPACESHIP
GEO_REPAIRPOD
GEO_REPAIRDONE
GEO_HEALTHICON
GEO_HEALTHBAR
GEO_STAMINABAR
NUM_GEOMETRY
Definition at line 17 of file SceneEnd.h.
enum SceneEnd::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 87 of file SceneEnd.h.
Constructor & Destructor Documentation
SceneEnd::SceneEnd ()
Definition at line 16 of file SceneEnd.cpp.
References b_RepairDone, b_startRepair, BossMS, CrosshairHit, f_RepairProcess, f_rockY, killCounter, MobMS, spawnWaveOne, and waveCounter.
SceneEnd::~SceneEnd ()
Definition at line 35 of file SceneEnd.cpp.
Member Function Documentation
bool SceneEnd::b_ReadyToFly () private
Definition at line 530 of file SceneEnd.cpp.
References b_RepairDone.
Referenced by Update().
void SceneEnd::checkAttack () private
Definition at line 424 of file SceneEndRenders.cpp.
References BossOne, camera, Collision(), CrosshairHit, misc::hitting(), Explorer::instance(), Application::IsKeyPressed(), Scene::Misc, MobOne, HostileMob::MobPosX, HostileMob::MobPosZ, MobThree, MobTwo, Camera::position, MobGhost::TakeDamage(), MobBossOne::TakeDamage(), Camera3::view, Vector3::x, and Vector3::z.
Referenced by MouseClickFunction().
void SceneEnd::checkPlayerPos (double dt, int checkRate, int lessenSpeed) private
void SceneEnd::checkPlayerPosMisc () private
void SceneEnd::Collision (float smallx, float largex, float smallz, float largez) private
Definition at line 258 of file SceneEnd.cpp.
References camera, Math::DegreeToRadian(), Camera::position, Camera3::rotationX, Camera3::rotationY, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by checkAttack(), and Update().
void SceneEnd::ContinueGameOrNot () private
Definition at line 293 of file SceneEnd.cpp.
References b_RepairDone, b_startRepair, camera, GlobalVariables::f_redScreenTimer, f_RepairProcess, f_rockY, Explorer::hp, Explorer::instance(), Explorer::isDead, Application::IsKeyPressed(), Application::OpenGame(), Explorer::PlayerLife, Camera::position, Reset(), Scene::Variables, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneEnd::Exit () virtual
Implements Scene.
Definition at line 874 of file SceneEnd.cpp.
References m_programID, and m_vertexArrayID.
void SceneEnd::Init () virtual
Implements Scene.
Definition at line 39 of file SceneEnd.cpp.
References BossOne, camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), MeshBuilder::GenerateTorus(), GEO_AXES, GEO_BACK, GEO_BAT, GEO_BATICON, GEO_BOSS, GEO_BOTTOM, GEO_CRYSTAL1, GEO_CRYSTAL2, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FRONT, GEO_GHOST1, GEO_HANDICON, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_LEFT, GEO_LHAND, GEO_LIGHTBALL, GEO_MAINDOORLEFT, GEO_MAINDOORRIGHT, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PLANETFLOOR, GEO_PORTRAIT, GEO_REPAIRDONE, GEO_REPAIRPOD, GEO_RHAND, GEO_RIGHT, GEO_ROCK, GEO_RUBBLE, GEO_SPACESHIP, GEO_STAMINABAR, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, MobOne, MobThree, MobTwo, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), MobBossOne::setSpawnBossOne(), MobGhost::setSpawnGhost(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void SceneEnd::MobCheck () private
Definition at line 457 of file SceneEndRenders.cpp.
References BossOne, HostileMob::health, MobOne, MobThree, MobTwo, ResetMobs(), and HostileMob::Spawn.
Referenced by Update().
void SceneEnd::MouseClickFunction (double dt) private
Definition at line 459 of file SceneEnd.cpp.
References GlobalVariables::b_LockSwing, GlobalVariables::b_LockSwingDebounce, checkAttack(), CrosshairHit, Explorer::instance(), Application::IsKeyPressed(), GlobalVariables::RotateX, Explorer::stamina, and Scene::Variables.
Referenced by Update().
void SceneEnd::MouseScrollToolSlot () private
Definition at line 326 of file SceneEnd.cpp.
References Explorer::i_SlotIndex, Explorer::instance(), and Application::mouse_scroll.
Referenced by Update().
void SceneEnd::moveMob (double dt) private
Definition at line 506 of file SceneEndRenders.cpp.
References BossMS, BossOne, MobMS, MobOne, MobThree, MobTwo, MobGhost::move(), MobBossOne::move(), and HostileMob::Spawn.
Referenced by Update().
bool SceneEnd::proximitycheck (float smallx, float largex, float smallz, float largez) private
Definition at line 272 of file SceneEnd.cpp.
References camera, Camera::position, Vector3::x, and Vector3::z.
void SceneEnd::PuzzleOneSwitchCheck (double dt) private
void SceneEnd::Render () virtual
Implements Scene.
Definition at line 776 of file SceneEnd.cpp.
References b_RepairDone, BossOne, camera, CrosshairHit, f_rockY, FPS, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_ROCK, GEO_STAMINABAR, GEO_TEXT, Explorer::instance(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, MobOne, HostileMob::MobPosX, HostileMob::MobPosZ, MobThree, MobTwo, modelStack, Explorer::PlayerLife, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderBoss(), RenderDownWall(), RenderFloor(), RenderMesh(), RenderMineText(), RenderMobs(), RenderModelOnScreen(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderRepairText(), RenderSceneEnd(), RenderShipAndPod(), RenderSkyBox(), RenderTextOnScreen(), RenderToolIcon(), MS::Scale(), HostileMob::Spawn, Light::spotDirection, Camera::target, ToolSelectionMouseScroll(), MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneEnd::RenderBoss (float xpos, float zpos) private
Definition at line 385 of file SceneEndRenders.cpp.
References MobBossOne::AttackAnimation, BossOne, camera, MobBossOne::CrystalAnim, GEO_BOSS, GEO_CRYSTAL1, GEO_CRYSTAL2, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneEnd::RenderDownWall (int xPos, int zPos) private
Definition at line 695 of file MapRender.cpp.
References GEO_FACILITYOUTWALL, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEnd::RenderFloor () private
Definition at line 68 of file SceneEndRenders.cpp.
References GEO_PLANETFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEnd::RenderGhost1 () private
void SceneEnd::RenderLevel1 () private
void SceneEnd::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 635 of file SceneEnd.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderBoss(), RenderDownWall(), RenderFloor(), RenderMobs(), RenderModelOnScreen(), RenderSceneEnd(), RenderShipAndPod(), and RenderSkyBox().
void SceneEnd::RenderMineText () private
Definition at line 201 of file SceneEndRenders.cpp.
References b_RepairDone, b_startRepair, camera, GEO_TEXT, Explorer::instance(), meshList, ToolUI::Pickaxe, Camera::position, RenderTextOnScreen(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneEnd::RenderMobs (float xpos, float zpos) private
Definition at line 363 of file SceneEndRenders.cpp.
References camera, GEO_GHOST1, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneEnd::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float Tx, float Ty, float Tz, bool LightYN) private
Definition at line 755 of file SceneEnd.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderToolIcon(), and ToolSelectionMouseScroll().
void SceneEnd::RenderMouseScrollToolSlot () private
Definition at line 349 of file SceneEnd.cpp.
References GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, Explorer::instance(), meshList, and RenderModelOnScreen().
Referenced by Render().
void SceneEnd::RenderPlayerDiesInteraction () private
Definition at line 98 of file SceneEndRenders.cpp.
References GlobalVariables::f_redScreenTimer, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_TEXT, Explorer::instance(), meshList, RenderModelOnScreen(), RenderTextOnScreen(), and Scene::Variables.
Referenced by Render().
void SceneEnd::RenderRepairText () private
Definition at line 222 of file SceneEndRenders.cpp.
References b_RepairDone, b_startRepair, camera, f_RepairProcess, GEO_TEXT, ToolUI::Hand, Explorer::instance(), meshList, Camera::position, RenderTextOnScreen(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneEnd::RenderSceneEnd () private
Definition at line 84 of file SceneEndRenders.cpp.
References GEO_FACILITYOUT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEnd::RenderShipAndPod () private
Definition at line 132 of file SceneEndRenders.cpp.
References b_RepairDone, GEO_REPAIRDONE, GEO_REPAIRPOD, GEO_SPACESHIP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEnd::RenderSkyBox () private
Definition at line 7 of file SceneEndRenders.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and worldspin.
Referenced by Render().
void SceneEnd::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 679 of file SceneEnd.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneEnd::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 709 of file SceneEnd.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderMineText(), RenderPlayerDiesInteraction(), and RenderRepairText().
void SceneEnd::RenderToolIcon () private
Definition at line 400 of file SceneEnd.cpp.
References ToolUI::BaseballBat, GEO_BATICON, GEO_HANDICON, GEO_PICKAXEICON, GEO_SWORDICON, ToolUI::Hand, Explorer::instance(), meshList, ToolUI::Pickaxe, RenderModelOnScreen(), and ToolUI::Sword.
Referenced by Render().
void SceneEnd::Reset () virtual
Definition at line 244 of file SceneEnd.cpp.
References Explorer::checkSavePoint, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Explorer::PlayerLife, Explorer::SavePoint, and Scene::Variables.
Referenced by ContinueGameOrNot(), and Update().
void SceneEnd::ResetMobs () private
Definition at line 527 of file SceneEndRenders.cpp.
References BossMS, BossOne, HostileMob::health, MobMS, MobOne, MobThree, MobTwo, MobBossOne::setSpawnBossOne(), MobGhost::setSpawnGhost(), and waveCounter.
Referenced by MobCheck().
void SceneEnd::ToolSelectionMouseScroll () private
Definition at line 367 of file SceneEnd.cpp.
References ToolUI::BaseballBat, GEO_BAT, GEO_LHAND, GEO_PICKAXE, GEO_RHAND, GEO_SWORD, ToolUI::Hand, Explorer::instance(), meshList, modelStack, ToolUI::Pickaxe, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), GlobalVariables::RotateX, ToolUI::Sword, and Scene::Variables.
Referenced by Render().
void SceneEnd::Update (double dt) virtual
Implements Scene.
Definition at line 544 of file SceneEnd.cpp.
References b_ReadyToFly(), b_RepairDone, b_startRepair, BossOne, camera, Explorer::checkDead(), HostileMob::checkPlayerPos(), Collision(), ContinueGameOrNot(), Application::EndingCutScene(), f_rockY, FPS, Explorer::InsertToolSlot(), Explorer::instance(), Application::IsKeyPressed(), light, MobCheck(), MobOne, MobThree, MobTwo, MouseClickFunction(), MouseScrollToolSlot(), moveMob(), Application::OpenGame(), ToolUI::Pickaxe, Light::position, Camera::position, Reset(), Position::Set(), Vector3::Set(), Light::spotDirection, Camera::target, Camera3::Update(), UpdatePlayerDiesInteraction(), UpdateRepairs(), worldspin, Vector3::x, Vector3::y, and Vector3::z.
void SceneEnd::UpdatePlayerDiesInteraction (double dt) private
Definition at line 283 of file SceneEnd.cpp.
References GlobalVariables::f_redScreenTimer, Explorer::instance(), light, m_parameters, Light::power, U_LIGHT0_POWER, and Scene::Variables.
Referenced by Update().
void SceneEnd::UpdateRepairs (double dt) private
Definition at line 495 of file SceneEnd.cpp.
References b_RepairDone, b_startRepair, camera, f_RepairProcess, Explorer::GetToolType(), ToolUI::Hand, Explorer::instance(), Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
Field Documentation
Animation SceneEnd::anima private
Definition at line 193 of file SceneEnd.h.
bool SceneEnd::b_RepairDone[3] private
Definition at line 158 of file SceneEnd.h.
Referenced by b_ReadyToFly(), ContinueGameOrNot(), Render(), RenderMineText(), RenderRepairText(), RenderShipAndPod(), SceneEnd(), Update(), and UpdateRepairs().
bool SceneEnd::b_startRepair[3] private
Definition at line 159 of file SceneEnd.h.
Referenced by ContinueGameOrNot(), RenderMineText(), RenderRepairText(), SceneEnd(), Update(), and UpdateRepairs().
int SceneEnd::BossMS private
Definition at line 231 of file SceneEnd.h.
Referenced by moveMob(), ResetMobs(), and SceneEnd().
MobBossOne SceneEnd::BossOne private
Definition at line 217 of file SceneEnd.h.
Referenced by checkAttack(), Init(), MobCheck(), moveMob(), Render(), RenderBoss(), ResetMobs(), and Update().
Camera3 SceneEnd::camera
Definition at line 127 of file SceneEnd.h.
Referenced by checkAttack(), Collision(), ContinueGameOrNot(), Init(), proximitycheck(), Render(), RenderBoss(), RenderMineText(), RenderMobs(), RenderRepairText(), Update(), and UpdateRepairs().
bool SceneEnd::CrosshairHit private
Definition at line 233 of file SceneEnd.h.
Referenced by checkAttack(), MouseClickFunction(), Render(), and SceneEnd().
Vector3 SceneEnd::end private
Definition at line 209 of file SceneEnd.h.
float SceneEnd::f_RepairProcess private
Definition at line 161 of file SceneEnd.h.
Referenced by ContinueGameOrNot(), RenderRepairText(), SceneEnd(), and UpdateRepairs().
float SceneEnd::f_rockY private
Definition at line 168 of file SceneEnd.h.
Referenced by ContinueGameOrNot(), Render(), SceneEnd(), and Update().
float SceneEnd::FPS private
Definition at line 211 of file SceneEnd.h.
Referenced by Render(), and Update().
int SceneEnd::killCounter private
Definition at line 220 of file SceneEnd.h.
Referenced by SceneEnd().
Light SceneEnd::light[1] private
Definition at line 197 of file SceneEnd.h.
Referenced by Init(), Render(), Update(), and UpdatePlayerDiesInteraction().
unsigned SceneEnd::m_parameters[U_TOTAL] private
Definition at line 191 of file SceneEnd.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and UpdatePlayerDiesInteraction().
unsigned SceneEnd::m_programID private
Definition at line 190 of file SceneEnd.h.
Referenced by Exit(), and Init().
unsigned SceneEnd::m_vertexArrayID private
Definition at line 187 of file SceneEnd.h.
Referenced by Exit(), and Init().
Mesh* SceneEnd::meshList[NUM_GEOMETRY] private
Definition at line 188 of file SceneEnd.h.
Referenced by Init(), Render(), RenderBoss(), RenderDownWall(), RenderFloor(), RenderMineText(), RenderMobs(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderRepairText(), RenderSceneEnd(), RenderShipAndPod(), RenderSkyBox(), RenderToolIcon(), and ToolSelectionMouseScroll().
int SceneEnd::MobMS private
Definition at line 230 of file SceneEnd.h.
Referenced by moveMob(), ResetMobs(), and SceneEnd().
MobGhost SceneEnd::MobOne private
Definition at line 214 of file SceneEnd.h.
Referenced by checkAttack(), Init(), MobCheck(), moveMob(), Render(), ResetMobs(), and Update().
MobGhost SceneEnd::MobThree private
Definition at line 216 of file SceneEnd.h.
Referenced by checkAttack(), Init(), MobCheck(), moveMob(), Render(), ResetMobs(), and Update().
MobGhost SceneEnd::MobTwo private
Definition at line 215 of file SceneEnd.h.
Referenced by checkAttack(), Init(), MobCheck(), moveMob(), Render(), ResetMobs(), and Update().
MS SceneEnd::modelStack private
Definition at line 195 of file SceneEnd.h.
Referenced by Render(), RenderBoss(), RenderDownWall(), RenderFloor(), RenderMesh(), RenderMobs(), RenderModelOnScreen(), RenderSceneEnd(), RenderShipAndPod(), RenderSkyBox(), RenderText(), RenderTextOnScreen(), and ToolSelectionMouseScroll().
MS SceneEnd::projectionStack private
Definition at line 195 of file SceneEnd.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
bool SceneEnd::spawnWaveOne =false private
Definition at line 219 of file SceneEnd.h.
Referenced by SceneEnd().
Vector3 SceneEnd::start private
Definition at line 208 of file SceneEnd.h.
MS SceneEnd::viewStack private
Definition at line 195 of file SceneEnd.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
int SceneEnd::waveCounter private
Definition at line 221 of file SceneEnd.h.
Referenced by ResetMobs(), and SceneEnd().
float SceneEnd::worldspin private
Definition at line 205 of file SceneEnd.h.
Referenced by RenderSkyBox(), and Update().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneEnd.h
ComGraphics/Source/MapRender.cpp
ComGraphics/Source/SceneEnd.cpp
ComGraphics/Source/SceneEndRenders.cpp