My Application: Explorer Class Reference
Explorer Class Reference
#include <Explorer.h>
Public Member Functions
virtual void setHP (float currHP)
virtual void setStamina (float currStam)
virtual float getHP ()
virtual float MinusHP (float TakeDamage)
virtual float getStamina ()
ToolUI::ToolType GetToolType (int SlotNumber)
void InsertToolSlot (ToolUI::ToolType ChooseTools)
bool CheckForDoubleTool (ToolUI::ToolType DoubleTool)
void checkDead ()
Static Public Member Functions
static Explorer * instance ()
Data Fields
float stamina
float hp
float f_hpBarScaleX
int i_SlotIndex
int itemAttack [4]
std::list< ToolUI > TotalTools
bool b_PickUpTool [3]
int i_SuitcaseCount
bool b_pickUpSuitCase [5]
unsigned int PlayerLife
bool isDead
bool checkSavePoint [4]
Vector3 SavePoint
float f_FlickeringLight
Private Member Functions
Explorer ()
Detailed Description
Definition at line 7 of file Explorer.h.
Constructor & Destructor Documentation
Explorer::Explorer () private
Definition at line 3 of file Explorer.cpp.
References b_pickUpSuitCase, b_PickUpTool, checkSavePoint, ToolUI::Empty, f_FlickeringLight, f_hpBarScaleX, ToolUI::Hand, hp, i_SlotIndex, i_SuitcaseCount, instance(), isDead, itemAttack, PlayerLife, SavePoint, stamina, and TotalTools.
Member Function Documentation
void Explorer::checkDead ()
Definition at line 64 of file Explorer.cpp.
References hp, instance(), and isDead.
Referenced by Camera3::Update(), SceneStart::Update(), SceneLevelTwo::Update(), SceneLevelOneA::Update(), SceneEnd::Update(), and SceneLevelOneB::Update().
bool Explorer::CheckForDoubleTool (ToolUI::ToolType DoubleTool)
Definition at line 102 of file Explorer.cpp.
References TotalTools.
Referenced by InsertToolSlot().
float Explorer::getHP () virtual
Definition at line 47 of file Explorer.cpp.
References hp, and instance().
float Explorer::getStamina () virtual
Definition at line 72 of file Explorer.cpp.
References instance(), and stamina.
ToolUI::ToolType Explorer::GetToolType (int SlotNumber)
Definition at line 115 of file Explorer.cpp.
References ToolUI::BaseballBat, ToolUI::Empty, ToolUI::Hand, instance(), itemAttack, ToolUI::Pickaxe, ToolUI::Sword, and TotalTools.
Referenced by SceneEnd::UpdateRepairs().
void Explorer::InsertToolSlot (ToolUI::ToolType ChooseTools)
Definition at line 87 of file Explorer.cpp.
References CheckForDoubleTool(), ToolUI::Empty, and TotalTools.
Referenced by SceneLevelOneA::ToolsUI(), SceneLevelOneB::ToolsUI(), SceneLevelTwo::Update(), and SceneEnd::Update().
static Explorer* Explorer::instance () inline static
Definition at line 10 of file Explorer.h.
Referenced by MobBossOne::attack(), MobGhost::attack(), SceneLevelOneB::attackCheck(), SceneLevelOneA::AttackCheck(), SceneEnd::checkAttack(), checkDead(), SceneLevelTwo::ContinueGameOrNot(), SceneEnd::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), Explorer(), getHP(), getStamina(), GetToolType(), Camera3::HumanControl(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneLevelOneB::Init(), MinusHP(), SceneStart::MouseClickFunction(), SceneLevelTwo::MouseClickFunction(), SceneLevelOneA::MouseClickFunction(), SceneEnd::MouseClickFunction(), SceneLevelOneB::MouseClickFunction(), SceneStart::MouseScrollToolSlot(), SceneLevelTwo::MouseScrollToolSlot(), SceneLevelOneA::MouseScrollToolSlot(), SceneEnd::MouseScrollToolSlot(), SceneLevelOneB::MouseScrollToolSlot(), SceneLevelOneA::PickUpSuitcaseInteraction(), SceneLevelOneB::PickUpSuitcaseInteraction(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), SceneEnd::RenderMineText(), SceneStart::RenderMouseScrollToolSlot(), SceneLevelTwo::RenderMouseScrollToolSlot(), SceneLevelOneA::RenderMouseScrollToolSlot(), SceneEnd::RenderMouseScrollToolSlot(), SceneLevelOneB::RenderMouseScrollToolSlot(), SceneLevelOneA::RenderPickUpPickAxe(), SceneLevelOneB::RenderPickUpPickTools(), SceneLevelOneB::RenderPickUpSuitcaseText(), SceneLevelOneA::RenderPickUpSuitcaseText(), SceneLevelTwo::RenderPlayerDiesInteraction(), SceneEnd::RenderPlayerDiesInteraction(), SceneLevelOneA::RenderPlayerDiesInteraction(), SceneLevelOneB::RenderPlayerDiesInteraction(), SceneEnd::RenderRepairText(), SceneLevelOneB::RenderScene(), SceneLevelOneA::RenderSuitCase(), SceneStart::RenderToolIcon(), SceneLevelTwo::RenderToolIcon(), SceneLevelOneA::RenderToolIcon(), SceneEnd::RenderToolIcon(), SceneLevelOneB::RenderToolIcon(), SceneLevelTwo::Reset(), SceneEnd::Reset(), SceneLevelTwo::ResetAll(), SceneLevelOneA::ResetAll(), SceneLevelOneB::ResetAll(), SceneLevelOneA::ResetSameScene(), SceneLevelOneB::ResetSameScene(), setHP(), setStamina(), SceneLevelTwo::SomeUpdates(), SceneStart::ToolSelectionMouseScroll(), SceneLevelTwo::ToolSelectionMouseScroll(), SceneLevelOneA::ToolSelectionMouseScroll(), SceneEnd::ToolSelectionMouseScroll(), SceneLevelOneB::ToolSelectionMouseScroll(), SceneLevelOneA::ToolsUI(), SceneLevelOneB::ToolsUI(), Camera3::Update(), SceneStart::Update(), SceneLevelTwo::Update(), SceneLevelOneA::Update(), SceneEnd::Update(), SceneLevelOneB::Update(), SceneLevelTwo::UpdatePlayerDiesInteraction(), SceneEnd::UpdatePlayerDiesInteraction(), SceneLevelOneB::UpdatePlayerDiesInteraction(), SceneLevelOneA::UpdatePlayerDiesInteraction(), and SceneEnd::UpdateRepairs().
float Explorer::MinusHP (float TakeDamage) virtual
Definition at line 52 of file Explorer.cpp.
References hp, and instance().
Referenced by MobBossOne::attack(), and MobGhost::attack().
void Explorer::setHP (float currHP) virtual
Definition at line 77 of file Explorer.cpp.
References hp, and instance().
void Explorer::setStamina (float currStam) virtual
Definition at line 82 of file Explorer.cpp.
References instance(), and stamina.
Field Documentation
bool Explorer::b_pickUpSuitCase[5]
Definition at line 33 of file Explorer.h.
Referenced by Explorer(), SceneLevelOneB::PickUpSuitcaseInteraction(), and SceneLevelOneA::PickUpSuitcaseInteraction().
bool Explorer::b_PickUpTool[3]
Definition at line 30 of file Explorer.h.
Referenced by Explorer(), SceneLevelOneA::ToolsUI(), and SceneLevelOneB::ToolsUI().
bool Explorer::checkSavePoint[4]
Definition at line 37 of file Explorer.h.
Referenced by Explorer(), SceneLevelTwo::Reset(), SceneEnd::Reset(), SceneLevelTwo::ResetAll(), SceneLevelOneA::ResetAll(), SceneLevelOneB::ResetAll(), SceneLevelOneA::ResetSameScene(), and SceneLevelOneB::ResetSameScene().
float Explorer::f_FlickeringLight
Definition at line 42 of file Explorer.h.
Referenced by Explorer(), and SceneLevelTwo::Update().
float Explorer::f_hpBarScaleX
Definition at line 20 of file Explorer.h.
Referenced by Explorer().
float Explorer::hp
Definition at line 19 of file Explorer.h.
Referenced by checkDead(), SceneLevelTwo::ContinueGameOrNot(), SceneEnd::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), Explorer(), getHP(), MinusHP(), SceneLevelTwo::Reset(), SceneEnd::Reset(), SceneLevelTwo::ResetAll(), SceneLevelOneA::ResetAll(), SceneLevelOneB::ResetAll(), SceneLevelOneA::ResetSameScene(), SceneLevelOneB::ResetSameScene(), setHP(), and SceneLevelOneA::Update().
int Explorer::i_SlotIndex
Definition at line 22 of file Explorer.h.
Referenced by Explorer(), SceneStart::MouseScrollToolSlot(), SceneLevelTwo::MouseScrollToolSlot(), SceneLevelOneA::MouseScrollToolSlot(), SceneEnd::MouseScrollToolSlot(), and SceneLevelOneB::MouseScrollToolSlot().
int Explorer::i_SuitcaseCount
Definition at line 32 of file Explorer.h.
Referenced by Explorer(), SceneLevelOneB::PickUpSuitcaseInteraction(), and SceneLevelOneA::PickUpSuitcaseInteraction().
bool Explorer::isDead
Definition at line 36 of file Explorer.h.
Referenced by checkDead(), SceneLevelTwo::ContinueGameOrNot(), SceneEnd::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), Explorer(), Camera3::HumanControl(), SceneLevelTwo::Reset(), SceneEnd::Reset(), SceneLevelTwo::ResetAll(), SceneLevelOneA::ResetAll(), SceneLevelOneB::ResetAll(), SceneLevelOneA::ResetSameScene(), SceneLevelOneB::ResetSameScene(), and SceneLevelTwo::SomeUpdates().
int Explorer::itemAttack[4]
Definition at line 24 of file Explorer.h.
Referenced by Explorer(), and GetToolType().
unsigned int Explorer::PlayerLife
Definition at line 35 of file Explorer.h.
Referenced by SceneLevelTwo::ContinueGameOrNot(), SceneEnd::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), Explorer(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), SceneEnd::Reset(), SceneLevelTwo::ResetAll(), SceneLevelOneA::ResetAll(), SceneLevelOneB::ResetAll(), and SceneLevelOneA::ResetSameScene().
Vector3 Explorer::SavePoint
Definition at line 40 of file Explorer.h.
Referenced by SceneLevelTwo::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), Explorer(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneLevelOneB::Init(), SceneLevelTwo::Reset(), SceneEnd::Reset(), SceneLevelTwo::ResetAll(), SceneLevelOneA::ResetAll(), SceneLevelOneB::ResetAll(), SceneLevelOneA::ResetSameScene(), and SceneLevelOneB::ResetSameScene().
float Explorer::stamina
Definition at line 18 of file Explorer.h.
Referenced by Explorer(), getStamina(), Camera3::HumanControl(), SceneStart::MouseClickFunction(), SceneLevelTwo::MouseClickFunction(), SceneLevelOneA::MouseClickFunction(), SceneEnd::MouseClickFunction(), SceneLevelOneB::MouseClickFunction(), SceneLevelTwo::Reset(), setStamina(), and Camera3::Update().
std::list<ToolUI> Explorer::TotalTools
Definition at line 29 of file Explorer.h.
Referenced by CheckForDoubleTool(), Explorer(), GetToolType(), and InsertToolSlot().
The documentation for this class was generated from the following files:
ComGraphics/Source/Explorer.h
ComGraphics/Source/Explorer.cpp