My Application: SceneEndCutScene Class Reference
SceneEndCutScene Class Reference
#include <SceneEndCutScene.h>
Public Member Functions
SceneEndCutScene ()
~SceneEndCutScene ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
vector< string > ReadFromText (string link)
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
vector< string > readText
vector< string > TestYou
vector< string >::iterator its = readText.begin()
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_EARTH,
GEO_MOON, GEO_PLANET, GEO_ASTEROID1, GEO_ASTEROID2,
GEO_MAINDOORLEFT, GEO_MAINDOORRIGHT, GEO_RUBBLE, GEO_PORTRAIT,
GEO_PLANETFLOOR, GEO_FACILITYFLOOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL,
GEO_FACILITYWALLS, GEO_FACILITYCEILINGS, GEO_DEADCOLOR, GEO_DEADBLACKSCREEN,
GEO_SPACESHIP, GEO_REPAIRPOD, GEO_REPAIRDONE, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderLevel1 ()
void RenderFloor ()
void RenderSkyBox ()
void RenderSceneEndCutScene (vector< string > Test)
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float Tx, float Ty, float Tz, bool LightYN)
void RenderShipAndPod ()
void RenderRepairText ()
void UpdateRepairs (double dt)
Private Attributes
bool b_RepairDone [3]
bool b_startRepair
float f_RepairProcess
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
float worldspin
Vector3 start
Vector3 end
GlobalVariables Variables
float FPS
bool displayInteract
float MoveCamera1
float MoveCamera2
bool CameraMove1
bool CameraMove2
float MoveQuad
bool QuadMove
Detailed Description
Definition at line 18 of file SceneEndCutScene.h.
Member Enumeration Documentation
enum SceneEndCutScene::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_EARTH
GEO_MOON
GEO_PLANET
GEO_ASTEROID1
GEO_ASTEROID2
GEO_MAINDOORLEFT
GEO_MAINDOORRIGHT
GEO_RUBBLE
GEO_PORTRAIT
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_DEADCOLOR
GEO_DEADBLACKSCREEN
GEO_SPACESHIP
GEO_REPAIRPOD
GEO_REPAIRDONE
NUM_GEOMETRY
Definition at line 20 of file SceneEndCutScene.h.
enum SceneEndCutScene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 64 of file SceneEndCutScene.h.
Constructor & Destructor Documentation
SceneEndCutScene::SceneEndCutScene ()
Definition at line 16 of file SceneEndCutScene.cpp.
References CameraMove1, CameraMove2, MoveQuad, and QuadMove.
SceneEndCutScene::~SceneEndCutScene ()
Definition at line 25 of file SceneEndCutScene.cpp.
Member Function Documentation
void SceneEndCutScene::Exit () virtual
Implements Scene.
Definition at line 443 of file SceneEndCutScene.cpp.
References m_programID, and m_vertexArrayID.
void SceneEndCutScene::Init () virtual
Implements Scene.
Definition at line 29 of file SceneEndCutScene.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), MeshBuilder::GenerateTorus(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FRONT, GEO_LEFT, GEO_LIGHTBALL, GEO_PLANETFLOOR, GEO_QUAD, GEO_REPAIRDONE, GEO_REPAIRPOD, GEO_RIGHT, GEO_SPACESHIP, GEO_TEXT, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
vector< string > SceneEndCutScene::ReadFromText (string link)
Definition at line 167 of file SceneEndCutScene.cpp.
References readText.
void SceneEndCutScene::Render () virtual
Implements Scene.
Definition at line 395 of file SceneEndCutScene.cpp.
References camera, GEO_QUAD, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MoveCamera1, MoveCamera2, MoveQuad, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderFloor(), RenderModelOnScreen(), RenderSceneEndCutScene(), RenderShipAndPod(), RenderSkyBox(), MS::Rotate(), Light::spotDirection, Camera::target, TestYou, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneEndCutScene::RenderFloor () private
Definition at line 325 of file SceneEndRenders.cpp.
References GEO_PLANETFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEndCutScene::RenderLevel1 () private
void SceneEndCutScene::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 254 of file SceneEndCutScene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderFloor(), RenderModelOnScreen(), RenderSceneEndCutScene(), RenderShipAndPod(), and RenderSkyBox().
void SceneEndCutScene::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float Tx, float Ty, float Tz, bool LightYN) private
Definition at line 374 of file SceneEndCutScene.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneEndCutScene::RenderRepairText () private
void SceneEndCutScene::RenderSceneEndCutScene (vector< string > Test) private
Definition at line 340 of file SceneEndRenders.cpp.
References GEO_FACILITYOUT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEndCutScene::RenderShipAndPod () private
Definition at line 353 of file SceneEndRenders.cpp.
References anima, GEO_SPACESHIP, meshList, modelStack, Animation::MovingShip, Animation::MovingShip2, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneEndCutScene::RenderSkyBox () private
Definition at line 264 of file SceneEndRenders.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and worldspin.
Referenced by Render().
void SceneEndCutScene::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 298 of file SceneEndCutScene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneEndCutScene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 328 of file SceneEndCutScene.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneEndCutScene::Reset () virtual
Definition at line 163 of file SceneEndCutScene.cpp.
void SceneEndCutScene::Update (double dt) virtual
Implements Scene.
Definition at line 192 of file SceneEndCutScene.cpp.
References anima, camera, CameraMove1, CameraMove2, Application::End_Credits(), FPS, Application::IsKeyPressed(), light, MoveCamera1, MoveCamera2, MoveQuad, Animation::MovingShip, Animation::MovingShip2, Light::position, Camera::position, QuadMove, Position::Set(), Vector3::Set(), Animation::shipCheck1, Animation::shipCheck2, Animation::ShipTakeOff(), Light::spotDirection, Camera::target, worldspin, Vector3::x, Vector3::y, and Vector3::z.
void SceneEndCutScene::UpdateRepairs (double dt) private
Field Documentation
Animation SceneEndCutScene::anima private
Definition at line 139 of file SceneEndCutScene.h.
Referenced by RenderShipAndPod(), and Update().
bool SceneEndCutScene::b_RepairDone[3] private
Definition at line 125 of file SceneEndCutScene.h.
bool SceneEndCutScene::b_startRepair private
Definition at line 126 of file SceneEndCutScene.h.
Camera3 SceneEndCutScene::camera
Definition at line 104 of file SceneEndCutScene.h.
Referenced by Init(), Render(), and Update().
bool SceneEndCutScene::CameraMove1 private
Definition at line 163 of file SceneEndCutScene.h.
Referenced by SceneEndCutScene(), and Update().
bool SceneEndCutScene::CameraMove2 private
Definition at line 164 of file SceneEndCutScene.h.
Referenced by SceneEndCutScene(), and Update().
bool SceneEndCutScene::displayInteract private
Definition at line 159 of file SceneEndCutScene.h.
Vector3 SceneEndCutScene::end private
Definition at line 155 of file SceneEndCutScene.h.
float SceneEndCutScene::f_RepairProcess private
Definition at line 127 of file SceneEndCutScene.h.
float SceneEndCutScene::FPS private
Definition at line 158 of file SceneEndCutScene.h.
Referenced by Update().
vector<string>::iterator SceneEndCutScene::its = readText.begin()
Definition at line 109 of file SceneEndCutScene.h.
Light SceneEndCutScene::light[1] private
Definition at line 143 of file SceneEndCutScene.h.
Referenced by Init(), Render(), and Update().
unsigned SceneEndCutScene::m_parameters[U_TOTAL] private
Definition at line 137 of file SceneEndCutScene.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SceneEndCutScene::m_programID private
Definition at line 136 of file SceneEndCutScene.h.
Referenced by Exit(), and Init().
unsigned SceneEndCutScene::m_vertexArrayID private
Definition at line 133 of file SceneEndCutScene.h.
Referenced by Exit(), and Init().
Mesh* SceneEndCutScene::meshList[NUM_GEOMETRY] private
Definition at line 134 of file SceneEndCutScene.h.
Referenced by Init(), Render(), RenderFloor(), RenderSceneEndCutScene(), RenderShipAndPod(), and RenderSkyBox().
MS SceneEndCutScene::modelStack private
Definition at line 141 of file SceneEndCutScene.h.
Referenced by Render(), RenderFloor(), RenderMesh(), RenderModelOnScreen(), RenderSceneEndCutScene(), RenderShipAndPod(), RenderSkyBox(), RenderText(), and RenderTextOnScreen().
float SceneEndCutScene::MoveCamera1 private
Definition at line 161 of file SceneEndCutScene.h.
Referenced by Render(), and Update().
float SceneEndCutScene::MoveCamera2 private
Definition at line 162 of file SceneEndCutScene.h.
Referenced by Render(), and Update().
float SceneEndCutScene::MoveQuad private
Definition at line 166 of file SceneEndCutScene.h.
Referenced by Render(), SceneEndCutScene(), and Update().
MS SceneEndCutScene::projectionStack private
Definition at line 141 of file SceneEndCutScene.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
bool SceneEndCutScene::QuadMove private
Definition at line 167 of file SceneEndCutScene.h.
Referenced by SceneEndCutScene(), and Update().
vector<string> SceneEndCutScene::readText
Definition at line 106 of file SceneEndCutScene.h.
Referenced by ReadFromText().
Vector3 SceneEndCutScene::start private
Definition at line 154 of file SceneEndCutScene.h.
vector<string> SceneEndCutScene::TestYou
Definition at line 108 of file SceneEndCutScene.h.
Referenced by Render().
GlobalVariables SceneEndCutScene::Variables private
Definition at line 156 of file SceneEndCutScene.h.
MS SceneEndCutScene::viewStack private
Definition at line 141 of file SceneEndCutScene.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
float SceneEndCutScene::worldspin private
Definition at line 151 of file SceneEndCutScene.h.
Referenced by RenderSkyBox(), and Update().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneEndCutScene.h
ComGraphics/Source/SceneEndCutScene.cpp
ComGraphics/Source/SceneEndRenders.cpp