My Application: OpeningCutScene2 Class Reference
OpeningCutScene2 Class Reference
#include <OpeningCutScene2.h>
Public Member Functions
OpeningCutScene2 ()
~OpeningCutScene2 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_PLANETFLOOR,
GEO_FACILITYFLOOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FACILITYWALLS,
GEO_FACILITYCEILINGS, GEO_DEADBODY, GEO_BLOOD1, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSceneStart ()
void RenderSkyBox ()
void RenderFloor ()
void RenderDownWall (int xPosLarge, int xPosSmall, int zPos)
void RenderUpWall (int xPosLarge, int xPosSmall, int zPos)
void RenderRightWall (int zPosLarge, int zPosSmall, int xPos)
void RenderLeftWall (int zPosLarge, int zPosSmall, int xPos)
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void RenderTextWord ()
void ChangeFirstCutScene ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
misc Misc
bool rotateCamX = false
float MoveCamera1
bool camera_check1 = true
bool camera_check2 = false
bool camera_check3 = false
bool rotateCamY = false
float RotateCamera
bool wokeUp = true
bool check1 = true
bool check2 = false
bool check3 = false
float eyeOpening
bool text1 = false
bool text2 = false
Detailed Description
Definition at line 15 of file OpeningCutScene2.h.
Member Enumeration Documentation
enum OpeningCutScene2::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_DEADBODY
GEO_BLOOD1
NUM_GEOMETRY
Definition at line 17 of file OpeningCutScene2.h.
enum OpeningCutScene2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 47 of file OpeningCutScene2.h.
Constructor & Destructor Documentation
OpeningCutScene2::OpeningCutScene2 ()
Definition at line 14 of file OpeningCutScene2.cpp.
OpeningCutScene2::~OpeningCutScene2 ()
Definition at line 18 of file OpeningCutScene2.cpp.
Member Function Documentation
void OpeningCutScene2::ChangeFirstCutScene () private
void OpeningCutScene2::Exit () virtual
Implements Scene.
Definition at line 477 of file OpeningCutScene2.cpp.
References m_programID, and m_vertexArrayID.
void OpeningCutScene2::Init () virtual
Implements Scene.
Definition at line 22 of file OpeningCutScene2.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_DEADBODY, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FRONT, GEO_LEFT, GEO_LIGHTBALL, GEO_PLANETFLOOR, GEO_QUAD, GEO_RIGHT, GEO_TEXT, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void OpeningCutScene2::Render () virtual
Implements Scene.
Definition at line 418 of file OpeningCutScene2.cpp.
References camera, eyeOpening, GEO_DEADBODY, GEO_QUAD, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MoveCamera1, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderMesh(), RenderModelOnScreen(), RenderSceneStart(), RenderTextWord(), MS::Rotate(), RotateCamera, MS::Scale(), Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void OpeningCutScene2::RenderDownWall (int xPosLarge, int xPosSmall, int zPos) private
void OpeningCutScene2::RenderFloor () private
Definition at line 220 of file SceneStartRenders.cpp.
References GEO_PLANETFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by RenderSceneStart().
void OpeningCutScene2::RenderLeftWall (int zPosLarge, int zPosSmall, int xPos) private
void OpeningCutScene2::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 261 of file OpeningCutScene2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderFloor(), RenderModelOnScreen(), RenderSceneStart(), and RenderSkyBox().
void OpeningCutScene2::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 381 of file OpeningCutScene2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void OpeningCutScene2::RenderRightWall (int zPosLarge, int zPosSmall, int xPos) private
void OpeningCutScene2::RenderSceneStart () private
Definition at line 239 of file SceneStartRenders.cpp.
References GEO_FACILITYOUT, GEO_FACILITYOUTWALL, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderFloor(), RenderMesh(), RenderSkyBox(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void OpeningCutScene2::RenderSkyBox () private
Definition at line 159 of file SceneStartRenders.cpp.
References GlobalVariables::f_Worldspin, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and Scene::Variables.
Referenced by RenderSceneStart().
void OpeningCutScene2::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 305 of file OpeningCutScene2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void OpeningCutScene2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 335 of file OpeningCutScene2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderTextWord().
void OpeningCutScene2::RenderTextWord () private
Definition at line 402 of file OpeningCutScene2.cpp.
References GEO_TEXT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderTextOnScreen(), text1, and text2.
Referenced by Render().
void OpeningCutScene2::RenderUpWall (int xPosLarge, int xPosSmall, int zPos) private
void OpeningCutScene2::Reset () virtual
Definition at line 145 of file OpeningCutScene2.cpp.
void OpeningCutScene2::Update (double dt) virtual
Implements Scene.
Definition at line 151 of file OpeningCutScene2.cpp.
References camera, camera_check1, camera_check2, camera_check3, check1, check2, check3, eyeOpening, GlobalVariables::f_Worldspin, Application::IsKeyPressed(), light, MoveCamera1, Light::position, Camera::position, RotateCamera, rotateCamX, rotateCamY, Position::Set(), Vector3::Set(), Light::spotDirection, Application::StartingScene(), Camera::target, text1, text2, Scene::Variables, wokeUp, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Animation OpeningCutScene2::anima private
Definition at line 117 of file OpeningCutScene2.h.
Camera3 OpeningCutScene2::camera
Definition at line 87 of file OpeningCutScene2.h.
Referenced by Init(), Render(), and Update().
bool OpeningCutScene2::camera_check1 = true private
Definition at line 133 of file OpeningCutScene2.h.
Referenced by Update().
bool OpeningCutScene2::camera_check2 = false private
Definition at line 134 of file OpeningCutScene2.h.
Referenced by Update().
bool OpeningCutScene2::camera_check3 = false private
Definition at line 135 of file OpeningCutScene2.h.
Referenced by Update().
bool OpeningCutScene2::check1 = true private
Definition at line 141 of file OpeningCutScene2.h.
Referenced by Update().
bool OpeningCutScene2::check2 = false private
Definition at line 142 of file OpeningCutScene2.h.
Referenced by Update().
bool OpeningCutScene2::check3 = false private
Definition at line 143 of file OpeningCutScene2.h.
Referenced by Update().
Vector3 OpeningCutScene2::end private
Definition at line 127 of file OpeningCutScene2.h.
float OpeningCutScene2::eyeOpening private
Definition at line 144 of file OpeningCutScene2.h.
Referenced by Render(), and Update().
Light OpeningCutScene2::light[1] private
Definition at line 121 of file OpeningCutScene2.h.
Referenced by Init(), Render(), and Update().
unsigned OpeningCutScene2::m_parameters[U_TOTAL] private
Definition at line 115 of file OpeningCutScene2.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned OpeningCutScene2::m_programID private
Definition at line 114 of file OpeningCutScene2.h.
Referenced by Exit(), and Init().
unsigned OpeningCutScene2::m_vertexArrayID private
Definition at line 111 of file OpeningCutScene2.h.
Referenced by Exit(), and Init().
Mesh* OpeningCutScene2::meshList[NUM_GEOMETRY] private
Definition at line 112 of file OpeningCutScene2.h.
Referenced by Init(), Render(), RenderFloor(), RenderSceneStart(), RenderSkyBox(), and RenderTextWord().
misc OpeningCutScene2::Misc private
Definition at line 129 of file OpeningCutScene2.h.
MS OpeningCutScene2::modelStack private
Definition at line 119 of file OpeningCutScene2.h.
Referenced by Render(), RenderFloor(), RenderMesh(), RenderModelOnScreen(), RenderSceneStart(), RenderSkyBox(), RenderText(), RenderTextOnScreen(), and RenderTextWord().
float OpeningCutScene2::MoveCamera1 private
Definition at line 132 of file OpeningCutScene2.h.
Referenced by Render(), and Update().
MS OpeningCutScene2::projectionStack private
Definition at line 119 of file OpeningCutScene2.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
float OpeningCutScene2::RotateCamera private
Definition at line 138 of file OpeningCutScene2.h.
Referenced by Render(), and Update().
bool OpeningCutScene2::rotateCamX = false private
Definition at line 131 of file OpeningCutScene2.h.
Referenced by Update().
bool OpeningCutScene2::rotateCamY = false private
Definition at line 137 of file OpeningCutScene2.h.
Referenced by Update().
Vector3 OpeningCutScene2::start private
Definition at line 126 of file OpeningCutScene2.h.
bool OpeningCutScene2::text1 = false private
Definition at line 146 of file OpeningCutScene2.h.
Referenced by RenderTextWord(), and Update().
bool OpeningCutScene2::text2 = false private
Definition at line 147 of file OpeningCutScene2.h.
Referenced by RenderTextWord(), and Update().
MS OpeningCutScene2::viewStack private
Definition at line 119 of file OpeningCutScene2.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
bool OpeningCutScene2::wokeUp = true private
Definition at line 140 of file OpeningCutScene2.h.
Referenced by Update().
The documentation for this class was generated from the following files:
ComGraphics/Source/OpeningCutScene2.h
ComGraphics/Source/OpeningCutScene2.cpp
ComGraphics/Source/SceneStartRenders.cpp