My Application: Mtx44 Class Reference
Mtx44 Class Reference
A 4 by 4 matrix.
#include <Mtx44.h>
Public Member Functions
Mtx44 (float a00=0, float a10=0, float a20=0, float a30=0, float a01=0, float a11=0, float a21=0, float a31=0, float a02=0, float a12=0, float a22=0, float a32=0, float a03=0, float a13=0, float a23=0, float a33=0)
Default Constructor. Default values are zero.
Mtx44 (const float m[16])
Constructor with array of 16 floats. Default values are zero.
Mtx44 (const Mtx44 &rhs)
Copy constructor.
void SetToIdentity (void)
Set the matrix to an identity matrix (1's along the diagonal)
void Transpose (void)
Set this matrix to its Transpose.
void SetToZero (void)
Set this matrix to zero.
Mtx44 GetTranspose () const
Return a new matrix that is a transpose of this matrix.
Mtx44 GetInverse () const throw (DivideByZero)
Return a new matrix that is an inverse.
Mtx44 operator* (const Mtx44 &rhs) const
operator* overload for matrix-matrix multiplication
Mtx44 operator+ (const Mtx44 &rhs) const
operator+ overload for matrix-matrix addition
Mtx44 & operator= (const Mtx44 &rhs)
operator= overload for assignment
Mtx44 operator* (float scalar) const
operator* overload for scalar multiplication
Vector3 operator* (const Vector3 &rhs) const
operator* overload for matrix-vector3 multiplication
void SetToRotation (float degrees, float axisX, float axisY, float axisZ) throw (DivideByZero)
Set Matrix to a rotation matrix about arbitrary axis.
void SetToScale (float sx, float sy, float sz)
Set this matrix to a scaling matrix with scale factors sx, sy and sz.
void SetToTranslation (float tx, float ty, float tz)
Set this matrix to a translation matrix with translation of (x, y, z)
void SetToFrustum (double left, double right, double bottom, double top, double near, double far)
Set this matrix to frustum matrix.
void SetToLookAt (double eyeX, double eyeY, double eyeZ, double centerX, double centerY, double centerZ, double upX, double upY, double upZ)
Set matrix to be a lookat matrix.
void SetToPerspective (double fovy, double aspect, double zNear, double zFar)
Set matrix to be a perspective matrix.
void SetToOrtho (double left, double right, double bottom, double top, double nearVal, double farVal)
Setup orthogonal matrix.
Data Fields
float a [16]
Detailed Description
A 4 by 4 matrix.
Class Mtx44:
Definition at line 24 of file Mtx44.h.
Constructor & Destructor Documentation
Mtx44::Mtx44 (float a00 = 0, float a10 = 0, float a20 = 0, float a30 = 0, float a01 = 0, float a11 = 0, float a21 = 0, float a31 = 0, float a02 = 0, float a12 = 0, float a22 = 0, float a32 = 0, float a03 = 0, float a13 = 0, float a23 = 0, float a33 = 0)
Default Constructor. Default values are zero.
Parameters
a00 to a33 - Initial values for the matrix in (row, column) format
Exceptions
None
Returns
None
Definition at line 22 of file Mtx44.cpp.
References a.
Referenced by operator+(), SetToFrustum(), SetToOrtho(), and SetToPerspective().
Mtx44::Mtx44 (const float m[16])
Constructor with array of 16 floats. Default values are zero.
Parameters
m[16] - Initial values for the matrix in column major format
Exceptions
None
Returns
None
Definition at line 52 of file Mtx44.cpp.
References a.
Mtx44::Mtx44 (const Mtx44 & rhs)
Copy constructor.
Definition at line 63 of file Mtx44.cpp.
References a.
Member Function Documentation
Mtx44 Mtx44::GetInverse () const throw (DivideByZero)
Return a new matrix that is an inverse.
Exceptions
DivideByZero thrown if the determinant of the matrix is zero
Returns
A new matrix
Definition at line 139 of file Mtx44.cpp.
References a, Math::EPSILON, and Math::FAbs().
Referenced by CutSceneOne::RenderMesh(), SceneOpening::RenderMesh(), OpeningCutScene::RenderMesh(), Credits::RenderMesh(), OpeningCutScene2::RenderMesh(), SceneEndCutScene::RenderMesh(), SceneStart::RenderMesh(), SceneLevelTwo::RenderMesh(), SceneLevelOneA::RenderMesh(), SceneEnd::RenderMesh(), and SceneLevelOneB::RenderMesh().
Mtx44 Mtx44::GetTranspose () const
Return a new matrix that is a transpose of this matrix.
Returns
A new matrix
Definition at line 123 of file Mtx44.cpp.
References Transpose().
Referenced by CutSceneOne::RenderMesh(), SceneOpening::RenderMesh(), OpeningCutScene::RenderMesh(), Credits::RenderMesh(), OpeningCutScene2::RenderMesh(), SceneEndCutScene::RenderMesh(), SceneStart::RenderMesh(), SceneLevelTwo::RenderMesh(), SceneLevelOneA::RenderMesh(), SceneEnd::RenderMesh(), and SceneLevelOneB::RenderMesh().
Mtx44 Mtx44::operator* (const Mtx44 & rhs) const
operator* overload for matrix-matrix multiplication
Parameters
rhs Matrix to multiply with
Returns
Resulting matrix
Definition at line 208 of file Mtx44.cpp.
References a.
Mtx44 Mtx44::operator* (float scalar) const
operator* overload for scalar multiplication
Parameters
scalar float to multiply with
Returns
Resulting matrix
Definition at line 276 of file Mtx44.cpp.
References a.
Vector3 Mtx44::operator* (const Vector3 & rhs) const
operator* overload for matrix-vector3 multiplication
Parameters
rhs Vector3 to multiply with
Returns
Resulting vector
Definition at line 294 of file Mtx44.cpp.
References a, Vector3::x, Vector3::y, and Vector3::z.
Mtx44 Mtx44::operator+ (const Mtx44 & rhs) const
operator+ overload for matrix-matrix addition
Parameters
rhs Matrix to add with
Returns
Resulting matrix
Definition at line 227 of file Mtx44.cpp.
References a, and Mtx44().
Mtx44 & Mtx44::operator= (const Mtx44 & rhs)
operator= overload for assignment
Parameters
rhs Matrix to assign to
Returns
Reference to this matrix
Definition at line 259 of file Mtx44.cpp.
References a.
void Mtx44::SetToFrustum (double left, double right, double bottom, double top, double near, double far)
Set this matrix to frustum matrix.
Parameters
left Frustum - left
right Frustum - right
bottom Frustum - bottom
top Frustum - top
nearVal Frustum - front
farVal Frustum - back
Definition at line 402 of file Mtx44.cpp.
References Mtx44().
Referenced by MS::Frustum().
void Mtx44::SetToIdentity (void)
Set the matrix to an identity matrix (1's along the diagonal)
Definition at line 74 of file Mtx44.cpp.
References a, and SetToZero().
Referenced by MS::LoadIdentity(), MS::MS(), SetToScale(), and SetToTranslation().
void Mtx44::SetToLookAt (double eyeX, double eyeY, double eyeZ, double centerX, double centerY, double centerZ, double upX, double upY, double upZ)
Set matrix to be a lookat matrix.
Parameters
eyeX eye vector x value
eyeY eye vector y value
eyeZ eye vector z value
centerX target position x value
centerY target position y value
centerZ target position z value
upX up vector x value
upY up vector y value
upZ up vector z value
Definition at line 433 of file Mtx44.cpp.
References Vector3::Cross(), Vector3::Normalize(), SetToTranslation(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by MS::LookAt().
void Mtx44::SetToOrtho (double left, double right, double bottom, double top, double nearVal, double farVal)
Setup orthogonal matrix.
Parameters
left View box - left
right View box - right
bottom View box - bottom
top View box - top
nearVal View box - front
farVal View box - back
Definition at line 492 of file Mtx44.cpp.
References Mtx44().
Referenced by SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), and SceneLevelOneA::RenderTextOnScreen().
void Mtx44::SetToPerspective (double fovy, double aspect, double zNear, double zFar)
Set matrix to be a perspective matrix.
Parameters
fovy Field of view
aspect Aspect ratio = width : height
zNear Near plane
zFar Far plane
Definition at line 466 of file Mtx44.cpp.
References Mtx44(), and Math::PI.
Referenced by CutSceneOne::Init(), SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), and SceneLevelOneB::Init().
void Mtx44::SetToRotation (float degrees, float axisX, float axisY, float axisZ) throw (DivideByZero)
Set Matrix to a rotation matrix about arbitrary axis.
Parameters
degrees Angle of rotation, in degrees, clockwise
axisX X-component of the rotation axis
axisY Y-component of the rotation axis
axisZ Z-component of the rotation axis
Exceptions
DivideByZero Thrown if rotation axis is a zero vector
Definition at line 319 of file Mtx44.cpp.
References Math::EPSILON, Math::FAbs(), and Math::PI.
Referenced by MS::Rotate().
void Mtx44::SetToScale (float sx, float sy, float sz)
Set this matrix to a scaling matrix with scale factors sx, sy and sz.
Parameters
sx scale at x-axis
sy scale at y-axis
sz scale at z-axis
Definition at line 356 of file Mtx44.cpp.
References a, and SetToIdentity().
Referenced by MS::Scale().
void Mtx44::SetToTranslation (float tx, float ty, float tz)
Set this matrix to a translation matrix with translation of (x, y, z)
Parameters
x translate at x-axis
y translate at y-axis
z translate at y-axis
Definition at line 376 of file Mtx44.cpp.
References a, and SetToIdentity().
Referenced by SceneOpening::RenderText(), OpeningCutScene2::RenderText(), SceneEndCutScene::RenderText(), SceneStart::RenderText(), SceneEnd::RenderText(), SceneLevelTwo::RenderText(), SceneLevelOneB::RenderText(), SceneLevelOneA::RenderText(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), SetToLookAt(), and MS::Translate().
void Mtx44::SetToZero (void)
Set this matrix to zero.
Definition at line 109 of file Mtx44.cpp.
References a.
Referenced by SetToIdentity().
void Mtx44::Transpose (void)
Set this matrix to its Transpose.
Definition at line 97 of file Mtx44.cpp.
References a, and swap().
Referenced by GetTranspose().
Field Documentation
float Mtx44::a[16]
Definition at line 50 of file Mtx44.h.
Referenced by GetInverse(), Mtx44(), operator*(), operator*(), operator+(), operator=(), CutSceneOne::RenderMesh(), SceneOpening::RenderMesh(), OpeningCutScene::RenderMesh(), Credits::RenderMesh(), OpeningCutScene2::RenderMesh(), SceneEndCutScene::RenderMesh(), SceneStart::RenderMesh(), SceneLevelTwo::RenderMesh(), SceneLevelOneA::RenderMesh(), SceneEnd::RenderMesh(), SceneLevelOneB::RenderMesh(), SceneOpening::RenderText(), OpeningCutScene2::RenderText(), SceneEndCutScene::RenderText(), SceneStart::RenderText(), SceneEnd::RenderText(), SceneLevelTwo::RenderText(), SceneLevelOneB::RenderText(), SceneLevelOneA::RenderText(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), SetToIdentity(), SetToScale(), SetToTranslation(), SetToZero(), and Transpose().
The documentation for this class was generated from the following files:
Common/Source/Mtx44.h
Common/Source/Mtx44.cpp