My Application: misc Class Reference
misc Class Reference
#include <Misc.h>
Public Member Functions
misc ()
~misc ()
bool WithinArea (float smallx, float largex, float smallz, float largez)
bool hitting (float distance, float mobx, float mobz, float AOA, float camX, float camZ, Vector3 view, Vector3 position)
Data Fields
float camX
float camY
float camZ
Detailed Description
Definition at line 6 of file Misc.h.
Constructor & Destructor Documentation
misc::misc ()
Definition at line 2 of file Misc.cpp.
misc::~misc ()
Definition at line 6 of file Misc.cpp.
Member Function Documentation
bool misc::hitting (float distance, float mobx, float mobz, float AOA, float camX, float camZ, Vector3 view, Vector3 position)
Definition at line 22 of file Misc.cpp.
References getAngle().
Referenced by SceneLevelOneB::attackCheck(), SceneLevelOneA::AttackCheck(), and SceneEnd::checkAttack().
bool misc::WithinArea (float smallx, float largex, float smallz, float largez)
Definition at line 40 of file Misc.cpp.
References camX, and camZ.
Referenced by SceneLevelOneA::checkDoor1(), SceneLevelOneB::ElevatorCheck(), SceneLevelOneB::PuzzleOneSwitchCheck(), SceneLevelTwo::SomeUpdates(), and SceneLevelTwo::SwitchCheck().
Field Documentation
float misc::camX
Definition at line 15 of file Misc.h.
Referenced by SceneLevelOneA::checkDoor2(), SceneStart::checkPlayerPosMisc(), SceneLevelTwo::checkPlayerPosMisc(), SceneLevelOneB::checkPlayerPosMisc(), SceneLevelTwo::RenderScene(), and WithinArea().
float misc::camY
Definition at line 15 of file Misc.h.
Referenced by SceneLevelOneA::checkDoor2(), SceneStart::checkPlayerPosMisc(), SceneLevelTwo::checkPlayerPosMisc(), SceneLevelOneB::checkPlayerPosMisc(), and SceneLevelTwo::RenderScene().
float misc::camZ
Definition at line 15 of file Misc.h.
Referenced by SceneLevelOneA::checkDoor2(), SceneStart::checkPlayerPosMisc(), SceneLevelTwo::checkPlayerPosMisc(), SceneLevelOneB::checkPlayerPosMisc(), SceneLevelTwo::RenderScene(), and WithinArea().
The documentation for this class was generated from the following files:
ComGraphics/Source/Misc.h
ComGraphics/Source/Misc.cpp