My Application: MS Class Reference
MS Class Reference
Matrix Stack class.
#include <MatrixStack.h>
Public Member Functions
MS ()
MS default constructor.
~MS ()
MS destructor.
const Mtx44 & Top () const
Return the top matrix on the matrix stack.
void PopMatrix ()
Pop the top matrix on the matrix stack.
void PushMatrix ()
Make a copy of the top matrix on the matrix stack and push it on top.
void Clear ()
Clear the matrix stack.
void LoadIdentity ()
Replace the top matrix with an identity matrix.
void LoadMatrix (const Mtx44 &matrix)
Return the top matrix with a new matrix.
void MultMatrix (const Mtx44 &matrix)
Multiply the top matrix with a new matrix.
void Rotate (float degrees, float axisX, float axisY, float axisZ)
Multiply the top matrix with a rotation matrix based on the following parameters.
void Scale (float scaleX, float scaleY, float scaleZ)
Multiply the top matrix with a scale matrix based on the following parameters.
void Translate (float translateX, float translateY, float translateZ)
Multiply the top matrix with a translation matrix based on the following parameters.
void Frustum (double left, double right, double bottom, double top, double near, double far)
Setup frustum matrix and push to matrix stack.
void LookAt (double eyeX, double eyeY, double eyeZ, double centerX, double centerY, double centerZ, double upX, double upY, double upZ)
Setup lookat matrix and push to matrix stack.
Private Attributes
std::stack< Mtx44 > ms
Detailed Description
Matrix Stack class.
Class MS:
Definition at line 22 of file MatrixStack.h.
Constructor & Destructor Documentation
MS::MS ()
MS default constructor.
Definition at line 18 of file MatrixStack.cpp.
References ms, and Mtx44::SetToIdentity().
MS::~MS ()
MS destructor.
Definition at line 30 of file MatrixStack.cpp.
Member Function Documentation
void MS::Clear ()
Clear the matrix stack.
Definition at line 72 of file MatrixStack.cpp.
References ms.
void MS::Frustum (double left, double right, double bottom, double top, double near, double far)
Setup frustum matrix and push to matrix stack.
Parameters
left Frustum - left
right Frustum - right
bottom Frustum - bottom
top Frustum - top
near Frustum - front
far Frustum - back
Definition at line 194 of file MatrixStack.cpp.
References ms, and Mtx44::SetToFrustum().
void MS::LoadIdentity ()
Replace the top matrix with an identity matrix.
Definition at line 83 of file MatrixStack.cpp.
References ms, and Mtx44::SetToIdentity().
Referenced by CutSceneOne::Render(), SceneOpening::Render(), OpeningCutScene::Render(), Credits::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), and SceneLevelOneA::RenderTextOnScreen().
void MS::LoadMatrix (const Mtx44 & matrix)
Return the top matrix with a new matrix.
Parameters
matrix The new matrix to replace the top
Definition at line 98 of file MatrixStack.cpp.
References ms.
Referenced by CutSceneOne::Init(), SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), SceneLevelOneB::Init(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), and SceneLevelOneA::RenderTextOnScreen().
void MS::LookAt (double eyeX, double eyeY, double eyeZ, double centerX, double centerY, double centerZ, double upX, double upY, double upZ)
Setup lookat matrix and push to matrix stack.
Parameters
eyeX eye vector x value
eyeY eye vector y value
eyeZ eye vector z value
centerX target position x value
centerY target position y value
centerZ target position z value
upX up vector x value
upY up vector y value
upZ up vector z value
Definition at line 224 of file MatrixStack.cpp.
References ms, and Mtx44::SetToLookAt().
Referenced by CutSceneOne::Render(), SceneOpening::Render(), OpeningCutScene::Render(), Credits::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), and SceneLevelOneB::Render().
void MS::MultMatrix (const Mtx44 & matrix)
Multiply the top matrix with a new matrix.
Parameters
matrix The new matrix to replace the top
Definition at line 111 of file MatrixStack.cpp.
References ms.
void MS::PopMatrix ()
Pop the top matrix on the matrix stack.
Definition at line 52 of file MatrixStack.cpp.
References ms.
Referenced by SceneLevelOneA::CollapseRubble(), SceneLevelOneA::DropPortrait(), SceneOpening::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), SceneLevelOneB::RenderBoss(), SceneEnd::RenderBoss(), Credits::RenderCredits(), CutSceneOne::RenderCutSceneOne(), SceneLevelOneB::RenderDoor(), SceneLevelTwo::RenderDownWall(), SceneLevelOneB::RenderDownWall(), SceneEnd::RenderDownWall(), SceneLevelOneA::RenderDownWall(), OpeningCutScene2::RenderFloor(), SceneEndCutScene::RenderFloor(), SceneStart::RenderFloor(), SceneEnd::RenderFloor(), SceneLevelTwo::RenderFloorCeiling(), SceneLevelOneA::RenderFloorCeiling(), SceneLevelOneB::RenderFloorCeiling(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), SceneLevelTwo::RenderGhost1(), SceneLevelTwo::RenderLeftWall(), SceneLevelOneA::RenderLeftWall(), SceneLevelOneB::RenderLeftWall(), SceneEnd::RenderMobs(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), OpeningCutScene::RenderOpeningCutScene(), SceneLevelOneA::RenderPickUpPickAxe(), SceneLevelOneB::RenderPickUpPickTools(), SceneLevelTwo::RenderPuzzle(), SceneLevelOneB::RenderPuzzle(), SceneLevelTwo::RenderRightWall(), SceneLevelOneB::RenderRightWall(), SceneLevelOneA::RenderRightWall(), SceneLevelTwo::RenderScene(), SceneLevelOneA::RenderScene(), SceneLevelOneB::RenderScene(), SceneEnd::RenderSceneEnd(), SceneEndCutScene::RenderSceneEndCutScene(), OpeningCutScene2::RenderSceneStart(), SceneStart::RenderSceneStart(), SceneEndCutScene::RenderShipAndPod(), SceneEnd::RenderShipAndPod(), OpeningCutScene2::RenderSkyBox(), SceneEndCutScene::RenderSkyBox(), SceneStart::RenderSkyBox(), SceneEnd::RenderSkyBox(), SceneLevelOneA::RenderSuitCase(), SceneLevelTwo::RenderSwitches(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), OpeningCutScene2::RenderTextWord(), SceneLevelTwo::RenderTraps(), SceneLevelTwo::RenderUpWall(), SceneLevelOneA::RenderUpWall(), SceneLevelOneB::RenderUpWall(), SceneLevelOneA::TestDoorRender(), SceneStart::ToolSelectionMouseScroll(), SceneLevelTwo::ToolSelectionMouseScroll(), SceneLevelOneA::ToolSelectionMouseScroll(), SceneEnd::ToolSelectionMouseScroll(), and SceneLevelOneB::ToolSelectionMouseScroll().
void MS::PushMatrix ()
Make a copy of the top matrix on the matrix stack and push it on top.
Definition at line 62 of file MatrixStack.cpp.
References ms.
Referenced by SceneLevelOneA::CollapseRubble(), SceneLevelOneA::DropPortrait(), SceneOpening::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), SceneLevelOneB::RenderBoss(), SceneEnd::RenderBoss(), Credits::RenderCredits(), CutSceneOne::RenderCutSceneOne(), SceneLevelOneB::RenderDoor(), SceneLevelTwo::RenderDownWall(), SceneLevelOneB::RenderDownWall(), SceneEnd::RenderDownWall(), SceneLevelOneA::RenderDownWall(), OpeningCutScene2::RenderFloor(), SceneEndCutScene::RenderFloor(), SceneStart::RenderFloor(), SceneEnd::RenderFloor(), SceneLevelTwo::RenderFloorCeiling(), SceneLevelOneA::RenderFloorCeiling(), SceneLevelOneB::RenderFloorCeiling(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), SceneLevelTwo::RenderGhost1(), SceneLevelTwo::RenderLeftWall(), SceneLevelOneA::RenderLeftWall(), SceneLevelOneB::RenderLeftWall(), SceneEnd::RenderMobs(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), OpeningCutScene::RenderOpeningCutScene(), SceneLevelOneA::RenderPickUpPickAxe(), SceneLevelOneB::RenderPickUpPickTools(), SceneLevelTwo::RenderPuzzle(), SceneLevelOneB::RenderPuzzle(), SceneLevelTwo::RenderRightWall(), SceneLevelOneB::RenderRightWall(), SceneLevelOneA::RenderRightWall(), SceneLevelTwo::RenderScene(), SceneLevelOneA::RenderScene(), SceneLevelOneB::RenderScene(), SceneEnd::RenderSceneEnd(), SceneEndCutScene::RenderSceneEndCutScene(), OpeningCutScene2::RenderSceneStart(), SceneStart::RenderSceneStart(), SceneEndCutScene::RenderShipAndPod(), SceneEnd::RenderShipAndPod(), OpeningCutScene2::RenderSkyBox(), SceneEndCutScene::RenderSkyBox(), SceneStart::RenderSkyBox(), SceneEnd::RenderSkyBox(), SceneLevelOneA::RenderSuitCase(), SceneLevelTwo::RenderSwitches(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), OpeningCutScene2::RenderTextWord(), SceneLevelTwo::RenderTraps(), SceneLevelTwo::RenderUpWall(), SceneLevelOneA::RenderUpWall(), SceneLevelOneB::RenderUpWall(), SceneLevelOneA::TestDoorRender(), SceneStart::ToolSelectionMouseScroll(), SceneLevelTwo::ToolSelectionMouseScroll(), SceneLevelOneA::ToolSelectionMouseScroll(), SceneEnd::ToolSelectionMouseScroll(), and SceneLevelOneB::ToolSelectionMouseScroll().
void MS::Rotate (float degrees, float axisX, float axisY, float axisZ)
Multiply the top matrix with a rotation matrix based on the following parameters.
Parameters
degrees Angle of rotation, in degrees, clockwise
axisX X-component of the rotation axis
axisY Y-component of the rotation axis
axisZ Z-component of the rotation axis
Definition at line 130 of file MatrixStack.cpp.
References ms, and Mtx44::SetToRotation().
Referenced by SceneLevelOneA::DropPortrait(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneLevelOneB::RenderBoss(), SceneEnd::RenderBoss(), CutSceneOne::RenderCutSceneOne(), SceneLevelOneB::RenderDoor(), SceneLevelTwo::RenderDownWall(), SceneLevelOneA::RenderDownWall(), SceneLevelOneB::RenderDownWall(), SceneEnd::RenderDownWall(), SceneStart::RenderFloor(), SceneLevelTwo::RenderFloorCeiling(), SceneLevelOneA::RenderFloorCeiling(), SceneLevelOneB::RenderFloorCeiling(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), SceneLevelTwo::RenderLeftWall(), SceneLevelOneB::RenderLeftWall(), SceneLevelOneA::RenderLeftWall(), SceneEnd::RenderMobs(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), SceneLevelOneA::RenderPickUpPickAxe(), SceneLevelOneB::RenderPickUpPickTools(), SceneLevelTwo::RenderPuzzle(), SceneLevelOneB::RenderPuzzle(), SceneLevelTwo::RenderRightWall(), SceneLevelOneB::RenderRightWall(), SceneLevelOneA::RenderRightWall(), SceneLevelTwo::RenderScene(), SceneLevelOneA::RenderScene(), SceneLevelOneB::RenderScene(), SceneEnd::RenderSceneEnd(), SceneEndCutScene::RenderSceneEndCutScene(), OpeningCutScene2::RenderSceneStart(), SceneStart::RenderSceneStart(), SceneEnd::RenderShipAndPod(), OpeningCutScene2::RenderSkyBox(), SceneEndCutScene::RenderSkyBox(), SceneStart::RenderSkyBox(), SceneEnd::RenderSkyBox(), SceneLevelOneA::RenderSuitCase(), SceneLevelTwo::RenderSwitches(), SceneLevelTwo::RenderTraps(), SceneLevelTwo::RenderUpWall(), SceneLevelOneB::RenderUpWall(), and SceneLevelOneA::RenderUpWall().
void MS::Scale (float scaleX, float scaleY, float scaleZ)
Multiply the top matrix with a scale matrix based on the following parameters.
Parameters
scaleX Factor to scale along x-axis
scaleY Factor to scale along y-axis
scaleZ Factor to scale along z-axis
Definition at line 149 of file MatrixStack.cpp.
References ms, and Mtx44::SetToScale().
Referenced by SceneLevelOneA::CollapseRubble(), SceneLevelOneA::DropPortrait(), OpeningCutScene2::Render(), SceneEnd::Render(), SceneLevelOneB::RenderBoss(), SceneEnd::RenderBoss(), CutSceneOne::RenderCutSceneOne(), SceneLevelOneB::RenderDoor(), SceneLevelTwo::RenderDownWall(), SceneEnd::RenderDownWall(), SceneLevelOneB::RenderDownWall(), SceneLevelOneA::RenderDownWall(), OpeningCutScene2::RenderFloor(), SceneEndCutScene::RenderFloor(), SceneStart::RenderFloor(), SceneEnd::RenderFloor(), SceneLevelTwo::RenderFloorCeiling(), SceneLevelOneA::RenderFloorCeiling(), SceneLevelOneB::RenderFloorCeiling(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), SceneLevelTwo::RenderLeftWall(), SceneLevelOneB::RenderLeftWall(), SceneLevelOneA::RenderLeftWall(), SceneEnd::RenderMobs(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), SceneLevelOneA::RenderPickUpPickAxe(), SceneLevelOneB::RenderPickUpPickTools(), SceneLevelTwo::RenderPuzzle(), SceneLevelOneB::RenderPuzzle(), SceneLevelTwo::RenderRightWall(), SceneLevelOneB::RenderRightWall(), SceneLevelOneA::RenderRightWall(), SceneLevelTwo::RenderScene(), SceneLevelOneA::RenderScene(), SceneLevelOneB::RenderScene(), SceneEnd::RenderSceneEnd(), SceneEndCutScene::RenderSceneEndCutScene(), OpeningCutScene2::RenderSceneStart(), SceneStart::RenderSceneStart(), SceneEndCutScene::RenderShipAndPod(), SceneEnd::RenderShipAndPod(), OpeningCutScene2::RenderSkyBox(), SceneEndCutScene::RenderSkyBox(), SceneStart::RenderSkyBox(), SceneEnd::RenderSkyBox(), SceneLevelOneA::RenderSuitCase(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), SceneLevelTwo::RenderTraps(), SceneLevelTwo::RenderUpWall(), SceneLevelOneA::RenderUpWall(), SceneLevelOneB::RenderUpWall(), and SceneLevelOneA::TestDoorRender().
const Mtx44 & MS::Top () const
Return the top matrix on the matrix stack.
Returns
A copy of the top matrix
Definition at line 42 of file MatrixStack.cpp.
References ms.
Referenced by CutSceneOne::Render(), SceneOpening::Render(), OpeningCutScene::Render(), Credits::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), CutSceneOne::RenderMesh(), SceneOpening::RenderMesh(), OpeningCutScene::RenderMesh(), Credits::RenderMesh(), OpeningCutScene2::RenderMesh(), SceneEndCutScene::RenderMesh(), SceneStart::RenderMesh(), SceneLevelTwo::RenderMesh(), SceneLevelOneA::RenderMesh(), SceneEnd::RenderMesh(), SceneLevelOneB::RenderMesh(), SceneOpening::RenderText(), OpeningCutScene2::RenderText(), SceneEndCutScene::RenderText(), SceneStart::RenderText(), SceneEnd::RenderText(), SceneLevelTwo::RenderText(), SceneLevelOneB::RenderText(), SceneLevelOneA::RenderText(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), and SceneLevelOneA::RenderTextOnScreen().
void MS::Translate (float translateX, float translateY, float translateZ)
Multiply the top matrix with a translation matrix based on the following parameters.
Parameters
translateX Offset along x-axis
scaleY Offset along y-axis
scaleZ Offset along z-axis
Definition at line 169 of file MatrixStack.cpp.
References ms, and Mtx44::SetToTranslation().
Referenced by SceneLevelOneA::CollapseRubble(), SceneLevelOneA::DropPortrait(), OpeningCutScene2::Render(), SceneEnd::Render(), SceneLevelOneB::RenderBoss(), SceneEnd::RenderBoss(), CutSceneOne::RenderCutSceneOne(), SceneLevelOneB::RenderDoor(), SceneLevelTwo::RenderDownWall(), SceneEnd::RenderDownWall(), SceneLevelOneB::RenderDownWall(), SceneLevelOneA::RenderDownWall(), OpeningCutScene2::RenderFloor(), SceneEndCutScene::RenderFloor(), SceneStart::RenderFloor(), SceneEnd::RenderFloor(), SceneLevelTwo::RenderFloorCeiling(), SceneLevelOneA::RenderFloorCeiling(), SceneLevelOneB::RenderFloorCeiling(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), SceneLevelTwo::RenderGhost1(), SceneLevelTwo::RenderLeftWall(), SceneLevelOneB::RenderLeftWall(), SceneLevelOneA::RenderLeftWall(), SceneEnd::RenderMobs(), SceneOpening::RenderModelOnScreen(), OpeningCutScene::RenderModelOnScreen(), Credits::RenderModelOnScreen(), OpeningCutScene2::RenderModelOnScreen(), SceneEndCutScene::RenderModelOnScreen(), SceneStart::RenderModelOnScreen(), SceneEnd::RenderModelOnScreen(), SceneLevelTwo::RenderModelOnScreen(), SceneLevelOneB::RenderModelOnScreen(), SceneLevelOneA::RenderModelOnScreen(), SceneLevelOneA::RenderPickUpPickAxe(), SceneLevelOneB::RenderPickUpPickTools(), SceneLevelTwo::RenderPuzzle(), SceneLevelOneB::RenderPuzzle(), SceneLevelTwo::RenderRightWall(), SceneLevelOneB::RenderRightWall(), SceneLevelOneA::RenderRightWall(), SceneLevelTwo::RenderScene(), SceneLevelOneA::RenderScene(), SceneLevelOneB::RenderScene(), SceneEnd::RenderSceneEnd(), SceneEndCutScene::RenderSceneEndCutScene(), OpeningCutScene2::RenderSceneStart(), SceneStart::RenderSceneStart(), SceneEndCutScene::RenderShipAndPod(), SceneEnd::RenderShipAndPod(), OpeningCutScene2::RenderSkyBox(), SceneEndCutScene::RenderSkyBox(), SceneStart::RenderSkyBox(), SceneEnd::RenderSkyBox(), SceneLevelOneA::RenderSuitCase(), SceneLevelTwo::RenderSwitches(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), SceneLevelTwo::RenderTraps(), SceneLevelTwo::RenderUpWall(), SceneLevelOneB::RenderUpWall(), SceneLevelOneA::RenderUpWall(), and SceneLevelOneA::TestDoorRender().
Field Documentation
std::stack<Mtx44> MS::ms private
Definition at line 23 of file MatrixStack.h.
Referenced by Clear(), Frustum(), LoadIdentity(), LoadMatrix(), LookAt(), MS(), MultMatrix(), PopMatrix(), PushMatrix(), Rotate(), Scale(), Top(), and Translate().
The documentation for this class was generated from the following files:
Common/Source/MatrixStack.h
Common/Source/MatrixStack.cpp