My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
static Mesh * GenerateQuad (const std::string &meshName, Color color)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateRing (const std::string &meshName, Color color, float innerRadius, unsigned numSlices=36)
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices=36, float numSpins=1, bool Wire=false)
static Mesh * GenerateTorus (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float outerR, float innerR)
static Mesh * GenerateCylinder (const std::string &meshName, Color color, unsigned numSlice, float top=1, float Partial=1)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 15 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Definition at line 49 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), and SceneLevelOneB::Init().
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 93 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 336 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshName, Color color, unsigned numSlice, float top = 1, float Partial = 1) static
Definition at line 452 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 19 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by CutSceneOne::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), and SceneLevelOneB::Init().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 247 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, TexCoord::Set(), Position::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), and SceneLevelOneB::Init().
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, float innerRadius, unsigned numSlices = 36) static
Definition at line 131 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices = 36, float numSpins = 1, bool Wire = false) static
Definition at line 186 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Referenced by SceneOpening::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), and SceneLevelOneB::Init().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 280 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, TexCoord::Set(), Position::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), and SceneLevelOneB::Init().
Mesh * MeshBuilder::GenerateTorus (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float outerR, float innerR) static
Definition at line 402 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SceneEndCutScene::Init(), and SceneEnd::Init().
The documentation for this class was generated from the following files:
ComGraphics/Source/MeshBuilder.h
ComGraphics/Source/MeshBuilder.cpp