My Application: SceneOpening Class Reference
SceneOpening Class Reference
#include <SceneOpening.h>
Public Member Functions
SceneOpening ()
~SceneOpening ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE { GEO_LIGHTBALL, GEO_TEXT, GEO_TITLE, NUM_GEOMETRY }
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void OptionChange (double dt)
void RenderOptionChange ()
void ChangeScene ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
MS modelStack
MS viewStack
MS projectionStack
unsigned int ui_ChooseOption
float ChooseOptionDebounce
Application App
Light light [1]
Detailed Description
Definition at line 15 of file SceneOpening.h.
Member Enumeration Documentation
enum SceneOpening::GEOMETRY_TYPE private
Enumerator
GEO_LIGHTBALL
GEO_TEXT
GEO_TITLE
NUM_GEOMETRY
Definition at line 17 of file SceneOpening.h.
enum SceneOpening::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 26 of file SceneOpening.h.
Constructor & Destructor Documentation
SceneOpening::SceneOpening ()
Definition at line 12 of file SceneOpening.cpp.
References ui_ChooseOption.
SceneOpening::~SceneOpening ()
Definition at line 17 of file SceneOpening.cpp.
Member Function Documentation
void SceneOpening::ChangeScene () private
Definition at line 166 of file SceneOpening.cpp.
References App, Application::Exit(), Application::IsKeyPressed(), Application::OpenCutScene(), and ui_ChooseOption.
Referenced by Update().
void SceneOpening::Exit () virtual
Implements Scene.
Definition at line 382 of file SceneOpening.cpp.
References m_programID, and m_vertexArrayID.
void SceneOpening::Init () virtual
Implements Scene.
Definition at line 21 of file SceneOpening.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_LIGHTBALL, GEO_TEXT, GEO_TITLE, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void SceneOpening::OptionChange (double dt) private
Definition at line 125 of file SceneOpening.cpp.
References ChooseOptionDebounce, Application::mouse_scroll, and ui_ChooseOption.
Referenced by Update().
void SceneOpening::Render () virtual
Implements Scene.
Definition at line 335 of file SceneOpening.cpp.
References camera, GEO_TITLE, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderModelOnScreen(), RenderOptionChange(), Light::spotDirection, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneOpening::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 194 of file SceneOpening.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderModelOnScreen().
void SceneOpening::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 314 of file SceneOpening.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneOpening::RenderOptionChange () private
Definition at line 147 of file SceneOpening.cpp.
References GEO_TEXT, meshList, RenderTextOnScreen(), and ui_ChooseOption.
Referenced by Render().
void SceneOpening::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 238 of file SceneOpening.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneOpening::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 268 of file SceneOpening.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderOptionChange().
void SceneOpening::Reset () virtual
Definition at line 120 of file SceneOpening.cpp.
void SceneOpening::Update (double dt) virtual
Implements Scene.
Definition at line 175 of file SceneOpening.cpp.
References camera, ChangeScene(), Application::IsKeyPressed(), light, OptionChange(), Light::position, Camera::position, Position::Set(), Vector3::Set(), Light::spotDirection, Camera::target, Camera3::Update(), Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Application SceneOpening::App private
Definition at line 91 of file SceneOpening.h.
Referenced by ChangeScene().
Camera3 SceneOpening::camera
Definition at line 66 of file SceneOpening.h.
Referenced by Init(), Render(), and Update().
float SceneOpening::ChooseOptionDebounce private
Definition at line 85 of file SceneOpening.h.
Referenced by OptionChange().
Light SceneOpening::light[1] private
Definition at line 93 of file SceneOpening.h.
Referenced by Init(), Render(), and Update().
unsigned SceneOpening::m_parameters[U_TOTAL] private
Definition at line 79 of file SceneOpening.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SceneOpening::m_programID private
Definition at line 78 of file SceneOpening.h.
Referenced by Exit(), and Init().
unsigned SceneOpening::m_vertexArrayID private
Definition at line 75 of file SceneOpening.h.
Referenced by Exit(), and Init().
Mesh* SceneOpening::meshList[NUM_GEOMETRY] private
Definition at line 76 of file SceneOpening.h.
Referenced by Init(), Render(), and RenderOptionChange().
MS SceneOpening::modelStack private
Definition at line 81 of file SceneOpening.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
MS SceneOpening::projectionStack private
Definition at line 81 of file SceneOpening.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
unsigned int SceneOpening::ui_ChooseOption private
Definition at line 84 of file SceneOpening.h.
Referenced by ChangeScene(), OptionChange(), RenderOptionChange(), and SceneOpening().
MS SceneOpening::viewStack private
Definition at line 81 of file SceneOpening.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneOpening.h
ComGraphics/Source/SceneOpening.cpp