My Application: SceneLevelOneA Class Reference
SceneLevelOneA Class Reference
#include <SceneLevelOneA.h>
Public Member Functions
SceneLevelOneA ()
~SceneLevelOneA ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void ResetSameScene ()
virtual void ResetAll ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_BOTTOM, GEO_TOP, GEO_LEFT,
GEO_RIGHT, GEO_FRONT, GEO_BACK, GEO_QUAD,
GEO_LIGHTBALL, GEO_TEXT, GEO_MOUNTTEXT, GEO_RUBBLE,
GEO_PORTRAIT, GEO_BLOOD, GEO_PLANETFLOOR, GEO_FACILITYFLOOR,
GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FACILITYWALLS, GEO_FACILITYCEILINGS,
GEO_TV, GEO_SPAWNPOINT, GEO_TOOLUIONE, GEO_TOOLUITWO,
GEO_TOOLUITHREE, GEO_TOOLUIFOUR, GEO_HANDICON, GEO_LHAND,
GEO_RHAND, GEO_PICKAXE, GEO_PICKAXEICON, GEO_BAT,
GEO_BATICON, GEO_SWORD, GEO_SWORDICON, GEO_GHOST1,
GEO_BOSS1, GEO_DOORSWITCH, GEO_SLIDEDOORTOP, GEO_SLIDEDOORBTM,
GEO_HEALTHBAR, GEO_STAMINABAR, GEO_DEADCOLOR, GEO_DEADBLACKSCREEN,
GEO_HEALTHICON, GEO_SUITCASE, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderScene ()
void RenderFloorCeiling ()
void RenderCutSceneOne ()
void RenderSuitCase ()
void RenderInteract ()
void RenderDownWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber)
void RenderUpWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber)
void RenderRightWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber)
void RenderLeftWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber)
void RenderGhost (float xpos, float zpos)
void CollapseRubble ()
void DropPortrait ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float Tx, float Ty, float Tz, bool LightYN)
void checkPlayerPos (double dt, int checkRate, int lessenSpeed)
void checkPlayerPosMisc ()
void Collision (float smallx, float largex, float smallz, float largez)
bool proximitycheck (float smallx, float largex, float smallz, float largez)
void PuzzleOneSwitchCheck (double dt)
void ToolsUI ()
void MouseScrollToolSlot ()
void RenderMouseScrollToolSlot ()
void ToolSelectionMouseScroll ()
void RenderToolIcon ()
void MouseClickFunction (double dt)
void RenderPickUpPickAxe ()
void UpdateSavePoint ()
void RenderSavePointText ()
void checkRubbleFall ()
void checkDoor1 (double dt)
void checkDoor2 ()
void checkDoor3 ()
void checkDrop ()
void AttackCheck ()
void TestDoorRender ()
void EnvironmentAnimation (double dt)
void AnimationCheck (double dt)
void RenderPlayerDiesInteraction ()
void UpdatePlayerDiesInteraction (double dt)
void ContinueGameOrNot ()
void PickUpSuitcaseInteraction ()
void RenderPickUpSuitcaseText ()
Private Attributes
bool displayInteract1
bool displayInteract2
bool displayInteract3
bool activateDoor1
bool activateDoor2_1
bool activateDoor2_2
bool activateDoor3
bool Key_1
bool Notice
bool Notice2
bool willDrop
bool Key1Active
float SwitchRot = 45.f
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
GlobalVariables Variables
MobGhost Ghost
float FPS
bool CrosshairHit = false
float CollXLarge [28]
float CollXSmall [28]
float CollZLarge [28]
float CollZSmall [28]
Detailed Description
Definition at line 15 of file SceneLevelOneA.h.
Member Enumeration Documentation
enum SceneLevelOneA::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_BOTTOM
GEO_TOP
GEO_LEFT
GEO_RIGHT
GEO_FRONT
GEO_BACK
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_MOUNTTEXT
GEO_RUBBLE
GEO_PORTRAIT
GEO_BLOOD
GEO_PLANETFLOOR
GEO_FACILITYFLOOR
GEO_FACILITYOUT
GEO_FACILITYOUTWALL
GEO_FACILITYWALLS
GEO_FACILITYCEILINGS
GEO_TV
GEO_SPAWNPOINT
GEO_TOOLUIONE
GEO_TOOLUITWO
GEO_TOOLUITHREE
GEO_TOOLUIFOUR
GEO_HANDICON
GEO_LHAND
GEO_RHAND
GEO_PICKAXE
GEO_PICKAXEICON
GEO_BAT
GEO_BATICON
GEO_SWORD
GEO_SWORDICON
GEO_GHOST1
GEO_BOSS1
GEO_DOORSWITCH
GEO_SLIDEDOORTOP
GEO_SLIDEDOORBTM
GEO_HEALTHBAR
GEO_STAMINABAR
GEO_DEADCOLOR
GEO_DEADBLACKSCREEN
GEO_HEALTHICON
GEO_SUITCASE
NUM_GEOMETRY
Definition at line 17 of file SceneLevelOneA.h.
enum SceneLevelOneA::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 85 of file SceneLevelOneA.h.
Constructor & Destructor Documentation
SceneLevelOneA::SceneLevelOneA ()
Definition at line 17 of file SceneLevelOneA.cpp.
References activateDoor1, activateDoor2_1, activateDoor2_2, activateDoor3, Key1Active, Key_1, Notice, Notice2, and willDrop.
SceneLevelOneA::~SceneLevelOneA ()
Definition at line 30 of file SceneLevelOneA.cpp.
Member Function Documentation
void SceneLevelOneA::AnimationCheck (double dt) private
Definition at line 409 of file SceneLevelOneARenders.cpp.
References activateDoor1, activateDoor2_1, activateDoor2_2, activateDoor3, anima, Animation::CloseSlideDoor2(), Ghost, Animation::OpenSlideDoor1(), Animation::OpenSlideDoor2(), Animation::OpenSlideDoor3(), Animation::Portraits(), HostileMob::Spawn, and willDrop.
Referenced by Update().
void SceneLevelOneA::AttackCheck () private
Definition at line 398 of file SceneLevelOneARenders.cpp.
References camera, CrosshairHit, Ghost, misc::hitting(), Explorer::instance(), Application::IsKeyPressed(), Scene::Misc, HostileMob::MobPosX, HostileMob::MobPosZ, Camera::position, MobGhost::TakeDamage(), Camera3::view, Vector3::x, and Vector3::z.
Referenced by MouseClickFunction().
void SceneLevelOneA::checkDoor1 (double dt) private
Definition at line 141 of file SceneLevelOneARenders.cpp.
References activateDoor1, anima, Collision(), displayInteract1, Application::IsKeyPressed(), Key1Active, Key_1, Notice, proximitycheck(), SwitchRot, Animation::toSlideDoorBtm, and misc::WithinArea().
Referenced by Update().
void SceneLevelOneA::checkDoor2 () private
Definition at line 204 of file SceneLevelOneARenders.cpp.
References activateDoor2_1, activateDoor2_2, anima, camera, misc::camX, misc::camY, misc::camZ, Collision(), displayInteract2, Ghost, HostileMob::health, Application::IsKeyPressed(), Camera::position, proximitycheck(), HostileMob::Spawn, Animation::toSlideDoorBtm2, Animation::toSlideDoorTop2, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneLevelOneA::checkDoor3 () private
Definition at line 254 of file SceneLevelOneARenders.cpp.
References activateDoor3, anima, Collision(), displayInteract3, Application::IsKeyPressed(), proximitycheck(), and Animation::toSlideDoorBtm3.
Referenced by Update().
void SceneLevelOneA::checkDrop () private
Definition at line 292 of file SceneLevelOneARenders.cpp.
References proximitycheck(), and willDrop.
Referenced by Update().
void SceneLevelOneA::checkPlayerPos (double dt, int checkRate, int lessenSpeed) private
void SceneLevelOneA::checkPlayerPosMisc () private
void SceneLevelOneA::checkRubbleFall () private
(anima.WithinArea(-20, 20, 400, 450))
Definition at line 124 of file SceneLevelOneARenders.cpp.
References anima, camera, Animation::Collapse, Collision(), Camera::position, Animation::RubbleCollapse, Vector3::x, and Vector3::z.
Referenced by Update().
void SceneLevelOneA::CollapseRubble () private
Definition at line 371 of file SceneLevelOneARenders.cpp.
References anima, GEO_RUBBLE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), Animation::RubbleCollapse, MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneLevelOneA::Collision (float smallx, float largex, float smallz, float largez) private
Definition at line 298 of file SceneLevelOneA.cpp.
References camera, Math::DegreeToRadian(), Camera::position, Camera3::rotationX, Camera3::rotationY, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by checkDoor1(), checkDoor2(), checkDoor3(), checkRubbleFall(), RenderScene(), and Update().
void SceneLevelOneA::ContinueGameOrNot () private
Definition at line 528 of file SceneLevelOneA.cpp.
References camera, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Application::IsKeyPressed(), light, m_parameters, Application::OpenGame(), Explorer::PlayerLife, Camera::position, Light::power, Explorer::SavePoint, U_LIGHT0_POWER, Variables, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneLevelOneA::DropPortrait () private
Definition at line 380 of file SceneLevelOneARenders.cpp.
References anima, Animation::f_PortraitDrop, Animation::f_PortraitFall, GEO_PORTRAIT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneLevelOneA::EnvironmentAnimation (double dt) private
Definition at line 393 of file SceneLevelOneARenders.cpp.
References GlobalVariables::f_savePointRotateY, GlobalVariables::f_SuitcaseRotateY, and Variables.
Referenced by Update().
void SceneLevelOneA::Exit () virtual
Implements Scene.
Definition at line 901 of file SceneLevelOneA.cpp.
References m_programID, and m_vertexArrayID.
void SceneLevelOneA::Init () virtual
Implements Scene.
Definition at line 34 of file SceneLevelOneA.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BAT, GEO_BATICON, GEO_BLOOD, GEO_BOTTOM, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_DOORSWITCH, GEO_FACILITYCEILINGS, GEO_FACILITYFLOOR, GEO_FACILITYOUT, GEO_FACILITYOUTWALL, GEO_FACILITYWALLS, GEO_FRONT, GEO_GHOST1, GEO_HANDICON, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_LEFT, GEO_LHAND, GEO_LIGHTBALL, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PORTRAIT, GEO_RHAND, GEO_RIGHT, GEO_RUBBLE, GEO_SLIDEDOORBTM, GEO_SLIDEDOORTOP, GEO_SPAWNPOINT, GEO_STAMINABAR, GEO_SUITCASE, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, GEO_TOP, GEO_TV, Ghost, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), MobGhost::setSpawnGhost(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void SceneLevelOneA::MouseClickFunction (double dt) private
Definition at line 465 of file SceneLevelOneA.cpp.
References AttackCheck(), GlobalVariables::b_LockSwing, GlobalVariables::b_LockSwingDebounce, CrosshairHit, Explorer::instance(), Application::IsKeyPressed(), GlobalVariables::RotateX, Explorer::stamina, and Variables.
Referenced by Update().
void SceneLevelOneA::MouseScrollToolSlot () private
Definition at line 424 of file SceneLevelOneA.cpp.
References Explorer::i_SlotIndex, Explorer::instance(), and Application::mouse_scroll.
Referenced by Update().
void SceneLevelOneA::PickUpSuitcaseInteraction () private
Definition at line 567 of file SceneLevelOneA.cpp.
References Explorer::b_pickUpSuitCase, camera, ToolUI::Hand, Explorer::i_SuitcaseCount, Explorer::instance(), Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
bool SceneLevelOneA::proximitycheck (float smallx, float largex, float smallz, float largez) private
Definition at line 312 of file SceneLevelOneA.cpp.
References camera, Camera::position, Vector3::x, and Vector3::z.
Referenced by checkDoor1(), checkDoor2(), checkDoor3(), checkDrop(), and Update().
void SceneLevelOneA::PuzzleOneSwitchCheck (double dt) private
void SceneLevelOneA::Render () virtual
Implements Scene.
Definition at line 803 of file SceneLevelOneA.cpp.
References camera, CollapseRubble(), CrosshairHit, displayInteract1, displayInteract2, displayInteract3, DropPortrait(), FPS, GEO_HEALTHBAR, GEO_HEALTHICON, GEO_STAMINABAR, GEO_TEXT, Ghost, Explorer::instance(), Key1Active, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, HostileMob::MobPosX, HostileMob::MobPosZ, modelStack, Notice, Explorer::PlayerLife, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderGhost(), RenderInteract(), RenderModelOnScreen(), RenderMouseScrollToolSlot(), RenderPickUpPickAxe(), RenderPickUpSuitcaseText(), RenderPlayerDiesInteraction(), RenderSavePointText(), RenderScene(), RenderTextOnScreen(), RenderToolIcon(), HostileMob::Spawn, Light::spotDirection, Camera::target, TestDoorRender(), ToolSelectionMouseScroll(), MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneLevelOneA::RenderCutSceneOne () private
void SceneLevelOneA::RenderDownWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber) private
Definition at line 6 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneA::RenderFloorCeiling () private
Definition at line 9 of file SceneLevelOneARenders.cpp.
References GEO_FACILITYCEILINGS, GEO_FACILITYFLOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneA::RenderGhost (float xpos, float zpos) private
Definition at line 352 of file SceneLevelOneARenders.cpp.
References camera, GEO_GHOST1, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, MS::Translate(), Camera3::view, Vector3::x, and Vector3::z.
Referenced by Render().
void SceneLevelOneA::RenderInteract () private
Definition at line 40 of file SceneLevelOneARenders.cpp.
References GEO_TEXT, meshList, and RenderTextOnScreen().
Referenced by Render().
void SceneLevelOneA::RenderLeftWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber) private
Definition at line 179 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneA::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 662 of file SceneLevelOneA.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by CollapseRubble(), DropPortrait(), RenderDownWall(), RenderFloorCeiling(), RenderGhost(), RenderLeftWall(), RenderModelOnScreen(), RenderPickUpPickAxe(), RenderRightWall(), RenderScene(), RenderSuitCase(), RenderUpWall(), and TestDoorRender().
void SceneLevelOneA::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float Tx, float Ty, float Tz, bool LightYN) private
Definition at line 782 of file SceneLevelOneA.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render(), RenderMouseScrollToolSlot(), RenderPlayerDiesInteraction(), RenderToolIcon(), and ToolSelectionMouseScroll().
void SceneLevelOneA::RenderMouseScrollToolSlot () private
Definition at line 447 of file SceneLevelOneA.cpp.
References GEO_TOOLUIFOUR, GEO_TOOLUIONE, GEO_TOOLUITHREE, GEO_TOOLUITWO, Explorer::instance(), meshList, and RenderModelOnScreen().
Referenced by Render().
void SceneLevelOneA::RenderPickUpPickAxe () private
Definition at line 471 of file SceneLevelOneARenders.cpp.
References GlobalVariables::f_rotatingTool, GEO_PICKAXE, Explorer::instance(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and Variables.
Referenced by Render().
void SceneLevelOneA::RenderPickUpSuitcaseText () private
Definition at line 485 of file SceneLevelOneARenders.cpp.
References camera, GEO_TEXT, ToolUI::Hand, Explorer::instance(), meshList, Camera::position, RenderTextOnScreen(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneLevelOneA::RenderPlayerDiesInteraction () private
Definition at line 437 of file SceneLevelOneARenders.cpp.
References GlobalVariables::f_redScreenTimer, GEO_DEADBLACKSCREEN, GEO_DEADCOLOR, GEO_TEXT, Explorer::instance(), meshList, RenderModelOnScreen(), RenderTextOnScreen(), and Variables.
Referenced by Render().
void SceneLevelOneA::RenderRightWall (int zPosLarge, int zPosSmall, int xPos, int wallNumber) private
Definition at line 122 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneA::RenderSavePointText () private
Definition at line 510 of file SceneLevelOneA.cpp.
References camera, GEO_TEXT, meshList, Camera::position, RenderTextOnScreen(), Vector3::x, and Vector3::z.
Referenced by Render().
void SceneLevelOneA::RenderScene () private
Definition at line 45 of file SceneLevelOneARenders.cpp.
References Collision(), GlobalVariables::f_savePointRotateY, GEO_DOORSWITCH, GEO_FACILITYOUT, GEO_SPAWNPOINT, GEO_TV, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderDownWall(), RenderFloorCeiling(), RenderLeftWall(), RenderMesh(), RenderRightWall(), RenderSuitCase(), RenderUpWall(), MS::Rotate(), MS::Scale(), SwitchRot, MS::Translate(), and Variables.
Referenced by Render().
void SceneLevelOneA::RenderSuitCase () private
Definition at line 24 of file SceneLevelOneARenders.cpp.
References GlobalVariables::f_SuitcaseRotateY, GEO_SUITCASE, Explorer::instance(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and Variables.
Referenced by RenderScene().
void SceneLevelOneA::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 706 of file SceneLevelOneA.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneLevelOneA::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 736 of file SceneLevelOneA.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderInteract(), RenderPickUpSuitcaseText(), RenderPlayerDiesInteraction(), and RenderSavePointText().
void SceneLevelOneA::RenderToolIcon () private
Definition at line 365 of file SceneLevelOneA.cpp.
References ToolUI::BaseballBat, GEO_BATICON, GEO_HANDICON, GEO_PICKAXEICON, GEO_SWORDICON, ToolUI::Hand, Explorer::instance(), meshList, ToolUI::Pickaxe, RenderModelOnScreen(), and ToolUI::Sword.
Referenced by Render().
void SceneLevelOneA::RenderUpWall (int xPosLarge, int xPosSmall, int zPos, int wallNumber) private
Definition at line 65 of file MapRender.cpp.
References CollXLarge, CollXSmall, CollZLarge, CollZSmall, GEO_FACILITYWALLS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderScene().
void SceneLevelOneA::ResetAll () virtual
Definition at line 284 of file SceneLevelOneA.cpp.
References Explorer::checkSavePoint, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Explorer::PlayerLife, Explorer::SavePoint, and Variables.
void SceneLevelOneA::ResetSameScene () virtual
Definition at line 235 of file SceneLevelOneA.cpp.
References activateDoor1, activateDoor2_1, activateDoor2_2, activateDoor3, anima, Animation::b_toPortraitDrop, Animation::b_toPortraitFall, Explorer::checkSavePoint, Animation::ClosingDoorBtm2, Animation::ClosingDoorTop2, Animation::Collapse, Animation::DoorSlideBtm, Animation::DoorSlideBtm_2, Animation::DoorSlideBtm_3, Animation::DoorSlideTop, Animation::DoorSlideTop_2, Animation::DoorSlideTop_3, Animation::f_PortraitDrop, Animation::f_PortraitFall, GlobalVariables::f_redScreenTimer, Explorer::hp, Explorer::instance(), Explorer::isDead, Key1Active, Key_1, Notice, Notice2, Explorer::PlayerLife, Animation::RubbleCollapse, Explorer::SavePoint, Animation::toSlideDoorBtm, Animation::toSlideDoorBtm2, Animation::toSlideDoorBtm3, Animation::toSlideDoorTop, Animation::toSlideDoorTop2, Animation::toSlideDoorTop3, Variables, and willDrop.
void SceneLevelOneA::TestDoorRender () private
Definition at line 300 of file SceneLevelOneARenders.cpp.
References anima, Animation::DoorSlideBtm, Animation::DoorSlideBtm_2, Animation::DoorSlideBtm_3, Animation::DoorSlideTop, Animation::DoorSlideTop_2, Animation::DoorSlideTop_3, GEO_SLIDEDOORBTM, GEO_SLIDEDOORTOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneLevelOneA::ToolSelectionMouseScroll () private
Definition at line 332 of file SceneLevelOneA.cpp.
References ToolUI::BaseballBat, GEO_BAT, GEO_LHAND, GEO_PICKAXE, GEO_RHAND, GEO_SWORD, ToolUI::Hand, Explorer::instance(), meshList, modelStack, ToolUI::Pickaxe, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), GlobalVariables::RotateX, ToolUI::Sword, and Variables.
Referenced by Render().
void SceneLevelOneA::ToolsUI () private
Definition at line 323 of file SceneLevelOneA.cpp.
References Explorer::b_PickUpTool, camera, Explorer::InsertToolSlot(), Explorer::instance(), ToolUI::Pickaxe, Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
void SceneLevelOneA::Update (double dt) virtual
Implements Scene.
Definition at line 579 of file SceneLevelOneA.cpp.
References activateDoor1, anima, AnimationCheck(), camera, Explorer::checkDead(), checkDoor1(), checkDoor2(), checkDoor3(), checkDrop(), HostileMob::checkPlayerPos(), checkRubbleFall(), Animation::Collapsing(), Collision(), CollXLarge, CollXSmall, CollZLarge, CollZSmall, ContinueGameOrNot(), EnvironmentAnimation(), GlobalVariables::f_rotatingTool, FPS, Ghost, Explorer::hp, Explorer::instance(), Application::IsKeyPressed(), light, HostileMob::MobPosX, HostileMob::MobPosZ, MouseClickFunction(), MouseScrollToolSlot(), MobGhost::move(), Application::OpenGame(), PickUpSuitcaseInteraction(), Light::position, Camera::position, proximitycheck(), Application::SceneLevel1B(), Position::Set(), Vector3::Set(), HostileMob::Spawn, Light::spotDirection, Camera::target, ToolsUI(), Camera3::Update(), UpdatePlayerDiesInteraction(), UpdateSavePoint(), Variables, Vector3::x, Vector3::y, and Vector3::z.
void SceneLevelOneA::UpdatePlayerDiesInteraction (double dt) private
Definition at line 518 of file SceneLevelOneA.cpp.
References GlobalVariables::f_redScreenTimer, Explorer::instance(), light, m_parameters, Light::power, U_LIGHT0_POWER, and Variables.
Referenced by Update().
void SceneLevelOneA::UpdateSavePoint () private
Definition at line 502 of file SceneLevelOneA.cpp.
References camera, Explorer::ExplorerSavePoint(), Explorer::instance(), Application::IsKeyPressed(), Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
Field Documentation
bool SceneLevelOneA::activateDoor1 private
Definition at line 203 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), checkDoor1(), ResetSameScene(), SceneLevelOneA(), and Update().
bool SceneLevelOneA::activateDoor2_1 private
Definition at line 204 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), checkDoor2(), ResetSameScene(), and SceneLevelOneA().
bool SceneLevelOneA::activateDoor2_2 private
Definition at line 205 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), checkDoor2(), ResetSameScene(), and SceneLevelOneA().
bool SceneLevelOneA::activateDoor3 private
Definition at line 206 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), checkDoor3(), ResetSameScene(), and SceneLevelOneA().
Animation SceneLevelOneA::anima private
Definition at line 220 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), checkDoor1(), checkDoor2(), checkDoor3(), checkRubbleFall(), CollapseRubble(), DropPortrait(), ResetSameScene(), TestDoorRender(), and Update().
Camera3 SceneLevelOneA::camera
Definition at line 126 of file SceneLevelOneA.h.
Referenced by AttackCheck(), checkDoor2(), checkRubbleFall(), Collision(), ContinueGameOrNot(), Init(), PickUpSuitcaseInteraction(), proximitycheck(), Render(), RenderGhost(), RenderPickUpSuitcaseText(), RenderSavePointText(), ToolsUI(), Update(), and UpdateSavePoint().
float SceneLevelOneA::CollXLarge[28] private
Definition at line 235 of file SceneLevelOneA.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelOneA::CollXSmall[28] private
Definition at line 236 of file SceneLevelOneA.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelOneA::CollZLarge[28] private
Definition at line 237 of file SceneLevelOneA.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
float SceneLevelOneA::CollZSmall[28] private
Definition at line 238 of file SceneLevelOneA.h.
Referenced by RenderDownWall(), RenderLeftWall(), RenderRightWall(), RenderUpWall(), and Update().
bool SceneLevelOneA::CrosshairHit = false private
Definition at line 232 of file SceneLevelOneA.h.
Referenced by AttackCheck(), MouseClickFunction(), and Render().
bool SceneLevelOneA::displayInteract1 private
Definition at line 200 of file SceneLevelOneA.h.
Referenced by checkDoor1(), and Render().
bool SceneLevelOneA::displayInteract2 private
Definition at line 201 of file SceneLevelOneA.h.
Referenced by checkDoor2(), and Render().
bool SceneLevelOneA::displayInteract3 private
Definition at line 202 of file SceneLevelOneA.h.
Referenced by checkDoor3(), and Render().
Vector3 SceneLevelOneA::end private
Definition at line 227 of file SceneLevelOneA.h.
float SceneLevelOneA::FPS private
Definition at line 231 of file SceneLevelOneA.h.
Referenced by Render(), and Update().
MobGhost SceneLevelOneA::Ghost private
Definition at line 229 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), AttackCheck(), checkDoor2(), Init(), Render(), and Update().
bool SceneLevelOneA::Key1Active private
Definition at line 211 of file SceneLevelOneA.h.
Referenced by checkDoor1(), Render(), ResetSameScene(), and SceneLevelOneA().
bool SceneLevelOneA::Key_1 private
Definition at line 207 of file SceneLevelOneA.h.
Referenced by checkDoor1(), ResetSameScene(), and SceneLevelOneA().
Light SceneLevelOneA::light[1] private
Definition at line 224 of file SceneLevelOneA.h.
Referenced by ContinueGameOrNot(), Init(), Render(), Update(), and UpdatePlayerDiesInteraction().
unsigned SceneLevelOneA::m_parameters[U_TOTAL] private
Definition at line 218 of file SceneLevelOneA.h.
Referenced by ContinueGameOrNot(), Init(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and UpdatePlayerDiesInteraction().
unsigned SceneLevelOneA::m_programID private
Definition at line 217 of file SceneLevelOneA.h.
Referenced by Exit(), and Init().
unsigned SceneLevelOneA::m_vertexArrayID private
Definition at line 214 of file SceneLevelOneA.h.
Referenced by Exit(), and Init().
Mesh* SceneLevelOneA::meshList[NUM_GEOMETRY] private
Definition at line 215 of file SceneLevelOneA.h.
Referenced by CollapseRubble(), DropPortrait(), Init(), Render(), RenderDownWall(), RenderFloorCeiling(), RenderGhost(), RenderInteract(), RenderLeftWall(), RenderMouseScrollToolSlot(), RenderPickUpPickAxe(), RenderPickUpSuitcaseText(), RenderPlayerDiesInteraction(), RenderRightWall(), RenderSavePointText(), RenderScene(), RenderSuitCase(), RenderToolIcon(), RenderUpWall(), TestDoorRender(), and ToolSelectionMouseScroll().
MS SceneLevelOneA::modelStack private
Definition at line 222 of file SceneLevelOneA.h.
Referenced by CollapseRubble(), DropPortrait(), Render(), RenderDownWall(), RenderFloorCeiling(), RenderGhost(), RenderLeftWall(), RenderMesh(), RenderModelOnScreen(), RenderPickUpPickAxe(), RenderRightWall(), RenderScene(), RenderSuitCase(), RenderText(), RenderTextOnScreen(), RenderUpWall(), TestDoorRender(), and ToolSelectionMouseScroll().
bool SceneLevelOneA::Notice private
Definition at line 208 of file SceneLevelOneA.h.
Referenced by checkDoor1(), Render(), ResetSameScene(), and SceneLevelOneA().
bool SceneLevelOneA::Notice2 private
Definition at line 209 of file SceneLevelOneA.h.
Referenced by ResetSameScene(), and SceneLevelOneA().
MS SceneLevelOneA::projectionStack private
Definition at line 222 of file SceneLevelOneA.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
Vector3 SceneLevelOneA::start private
Definition at line 226 of file SceneLevelOneA.h.
float SceneLevelOneA::SwitchRot = 45.f private
Definition at line 212 of file SceneLevelOneA.h.
Referenced by checkDoor1(), and RenderScene().
GlobalVariables SceneLevelOneA::Variables private
Definition at line 228 of file SceneLevelOneA.h.
Referenced by ContinueGameOrNot(), EnvironmentAnimation(), MouseClickFunction(), RenderPickUpPickAxe(), RenderPlayerDiesInteraction(), RenderScene(), RenderSuitCase(), ResetAll(), ResetSameScene(), ToolSelectionMouseScroll(), Update(), and UpdatePlayerDiesInteraction().
MS SceneLevelOneA::viewStack private
Definition at line 222 of file SceneLevelOneA.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderText(), and RenderTextOnScreen().
bool SceneLevelOneA::willDrop private
Definition at line 210 of file SceneLevelOneA.h.
Referenced by AnimationCheck(), checkDrop(), ResetSameScene(), and SceneLevelOneA().
The documentation for this class was generated from the following files:
ComGraphics/Source/SceneLevelOneA.h
ComGraphics/Source/MapRender.cpp
ComGraphics/Source/SceneLevelOneA.cpp
ComGraphics/Source/SceneLevelOneARenders.cpp