My Application: OpeningCutScene Class Reference
OpeningCutScene Class Reference
#include <OpeningCutScene.h>
Public Member Functions
OpeningCutScene ()
~OpeningCutScene ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
vector< string > ReadFromText (string link)
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
vector< string > readText
vector< string > TestYou
vector< string >::iterator its = readText.begin()
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE { GEO_TEXT, GEO_TEXTBACKGROUND, NUM_GEOMETRY }
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void RenderOpeningCutScene (vector< string > Test)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
GlobalVariables Variables
float TextMove = 0
bool toMoveText = true
bool appearText = false
float BGMove = 0
bool toMoveBG = true
bool appearBG = false
bool startTimer = false
float timercount = 0
bool changeScene = false
Detailed Description
Definition at line 19 of file OpeningCutScene.h.
Member Enumeration Documentation
enum OpeningCutScene::GEOMETRY_TYPE private
Enumerator
GEO_TEXT
GEO_TEXTBACKGROUND
NUM_GEOMETRY
Definition at line 21 of file OpeningCutScene.h.
enum OpeningCutScene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 28 of file OpeningCutScene.h.
Constructor & Destructor Documentation
OpeningCutScene::OpeningCutScene ()
Definition at line 16 of file OpeningCutScene.cpp.
OpeningCutScene::~OpeningCutScene ()
Definition at line 20 of file OpeningCutScene.cpp.
Member Function Documentation
void OpeningCutScene::Exit () virtual
Implements Scene.
Definition at line 392 of file OpeningCutScene.cpp.
References m_programID, and m_vertexArrayID.
void OpeningCutScene::Init () virtual
Implements Scene.
Definition at line 24 of file OpeningCutScene.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_TEXT, GEO_TEXTBACKGROUND, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, ReadFromText(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, TestYou, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
vector< string > OpeningCutScene::ReadFromText (string link)
Definition at line 123 of file OpeningCutScene.cpp.
References readText.
Referenced by Init().
void OpeningCutScene::Render () virtual
Implements Scene.
Definition at line 354 of file OpeningCutScene.cpp.
References camera, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, modelStack, Light::position, Camera::position, RenderOpeningCutScene(), Light::spotDirection, Camera::target, TestYou, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void OpeningCutScene::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 243 of file OpeningCutScene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderModelOnScreen().
void OpeningCutScene::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 333 of file OpeningCutScene.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by RenderOpeningCutScene().
void OpeningCutScene::RenderOpeningCutScene (vector< string > Test) private
Definition at line 149 of file OpeningCutScene.cpp.
References BGMove, GEO_TEXT, GEO_TEXTBACKGROUND, its, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), RenderTextOnScreen(), startTimer, TestYou, TextMove, and toMoveBG.
Referenced by Render().
void OpeningCutScene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 287 of file OpeningCutScene.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderOpeningCutScene().
void OpeningCutScene::Reset () virtual
Definition at line 119 of file OpeningCutScene.cpp.
void OpeningCutScene::Update (double dt) virtual
Implements Scene.
Definition at line 182 of file OpeningCutScene.cpp.
References appearBG, appearText, BGMove, camera, changeScene, Application::IsKeyPressed(), light, Application::OpenCutScene2(), Light::position, Camera::position, Position::Set(), Vector3::Set(), Light::spotDirection, Application::StartingScene(), startTimer, Camera::target, TextMove, timercount, toMoveBG, toMoveText, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Animation OpeningCutScene::anima private
Definition at line 89 of file OpeningCutScene.h.
bool OpeningCutScene::appearBG = false private
Definition at line 104 of file OpeningCutScene.h.
Referenced by Update().
bool OpeningCutScene::appearText = false private
Definition at line 101 of file OpeningCutScene.h.
Referenced by Update().
float OpeningCutScene::BGMove = 0 private
Definition at line 102 of file OpeningCutScene.h.
Referenced by RenderOpeningCutScene(), and Update().
Camera3 OpeningCutScene::camera
Definition at line 68 of file OpeningCutScene.h.
Referenced by Init(), Render(), and Update().
bool OpeningCutScene::changeScene = false private
Definition at line 109 of file OpeningCutScene.h.
Referenced by Update().
Vector3 OpeningCutScene::end private
Definition at line 96 of file OpeningCutScene.h.
vector<string>::iterator OpeningCutScene::its = readText.begin()
Definition at line 73 of file OpeningCutScene.h.
Referenced by RenderOpeningCutScene().
Light OpeningCutScene::light[1] private
Definition at line 93 of file OpeningCutScene.h.
Referenced by Init(), Render(), and Update().
unsigned OpeningCutScene::m_parameters[U_TOTAL] private
Definition at line 87 of file OpeningCutScene.h.
Referenced by Init(), Render(), RenderMesh(), and RenderTextOnScreen().
unsigned OpeningCutScene::m_programID private
Definition at line 86 of file OpeningCutScene.h.
Referenced by Exit(), and Init().
unsigned OpeningCutScene::m_vertexArrayID private
Definition at line 83 of file OpeningCutScene.h.
Referenced by Exit(), and Init().
Mesh* OpeningCutScene::meshList[NUM_GEOMETRY] private
Definition at line 84 of file OpeningCutScene.h.
Referenced by Init(), and RenderOpeningCutScene().
MS OpeningCutScene::modelStack private
Definition at line 91 of file OpeningCutScene.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), RenderOpeningCutScene(), and RenderTextOnScreen().
MS OpeningCutScene::projectionStack private
Definition at line 91 of file OpeningCutScene.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), and RenderTextOnScreen().
vector<string> OpeningCutScene::readText
Definition at line 70 of file OpeningCutScene.h.
Referenced by ReadFromText().
Vector3 OpeningCutScene::start private
Definition at line 95 of file OpeningCutScene.h.
bool OpeningCutScene::startTimer = false private
Definition at line 106 of file OpeningCutScene.h.
Referenced by RenderOpeningCutScene(), and Update().
vector<string> OpeningCutScene::TestYou
Definition at line 72 of file OpeningCutScene.h.
Referenced by Init(), Render(), and RenderOpeningCutScene().
float OpeningCutScene::TextMove = 0 private
Definition at line 99 of file OpeningCutScene.h.
Referenced by RenderOpeningCutScene(), and Update().
float OpeningCutScene::timercount = 0 private
Definition at line 107 of file OpeningCutScene.h.
Referenced by Update().
bool OpeningCutScene::toMoveBG = true private
Definition at line 103 of file OpeningCutScene.h.
Referenced by RenderOpeningCutScene(), and Update().
bool OpeningCutScene::toMoveText = true private
Definition at line 100 of file OpeningCutScene.h.
Referenced by Update().
GlobalVariables OpeningCutScene::Variables private
Definition at line 97 of file OpeningCutScene.h.
MS OpeningCutScene::viewStack private
Definition at line 91 of file OpeningCutScene.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGraphics/Source/OpeningCutScene.h
ComGraphics/Source/OpeningCutScene.cpp