My Application: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
static void OpenCutScene ()
static void OpenCutScene2 ()
static void OpenGame ()
static void SceneLevel1A ()
static void SceneLevel1B ()
static void SceneLevel2 ()
static void FirstCutScene ()
static void StartingScene ()
static void EndingScene ()
static void EndingCutScene ()
static void End_Credits ()
Static Public Attributes
static int mouse_scroll = 0
static Music * musics
static Scene * scene
static Scene * IntroScene
static Scene * IntroScene2
static Scene * Opening
static Scene * Start
static Scene * LevelOneA
static Scene * LevelOneB
static Scene * LevelTwo
static Scene * End
static Scene * CutScene1
static Scene * EndScene
static Scene * EndCredits
Private Attributes
StopWatch m_timer
Detailed Description
Definition at line 14 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 47 of file Application.cpp.
Application::~Application ()
Definition at line 52 of file Application.cpp.
Member Function Documentation
void Application::End_Credits () static
Definition at line 256 of file Application.cpp.
References EndCredits, Scene::Init(), and scene.
Referenced by SceneEndCutScene::Update().
void Application::EndingCutScene () static
Definition at line 250 of file Application.cpp.
References EndScene, Scene::Init(), and scene.
Referenced by SceneEnd::Update().
void Application::EndingScene () static
Definition at line 232 of file Application.cpp.
References End, Scene::Init(), and scene.
Referenced by SceneLevelTwo::SomeUpdates().
void Application::Exit ()
Definition at line 189 of file Application.cpp.
References m_window.
Referenced by SceneOpening::ChangeScene(), and main().
void Application::FirstCutScene () static
Definition at line 209 of file Application.cpp.
References CutScene1, Scene::Init(), and scene.
Referenced by SceneStart::ChangeFirstCutScene().
void Application::Init ()
Definition at line 79 of file Application.cpp.
References error_callback(), m_window, resize_callback(), and scroll_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 42 of file Application.cpp.
Referenced by SceneLevelOneB::attackCheck(), SceneLevelOneA::AttackCheck(), SceneStart::ChangeFirstCutScene(), SceneOpening::ChangeScene(), SceneEnd::checkAttack(), SceneLevelOneB::checkDoor1(), SceneLevelOneA::checkDoor1(), SceneLevelOneA::checkDoor2(), SceneLevelOneB::checkDoor3(), SceneLevelOneA::checkDoor3(), SceneLevelOneB::checkDoor4(), SceneLevelTwo::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), SceneEnd::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), SceneLevelOneB::ElevatorCheck(), Camera3::HumanControl(), SceneLevelTwo::MouseClickFunction(), SceneStart::MouseClickFunction(), SceneLevelOneA::MouseClickFunction(), SceneLevelOneB::MouseClickFunction(), SceneEnd::MouseClickFunction(), SceneLevelOneB::PuzzleOneSwitchCheck(), Run(), SceneLevelTwo::SomeUpdates(), SceneLevelTwo::SwitchCheck(), Camera::Update(), CutSceneOne::Update(), SceneOpening::Update(), OpeningCutScene::Update(), Credits::Update(), OpeningCutScene2::Update(), SceneEndCutScene::Update(), SceneLevelTwo::Update(), SceneLevelOneA::Update(), SceneStart::Update(), SceneLevelOneB::Update(), SceneEnd::Update(), and SceneLevelOneA::UpdateSavePoint().
void Application::OpenCutScene () static
Definition at line 238 of file Application.cpp.
References Scene::Init(), IntroScene, and scene.
Referenced by SceneOpening::ChangeScene().
void Application::OpenCutScene2 () static
Definition at line 244 of file Application.cpp.
References Scene::Init(), IntroScene2, and scene.
Referenced by OpeningCutScene::Update().
void Application::OpenGame () static
Definition at line 197 of file Application.cpp.
References Scene::Init(), Opening, and scene.
Referenced by SceneLevelTwo::ContinueGameOrNot(), SceneLevelOneB::ContinueGameOrNot(), SceneEnd::ContinueGameOrNot(), SceneLevelOneA::ContinueGameOrNot(), Credits::RenderMovingCredits(), SceneLevelTwo::Update(), SceneLevelOneA::Update(), SceneLevelOneB::Update(), and SceneEnd::Update().
void Application::Run ()
Definition at line 133 of file Application.cpp.
References CutScene1, End, EndCredits, EndScene, Scene::Exit(), frameTime, StopWatch::getElapsedTime(), Music::init(), Scene::Init(), IntroScene, IntroScene2, IsKeyPressed(), LevelOneA, LevelOneB, LevelTwo, m_timer, m_window, mouse_scroll, musics, Opening, Scene::Render(), scene, scroll_callback(), Start, StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
void Application::SceneLevel1A () static
Definition at line 214 of file Application.cpp.
References Scene::Init(), LevelOneA, and scene.
Referenced by CutSceneOne::Update().
void Application::SceneLevel1B () static
Definition at line 220 of file Application.cpp.
References Scene::Init(), LevelOneB, and scene.
Referenced by SceneLevelOneA::Update().
void Application::SceneLevel2 () static
Definition at line 226 of file Application.cpp.
References Scene::Init(), LevelTwo, and scene.
Referenced by SceneLevelOneB::ElevatorCheck().
void Application::StartingScene () static
Definition at line 203 of file Application.cpp.
References Scene::Init(), scene, and Start.
Referenced by OpeningCutScene::Update(), and OpeningCutScene2::Update().
Field Documentation
Scene * Application::CutScene1 static
Definition at line 48 of file Application.h.
Referenced by FirstCutScene(), and Run().
Scene * Application::End static
Definition at line 47 of file Application.h.
Referenced by EndingScene(), and Run().
Scene * Application::EndCredits static
Definition at line 50 of file Application.h.
Referenced by End_Credits(), and Run().
Scene * Application::EndScene static
Definition at line 49 of file Application.h.
Referenced by EndingCutScene(), and Run().
Scene * Application::IntroScene static
Definition at line 40 of file Application.h.
Referenced by OpenCutScene(), and Run().
Scene * Application::IntroScene2 static
Definition at line 41 of file Application.h.
Referenced by OpenCutScene2(), and Run().
Scene * Application::LevelOneA static
Definition at line 44 of file Application.h.
Referenced by Run(), and SceneLevel1A().
Scene * Application::LevelOneB static
Definition at line 45 of file Application.h.
Referenced by Run(), and SceneLevel1B().
Scene * Application::LevelTwo static
Definition at line 46 of file Application.h.
Referenced by Run(), and SceneLevel2().
StopWatch Application::m_timer private
Definition at line 54 of file Application.h.
Referenced by Run().
int Application::mouse_scroll = 0 static
Definition at line 23 of file Application.h.
Referenced by SceneLevelTwo::MouseScrollToolSlot(), SceneStart::MouseScrollToolSlot(), SceneLevelOneA::MouseScrollToolSlot(), SceneLevelOneB::MouseScrollToolSlot(), SceneEnd::MouseScrollToolSlot(), SceneOpening::OptionChange(), Run(), and scroll_callback().
Music * Application::musics static
Definition at line 37 of file Application.h.
Referenced by Run().
Scene * Application::Opening static
Definition at line 42 of file Application.h.
Referenced by OpenGame(), and Run().
Scene * Application::scene static
Definition at line 39 of file Application.h.
Referenced by End_Credits(), EndingCutScene(), EndingScene(), FirstCutScene(), OpenCutScene(), OpenCutScene2(), OpenGame(), Run(), SceneLevel1A(), SceneLevel1B(), SceneLevel2(), and StartingScene().
Scene * Application::Start static
Definition at line 43 of file Application.h.
Referenced by Run(), and StartingScene().
The documentation for this class was generated from the following files:
ComGraphics/Source/Application.h
ComGraphics/Source/Application.cpp