My Application: Credits Class Reference
Credits Class Reference
#include <Credits.h>
Public Member Functions
Credits ()
~Credits ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Reset ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Camera3 camera
Data Fields inherited from Scene
GlobalVariables Variables
ToolUI::ToolType Tool
SwitchLightPuzzle Switches
misc Misc
Private Types
enum GEOMETRY_TYPE {
GEO_TITLE, GEO_TEXT, GEO_TEXTBACKGROUND, GEO_NAME1,
GEO_NAME2, GEO_NAME3, GEO_NAME4, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderModelOnScreen (Mesh *mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN)
void RenderCredits ()
void RenderMovingCredits (double dt)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Animation anima
MS modelStack
MS viewStack
MS projectionStack
Light light [1]
Vector3 start
Vector3 end
GlobalVariables Variables
float firstcredits
float secondcredits
float thirdcredits
float fourthcredits
float fifthcredits
float lastcredits
bool move1 = true
bool move2
bool move3
bool move4
bool move5
bool move6
bool first = true
bool second
bool third
bool fourth
bool fifth
bool last
float countdown
bool timer
Detailed Description
Definition at line 19 of file Credits.h.
Member Enumeration Documentation
enum Credits::GEOMETRY_TYPE private
Enumerator
GEO_TITLE
GEO_TEXT
GEO_TEXTBACKGROUND
GEO_NAME1
GEO_NAME2
GEO_NAME3
GEO_NAME4
NUM_GEOMETRY
Definition at line 21 of file Credits.h.
enum Credits::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 34 of file Credits.h.
Constructor & Destructor Documentation
Credits::Credits ()
Definition at line 16 of file Credits.cpp.
References first, move1, second, and timer.
Credits::~Credits ()
Definition at line 26 of file Credits.cpp.
Member Function Documentation
void Credits::Exit () virtual
Implements Scene.
Definition at line 515 of file Credits.cpp.
References m_programID, and m_vertexArrayID.
void Credits::Init () virtual
Implements Scene.
Definition at line 30 of file Credits.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_NAME1, GEO_NAME2, GEO_NAME3, GEO_NAME4, GEO_TEXT, GEO_TEXTBACKGROUND, GEO_TITLE, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Camera::position, Light::power, projectionStack, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, Vector3::y, and Vector3::z.
void Credits::Render () virtual
Implements Scene.
Definition at line 477 of file Credits.cpp.
References camera, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, modelStack, Light::position, Camera::position, RenderCredits(), Light::spotDirection, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void Credits::RenderCredits () private
Definition at line 141 of file Credits.cpp.
References fifth, fifthcredits, first, firstcredits, fourth, fourthcredits, GEO_NAME1, GEO_NAME2, GEO_NAME3, GEO_NAME4, GEO_TEXT, GEO_TITLE, last, lastcredits, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderModelOnScreen(), RenderTextOnScreen(), second, secondcredits, third, and thirdcredits.
Referenced by Render().
void Credits::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 366 of file Credits.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderModelOnScreen().
void Credits::RenderModelOnScreen (Mesh * mesh, float Sx, float Sy, float Sz, float Rotate, float rX, float rY, float rZ, float x, float y, float z, bool LightYN) private
Definition at line 456 of file Credits.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by RenderCredits().
void Credits::RenderMovingCredits (double dt) private
Definition at line 190 of file Credits.cpp.
References countdown, fifth, fifthcredits, first, firstcredits, fourth, fourthcredits, last, lastcredits, move1, move2, move3, move4, move5, move6, Application::OpenGame(), second, secondcredits, third, thirdcredits, and timer.
Referenced by Update().
void Credits::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 410 of file Credits.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderCredits().
void Credits::Reset () virtual
Definition at line 136 of file Credits.cpp.
void Credits::Update (double dt) virtual
Implements Scene.
Definition at line 346 of file Credits.cpp.
References camera, Application::IsKeyPressed(), light, Light::position, Camera::position, RenderMovingCredits(), Position::Set(), Vector3::Set(), Light::spotDirection, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Animation Credits::anima private
Definition at line 91 of file Credits.h.
Camera3 Credits::camera
Definition at line 74 of file Credits.h.
Referenced by Init(), Render(), and Update().
float Credits::countdown private
Definition at line 121 of file Credits.h.
Referenced by RenderMovingCredits().
Vector3 Credits::end private
Definition at line 98 of file Credits.h.
bool Credits::fifth private
Definition at line 118 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
float Credits::fifthcredits private
Definition at line 105 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
bool Credits::first = true private
Definition at line 114 of file Credits.h.
Referenced by Credits(), RenderCredits(), and RenderMovingCredits().
float Credits::firstcredits private
Definition at line 101 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
bool Credits::fourth private
Definition at line 117 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
float Credits::fourthcredits private
Definition at line 104 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
bool Credits::last private
Definition at line 119 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
float Credits::lastcredits private
Definition at line 106 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
Light Credits::light[1] private
Definition at line 95 of file Credits.h.
Referenced by Init(), Render(), and Update().
unsigned Credits::m_parameters[U_TOTAL] private
Definition at line 89 of file Credits.h.
Referenced by Init(), Render(), RenderMesh(), and RenderTextOnScreen().
unsigned Credits::m_programID private
Definition at line 88 of file Credits.h.
Referenced by Exit(), and Init().
unsigned Credits::m_vertexArrayID private
Definition at line 85 of file Credits.h.
Referenced by Exit(), and Init().
Mesh* Credits::meshList[NUM_GEOMETRY] private
Definition at line 86 of file Credits.h.
Referenced by Init(), and RenderCredits().
MS Credits::modelStack private
Definition at line 93 of file Credits.h.
Referenced by Render(), RenderCredits(), RenderMesh(), RenderModelOnScreen(), and RenderTextOnScreen().
bool Credits::move1 = true private
Definition at line 108 of file Credits.h.
Referenced by Credits(), and RenderMovingCredits().
bool Credits::move2 private
Definition at line 109 of file Credits.h.
Referenced by RenderMovingCredits().
bool Credits::move3 private
Definition at line 110 of file Credits.h.
Referenced by RenderMovingCredits().
bool Credits::move4 private
Definition at line 111 of file Credits.h.
Referenced by RenderMovingCredits().
bool Credits::move5 private
Definition at line 112 of file Credits.h.
Referenced by RenderMovingCredits().
bool Credits::move6 private
Definition at line 113 of file Credits.h.
Referenced by RenderMovingCredits().
MS Credits::projectionStack private
Definition at line 93 of file Credits.h.
Referenced by Init(), RenderMesh(), RenderModelOnScreen(), and RenderTextOnScreen().
bool Credits::second private
Definition at line 115 of file Credits.h.
Referenced by Credits(), RenderCredits(), and RenderMovingCredits().
float Credits::secondcredits private
Definition at line 102 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
Vector3 Credits::start private
Definition at line 97 of file Credits.h.
bool Credits::third private
Definition at line 116 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
float Credits::thirdcredits private
Definition at line 103 of file Credits.h.
Referenced by RenderCredits(), and RenderMovingCredits().
bool Credits::timer private
Definition at line 122 of file Credits.h.
Referenced by Credits(), and RenderMovingCredits().
GlobalVariables Credits::Variables private
Definition at line 99 of file Credits.h.
MS Credits::viewStack private
Definition at line 93 of file Credits.h.
Referenced by Render(), RenderMesh(), RenderModelOnScreen(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGraphics/Source/Credits.h
ComGraphics/Source/Credits.cpp