My Application: Math Namespace Reference
Math Namespace Reference
Math namespace.
Functions
float FAbs (float value)
float DegreeToRadian (float value)
Converts from degrees to radians.
float RadianToDegree (float value)
Converts from radians to degrees.
template<typename T >
T Wrap (T val, T minVal, T maxVal)
Keeps a value between a min and max point. If it goes to low, it will become the max. If the value gets too high, it will become the min.
template<typename T >
T Clamp (T val, T minVal, T maxVal)
Keeps a value between a min and max point. If it goes to low, it will become the min. If the value gets too high, it will become the max.
template<typename T >
T Min (T x, T y)
Returns the smaller of the two values.
template<typename T >
T Max (T x, T y)
Returns the larger of the two values.
template<typename T >
T Square (T x)
Returns the square of a value.
void InitRNG (void)
Initialize Random Number Generator.
unsigned RandInt (void)
Return a random integer.
int RandIntMinMax (int min, int max)
Return a random integer between min and max.
float RandFloat (void)
Return a random float.
float RandFloatMinMax (float min, float max)
Return a random float between min and max.
Variables
const float EPSILON = 0.00001f
const float PI = 3.1415926535897932384626433832795f
Used for error checking.
const float TWO_PI = PI * 2.0f
const float HALF_PI = PI / 2.0f
const float QUARTER_PI = PI / 4.0f
Detailed Description
Math namespace.
Function Documentation
template<typename T > T Math::Clamp (T val, T minVal, T maxVal)
Keeps a value between a min and max point. If it goes to low, it will become the min. If the value gets too high, it will become the max.
Parameters
val - the value to clamp.
minVal - the minimum value allowed.
maxVal - the maximum value allowed.
Exceptions
None
Returns
The clampped value.
Definition at line 111 of file MyMath.h.
float Math::DegreeToRadian (float value) inline
Converts from degrees to radians.
Parameters
value - an angle in degress
Exceptions
None
Returns
the angle in radians
Definition at line 49 of file MyMath.h.
Referenced by Camera3::CameraRotation(), CircleX(), CircleZ(), SceneLevelTwo::Collision(), SceneStart::Collision(), SceneLevelOneB::Collision(), SceneLevelOneA::Collision(), SceneEnd::Collision(), MeshBuilder::GenerateTorus(), Camera3::HumanControl(), CutSceneOne::Init(), SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneStart::Init(), SceneLevelOneB::Init(), SceneEnd::Init(), SceneLevelTwo::SpecialCollision(), SphereX(), SphereY(), SphereZ(), and Camera3::Update().
float Math::FAbs (float value) inline
Definition at line 33 of file MyMath.h.
Referenced by Mtx44::GetInverse(), and Mtx44::SetToRotation().
void Math::InitRNG (void) inline
Initialize Random Number Generator.
Parameters
None
Exceptions
None
Returns
None
Definition at line 184 of file MyMath.h.
template<typename T > T Math::Max (T x, T y)
Returns the larger of the two values.
Parameters
x the first value to check
y the second value to check
Exceptions
None
Returns
The larger of the two values
Definition at line 154 of file MyMath.h.
template<typename T > T Math::Min (T x, T y)
Returns the smaller of the two values.
Parameters
x the first value to check
y the second value to check
Exceptions
None
Returns
The smaller of the two values
Definition at line 137 of file MyMath.h.
float Math::RadianToDegree (float value) inline
Converts from radians to degrees.
Parameters
value - an angle in radians
Exceptions
None
Returns
the angle in degrees
Definition at line 64 of file MyMath.h.
References PI.
Referenced by getAngle(), SceneLevelOneB::RenderBoss(), SceneEnd::RenderBoss(), SceneLevelOneA::RenderGhost(), SceneLevelOneB::RenderGhost(), and SceneEnd::RenderMobs().
float Math::RandFloat (void) inline
Return a random float.
Parameters
None
Exceptions
None
Returns
Random float
Definition at line 231 of file MyMath.h.
Referenced by RandFloatMinMax().
float Math::RandFloatMinMax (float min, float max) inline
Return a random float between min and max.
Parameters
min - minimum range
max - maximum range
Exceptions
None
Returns
Random float
Definition at line 247 of file MyMath.h.
References RandFloat().
unsigned Math::RandInt (void) inline
Return a random integer.
Parameters
None
Exceptions
None
Returns
Random integer
Definition at line 199 of file MyMath.h.
int Math::RandIntMinMax (int min, int max) inline
Return a random integer between min and max.
Parameters
min - minimum range
max - maximum range
Exceptions
None
Returns
Random integer
Definition at line 215 of file MyMath.h.
template<typename T > T Math::Square (T x)
Returns the square of a value.
Parameters
x the value
Exceptions
None
Returns
The square of the value
Definition at line 170 of file MyMath.h.
template<typename T > T Math::Wrap (T val, T minVal, T maxVal)
Keeps a value between a min and max point. If it goes to low, it will become the max. If the value gets too high, it will become the min.
Parameters
val - the value to Wrap.
minVal - the minimum value allowed.
maxVal - the maximum value allowed.
Exceptions
None
Returns
The wrapped value.
Definition at line 83 of file MyMath.h.
Variable Documentation
const float Math::EPSILON = 0.00001f
Definition at line 27 of file MyMath.h.
Referenced by Mtx44::GetInverse(), Vector3::IsEqual(), Vector3::Normalize(), Vector3::Normalized(), and Mtx44::SetToRotation().
const float Math::HALF_PI = PI / 2.0f
Definition at line 30 of file MyMath.h.
const float Math::PI = 3.1415926535897932384626433832795f
Used for error checking.
Definition at line 28 of file MyMath.h.
Referenced by RadianToDegree(), Mtx44::SetToPerspective(), and Mtx44::SetToRotation().
const float Math::QUARTER_PI = PI / 4.0f
Definition at line 31 of file MyMath.h.
const float Math::TWO_PI = PI * 2.0f
Definition at line 29 of file MyMath.h.