My Application: Position Struct Reference
Position Struct Reference
#include <Vertex.h>
Public Member Functions
Position (float x=0, float y=0, float z=0)
void Set (float x, float y, float z)
Data Fields
float x
float y
float z
Detailed Description
Definition at line 18 of file Vertex.h.
Constructor & Destructor Documentation
Position::Position (float x = 0, float y = 0, float z = 0) inline
Definition at line 21 of file Vertex.h.
References Set().
Member Function Documentation
void Position::Set (float x, float y, float z) inline
Definition at line 22 of file Vertex.h.
References x, y, and z.
Referenced by MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateCylinder(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRing(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), MeshBuilder::GenerateTorus(), IndexVBO(), CutSceneOne::Init(), SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), SceneLevelOneB::Init(), Light::Light(), Position(), CutSceneOne::Update(), SceneOpening::Update(), OpeningCutScene::Update(), Credits::Update(), OpeningCutScene2::Update(), SceneEndCutScene::Update(), SceneStart::Update(), SceneLevelTwo::Update(), SceneLevelOneA::Update(), SceneEnd::Update(), and SceneLevelOneB::Update().
Field Documentation
float Position::x
Definition at line 20 of file Vertex.h.
Referenced by LoadOBJ(), operator*(), CutSceneOne::Render(), SceneOpening::Render(), OpeningCutScene::Render(), Credits::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), and Set().
float Position::y
Definition at line 20 of file Vertex.h.
Referenced by LoadOBJ(), operator*(), CutSceneOne::Render(), SceneOpening::Render(), OpeningCutScene::Render(), Credits::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), and Set().
float Position::z
Definition at line 20 of file Vertex.h.
Referenced by LoadOBJ(), operator*(), CutSceneOne::Render(), SceneOpening::Render(), OpeningCutScene::Render(), Credits::Render(), OpeningCutScene2::Render(), SceneEndCutScene::Render(), SceneStart::Render(), SceneLevelTwo::Render(), SceneLevelOneA::Render(), SceneEnd::Render(), SceneLevelOneB::Render(), and Set().
The documentation for this struct was generated from the following file:
ComGraphics/Source/Vertex.h