My Application: Color Struct Reference
Color Struct Reference
#include <Vertex.h>
Public Member Functions
Color (float r=1, float g=1, float b=1)
void Set (float r, float g, float b)
Data Fields
float r
float g
float b
Detailed Description
Definition at line 25 of file Vertex.h.
Constructor & Destructor Documentation
Color::Color (float r = 1, float g = 1, float b = 1) inline
Definition at line 28 of file Vertex.h.
References Set().
Member Function Documentation
void Color::Set (float r, float g, float b) inline
Definition at line 29 of file Vertex.h.
References b, g, and r.
Referenced by Color(), MeshBuilder::GenerateAxes(), CutSceneOne::Init(), SceneOpening::Init(), OpeningCutScene::Init(), Credits::Init(), OpeningCutScene2::Init(), SceneEndCutScene::Init(), SceneStart::Init(), SceneLevelTwo::Init(), SceneLevelOneA::Init(), SceneEnd::Init(), SceneLevelOneB::Init(), and Light::Light().
Field Documentation
float Color::b
Definition at line 27 of file Vertex.h.
Referenced by Set().
float Color::g
Definition at line 27 of file Vertex.h.
Referenced by Set().
float Color::r
Definition at line 27 of file Vertex.h.
Referenced by SceneOpening::RenderText(), OpeningCutScene2::RenderText(), SceneEndCutScene::RenderText(), SceneStart::RenderText(), SceneEnd::RenderText(), SceneLevelTwo::RenderText(), SceneLevelOneB::RenderText(), SceneLevelOneA::RenderText(), SceneOpening::RenderTextOnScreen(), OpeningCutScene::RenderTextOnScreen(), Credits::RenderTextOnScreen(), OpeningCutScene2::RenderTextOnScreen(), SceneEndCutScene::RenderTextOnScreen(), SceneStart::RenderTextOnScreen(), SceneEnd::RenderTextOnScreen(), SceneLevelTwo::RenderTextOnScreen(), SceneLevelOneB::RenderTextOnScreen(), SceneLevelOneA::RenderTextOnScreen(), and Set().
The documentation for this struct was generated from the following file:
ComGraphics/Source/Vertex.h